# Income Elasticity = 0 Model Run - Tables

In [1]:
using Mimi
using MimiFUND
using DelimitedFiles

In [2]:
function set_custom_params!(m)
    set_param!(m, :vbel, -0.00001)
    set_param!(m, :diamortel, -0.00001)
    set_param!(m, :diayldel, -0.00001)
    set_param!(m, :hurrdeadel, -0.00001)
    set_param!(m, :extratropicalstormsdeadel, -0.00001)
end

set_custom_params! (generic function with 1 method)

In [3]:
m1 = MimiFUND.get_model();
set_custom_params!(m1)

In [4]:
run(m1);

# Discount Factor

In [5]:
baseyear = 60
prtp = 0.01
eta = 1.0
ypc = m1[:socioeconomic, :ypc]
df_r = [t>=baseyear ? (ypc[baseyear,r]/ypc[t,r])^eta *
(1.0+prtp)^-(t-baseyear) : 0.0 for t in 1:1051, r in 1:16];
#df_r_1=df_r;
df_r_1=df_r[50:350,:];

# Key Variables

### Population - global population is in people while regional population is in millions

In [6]:
pop=m1[:population, :globalpopulation];

In [7]:
pop_glob=pop[50:350,:];

In [8]:
pop_glob_2015=pop[65,:]

1-element Vector{Union{Missing, Float64}}:
 7.136994511743061e9

In [9]:
pop_sum=sum(pop[50:350,:])

2.8688070717254937e12

In [10]:
pop_reg=m1[:population,:population][50:350,:];

In [11]:
pop_reg_2015=m1[:population,:population][65,:]

16-element Vector{Union{Missing, Float64}}:
  296.64533417997785
   33.43124830027777
  394.803410095592
  192.84043982255113
   23.553988129071048
  126.78218518501934
  293.6489991539043
  316.05843318288566
  154.35358707928273
  414.7195244315594
 1669.499370007048
  629.3898515858369
 1467.5064430352088
  192.370918420008
  878.0032678336242
   53.38751130121562

In [12]:
pop_reg_sum=sum(m1[:population,:population][50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 88947.4  10081.8  1.18354e5  66470.1  …  1.06831e5  4.39945e5  20083.8

#### Alternative Regions 

In [13]:
pop_r=m1[:population,:population];
pop_high=sum(pop_r[50:350,1:5],dims=2)
pop_med=(pop_r[50:350,6]+sum(pop_r[50:350,8:10],dims=2)+sum(pop_r[50:350,12:13],dims=2))
pop_low=(pop_r[50:350,7]+pop_r[50:350,11]+pop_r[50:350,14]+pop_r[50:350,15]+pop_r[50:350,16])
pop_high_avg=sum(pop_high)/301
pop_med_avg=sum(pop_med)/301
pop_low_avg=sum(pop_low)/301
pop_high_2015=sum(pop_r[65,1:5],dims=2)
pop_med_2015=(pop_r[65,6]+sum(pop_r[65,8:10])+sum(pop_r[65,12:13]))
pop_low_2015=(pop_r[65,7]+pop_r[65,11]+pop_r[65,14]+pop_r[65,15]+pop_r[65,16])

3086.9100667158

### Income - billions USD1995

In [14]:
globalincome= m1[:socioeconomic, :globalincome];

In [15]:
GDP_glob=globalincome[50:350,:];

In [16]:
GDP_glob_2015=globalincome[65,:]

1-element Vector{Union{Missing, Float64}}:
 47678.27610454091

In [17]:
income= m1[:socioeconomic, :income];

In [18]:
GDP_reg=income[50:350,:];

In [19]:
GDP_reg_2015=income[65,:]

16-element Vector{Union{Missing, Float64}}:
 12358.248081513664
   978.869745795805
 13481.458500401504
  8822.809888826234
   759.2688531977443
   589.752477985309
   827.0262854422156
  1095.106448029111
   657.7103796623765
  2296.4417322086542
  1075.6117639648041
  1463.5581401941959
  2265.405427158926
   333.31631263578515
   589.6629436045165
    84.02912392005976

In [20]:
GDP_reg_sum=sum(df_r_1.*GDP_reg,dims=1)

1×16 Matrix{Float64}:
 1.0784e6  85614.5  1.17058e6  8.6354e5  …  48005.2  80686.4  8640.86

In [21]:
GDP_glob_sum=sum(df_r_1.*GDP_reg)

4.4732662935610125e6

#### Alternative Regions 

In [22]:
gdp_high=sum(income[50:350,1:5],dims=2)
gdp_med=(income[50:350,6]+sum(income[50:350,8:10],dims=2)+sum(income[50:350,12:13],dims=2))
gdp_low=(income[50:350,7]+income[50:350,11]+income[50:350,14]+income[50:350,15]+income[50:350,16])
gdp_high2=sum(df_r[50:350,1:5].*income[50:350,1:5],dims=2)
gdp_med2=(df_r[50:350,6].*income[50:350,6]+sum(df_r[50:350,8:10].*income[50:350,8:10],dims=2)+sum(df_r[50:350,12:13].*income[50:350,12:13],dims=2))
gdp_low2=(df_r[50:350,7].*income[50:350,7]+df_r[50:350,11].*income[50:350,11]+df_r[50:350,14].*income[50:350,14]+df_r[50:350,15].*income[50:350,15]+df_r[50:350,16].*income[50:350,16])
gdp_high_avg=sum(gdp_high2)/291
gdp_med_avg=sum(gdp_med2)/291
gdp_low_avg=sum(gdp_low2)/291
gdp_high_2015=sum(income[65,1:5],dims=2)
gdp_med_2015=(income[65,6]+sum(income[65,8:10])+sum(income[65,12:13]))
gdp_low_2015=(income[65,7]+income[65,11]+income[65,14]+income[65,15]+income[65,16])

2909.646429567381

### Income per capita 

In [23]:
ypc = m1[:socioeconomic, :ypc];

In [24]:
globalypc=m1[:socioeconomic, :globalypc]
ypc_glob=globalypc[50:350,:]

301×1 Matrix{Union{Missing, Float64}}:
   5337.363876252127
   5422.374259667928
   5568.935373127882
   5637.897027516389
   5710.171043294306
   5785.143299296734
   5862.824843936407
   5943.279104285226
   6026.55744917073
   6112.777771536882
   6202.049312025879
   6294.454322545399
   6389.5936461594965
      ⋮
 117555.46639272776
 118272.79882214549
 118991.4084451451
 119711.26358706615
 120432.33235337144
 121154.58264550105
 121877.98217388373
 122602.49843437914
 123328.09873541872
 124054.75020725002
 124782.41979887999
 125511.0742959684

In [25]:
ypc_glob_2015=globalypc[65,:]

1-element Vector{Union{Missing, Float64}}:
 6680.441749827896

In [26]:
ypc_reg=ypc[50:350,:];

In [27]:
ypc_reg_2015=ypc[65,:]

16-element Vector{Union{Missing, Float64}}:
 41660.01166233002
 29280.083621276917
 34147.26964272496
 45751.865619809054
 32235.256680826446
  4651.698321216462
  2816.3769937072493
  3464.886024399903
  4261.0631350248295
  5537.3369154883685
   644.2720394439343
  2325.3602461281407
  1543.7107195750648
  1732.6751640705263
   671.5953860393305
  1573.9471998603246

In [28]:
ypc_reg_sum=sum(df_r_1.*ypc_reg,dims=1)

1×16 Matrix{Float64}:
 3.63323e6  2.55153e6  2.9689e6  3.97383e6  …  1.4648e5  56708.1  1.32738e5

In [29]:
ypc_reg_avg=ypc_reg_sum/291

1×16 Matrix{Float64}:
 12485.3  8768.14  10202.4  13655.8  …  438.336  503.369  194.873  456.144

In [30]:
ypc_reg_pop_avg=sum(df_r_1.*ypc_reg.*pop_reg,dims=1)./sum(pop_reg,dims=1)

1×16 Matrix{Float64}:
 12124.0  8491.96  9890.46  12991.4  …  418.62  449.356  183.401  430.241

In [31]:
ypc_glob_avg=(sum(GDP_reg_sum.*pop_reg)./sum(pop_reg))/291

777.9191627298336

In [32]:
ypc_glob_pop_avg=sum(df_r_1.*ypc_reg.*pop_reg)./sum(pop_reg)

1559.2774912083903

#### Alternative Regions 

In [33]:
ypc_high=1000*gdp_high./pop_high
ypc_med=1000*gdp_med./pop_med
ypc_low=1000*gdp_low./pop_low;
ypc_high_avg=1000*gdp_high_avg/pop_high_avg*(301/291)
ypc_med_avg=1000*gdp_med_avg/pop_med_avg*(301/291)
ypc_low_avg=1000*gdp_low_avg/pop_low_avg*(301/291)
ypc_high_2015=1000*gdp_high_2015./pop_high_2015
ypc_med_2015=1000*gdp_med_2015./pop_med_2015
ypc_low_2015=1000*gdp_low_2015./pop_low_2015

942.575704080355

## Deaths

In [34]:
deaths = m1[:impactdeathmorbidity, :dead];

In [35]:
deaths_reg=deaths[50:350,:];

In [36]:
deaths_reg_2015=deaths[65,:]

16-element Vector{Union{Missing, Float64}}:
   1349.1299359854859
      5.324754212051623
    701.7274927120093
    261.1447809159548
      2.512467497448858
    342.9355433077021
  11226.398072370639
   1025.164310549498
   1149.4462590980968
   2760.311950684234
  24763.797868612306
   3727.3301722985443
  14788.567558100443
   9886.301493462914
 176729.0328164777
    839.6737475449977

In [37]:
deaths_reg_sum=sum(deaths_reg,dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 2.60173e6  206.565  1.39105e6  529059.0  …  3.65692e7  5.69415e8  2.00514e6

In [38]:
deaths_reg_avg=sum(deaths_reg,dims=1)/301

1×16 Matrix{Float64}:
 8643.63  0.686264  4621.43  1757.67  …  1.21492e5  1.89174e6  6661.61

In [39]:
deaths_glob=sum(deaths,dims=2)[50:350,:];

In [40]:
deaths_glob_2015=sum(deaths,dims=2)[65,:]

1-element Vector{Union{Missing, Float64}}:
 249558.79922383002

In [41]:
deaths_glob_sum=sum(deaths_glob)

7.65305156847614e8

In [42]:
deaths_glob_avg=deaths_glob_sum/301

2.5425420493276212e6

#### Alternative Regions 

In [43]:
dead_high=sum(deaths[50:350,1:5],dims=2)
dead_med=(deaths[50:350,6]+sum(deaths[50:350,8:10],dims=2)+sum(deaths[50:350,12:13],dims=2))
dead_low=(deaths[50:350,7]+deaths[50:350,11]+deaths[50:350,14]+deaths[50:350,15]+deaths[50:350,16])
dead_high_sum=sum(dead_high)
dead_med_sum=sum(dead_med)
dead_low_sum=sum(dead_low)
dead_high_avg=sum(dead_high)/301
dead_med_avg=sum(dead_med)/301
dead_low_avg=sum(dead_low)/301

2.3334877486239183e6

### VSL

In [44]:
vsl=m1[:vslvmorb, :vsl];

In [45]:
vsl_reg=vsl[50:350,:];

In [46]:
vsl_reg_2015=vsl[65,:]

16-element Vector{Union{Missing, Float64}}:
      8.3320023324660035e6
      5.856016724255383e6
      6.829453928544993e6
      9.150373123961812e6
      6.447051336165289e6
 930339.6642432924
 563275.3987414499
 692977.2048799805
 852212.6270049659
      1.1074673830976738e6
 128854.40788878687
 465072.04922562814
 308742.14391501294
 346535.0328141053
 134319.0772078661
 314789.4399720649

In [47]:
vsl_reg_avg=sum(df_r_1.*vsl_reg,dims=1)/291

1×16 Matrix{Float64}:
 2.49706e6  1.75363e6  2.04048e6  2.73116e6  …  1.00674e5  38974.7  91228.8

In [48]:
vsl_reg_pop_avg=vsl_reg_pop_avg=sum(df_r_1[10:300,:].*vsl_reg[10:300,:].*deaths_reg[10:300,:],dims=1)./sum(deaths_reg[10:300,:],dims=1)

1×16 Matrix{Float64}:
 1.59248e6  6.73079e5  1.2965e6  …  55118.9  62467.2  25473.7  57919.8

In [49]:
#Incorrect
vsl_glob=sum(df_r.*vsl.*deaths,dims=2)./sum(deaths,dims=2)
vsl_glob=vsl_glob[50:350,:]

301×1 Matrix{Union{Missing, Float64}}:
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
 246993.76064561648
 242887.8084623065
 238863.25436093644
      ⋮
  13273.480647497878
  13149.78516211286
  13027.245603198353
  12905.851109790512
  12785.590916880878
  12666.45435656492
  12548.43088324551
  12431.510036748166
  12315.681453972744
  12200.934876455929
  12087.260135156916
  11974.647169237838

In [50]:
vsl_glob_2015=vsl_glob[65,:]

1-element Vector{Union{Missing, Float64}}:
 117728.76936553216

In [51]:
vsl_glob_avg=sum(vsl_glob)/291

68181.3096894899

#### Alternative Regions 

In [52]:
mort_val=vsl.*deaths
vsl_high=sum(mort_val[50:350,1:5],dims=2)./sum(deaths[50:350,1:5],dims=2)
vsl_med=(mort_val[50:350,6]+sum(mort_val[50:350,8:10],dims=2)+sum(mort_val[50:350,12:13],dims=2))./(deaths[50:350,6]+sum(deaths[50:350,8:10],dims=2)+sum(deaths[50:350,12:13],dims=2))
vsl_low=(mort_val[50:350,7]+mort_val[50:350,11]+mort_val[50:350,14]+mort_val[50:350,15]+mort_val[50:350,16])./(deaths[50:350,7]+deaths[50:350,11]+deaths[50:350,14]+deaths[50:350,15]+deaths[50:350,16]);
vsl_high_avg=sum(vsl_high)/291
vsl_med_avg=sum(vsl_med)/291
vsl_low_avg=sum(vsl_low)/291
vsl_high_pop_avg=sum(mort_val[50:350,1:5])./sum(deaths[50:350,1:5])
vsl_med_pop_avg=(sum(mort_val[50:350,6])+sum(mort_val[50:350,8:10])+sum(mort_val[50:350,12:13]))./(sum(deaths[50:350,6])+sum(deaths[50:350,8:10])+sum(deaths[50:350,12:13]))
vsl_low_pop_avg=(sum(mort_val[50:350,7])+sum(mort_val[50:350,11])+sum(mort_val[50:350,14])+sum(mort_val[50:350,15])+sum(mort_val[50:350,16]))./(sum(deaths[50:350,7])+sum(deaths[50:350,11])+sum(deaths[50:350,14])+sum(deaths[50:350,15])+sum(deaths[50:350,16]))


4.355631594122234e6

# SCC

In [53]:
m3 = MimiFUND.get_model();
set_custom_params!(m3)

In [54]:
add_comp!(m3, Mimi.adder, :co2marg, before=:climateco2cycle);

In [55]:
connect_param!(m3, :co2marg, :input, :emissions, :mco2)

In [56]:
connect_param!(m3, :climateco2cycle, :mco2, :co2marg, :output)

In [57]:
marginalemissions = zeros(1051)
marginalemissions[60] = 1
set_param!(m3, :co2marg, :add, marginalemissions);

In [58]:
run(m3)

In [59]:
md = (m3[:impactaggregation, :loss]-
    m1[:impactaggregation, :loss])/10^6;

In [60]:
pd=df_r.*md
SCC=sum(pd[60:300,:])

30.445959530692576

# Regional SCC

In [61]:
reg_SCC=sum(pd[60:300,:],dims=1);
SCC_reg=reg_SCC

1×16 Matrix{Union{Missing, Float64}}:
 5.83785  0.205104  7.13923  -0.233668  …  2.05054  6.28337  0.0202393

#### Alternative Regions 

In [62]:
SCC_high=sum(SCC_reg[1:5])
SCC_med=(SCC_reg[6]+sum(SCC_reg[8:10])+sum(SCC_reg[12:13]))
SCC_low=(SCC_reg[7]+SCC_reg[11]+SCC_reg[14]+SCC_reg[15]+SCC_reg[16])

12.340092995598276

## Health SCC

In [63]:
marg_health=10^9*((m3[:impactdeathmorbidity, :deadcost]+m3[:impactdeathmorbidity, :morbcost])-(m1[:impactdeathmorbidity, :deadcost]+m1[:impactdeathmorbidity, :morbcost]));

In [64]:
pd_health=(df_r.*marg_health)/10^6
health_SCC=sum(pd_health[60:300,:])

12.342858128849794

In [65]:
Perc_Health_SCC=health_SCC/SCC

0.4054021722129321

## Health Regional SCC

In [66]:
reg_health_SCC=sum(pd_health[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 1.82678  7.52886e-5  0.786748  0.385396  …  0.677152  5.19292  0.0480915

In [67]:
Reg_Perc_Health_SCC=reg_health_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.31292  0.000367075  0.110201  -1.64933  …  0.330232  0.826455  2.37614

In [68]:
Perc_health_SCC_reg=reg_health_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.31292  0.000367075  0.110201  -1.64933  …  0.330232  0.826455  2.37614

#### Alternative Regions 

In [69]:
health_SCC_high=sum(reg_health_SCC[1:5])
health_SCC_med=(reg_health_SCC[6]+sum(reg_health_SCC[8:10])+sum(reg_health_SCC[12:13]))
health_SCC_low=(reg_health_SCC[7]+reg_health_SCC[11]+reg_health_SCC[14]+reg_health_SCC[15]+reg_health_SCC[16])

7.327453457186693

# Health Endpoint SCC

### Dengue Fever 

In [70]:
dv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :dengue]./(10^9)

trick=ones(1051,16)
trick2=m1[:impactdeathmorbidity, :d2dd]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick

#dv_2=m1[:vslvmorb, :vmorb]*parameters["d2dd"].*m1[:impactvectorbornediseases, :dengue]./1000000000.0
dv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :dengue]./(10^9)
dv_3=dv_1+dv_2
pv_dv_1=df_r.*dv_1
pv_dv_2=df_r.*dv_2
pv_dv_3=df_r.*dv_3;

In [71]:
dv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :dengue]./(10^9)

trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dd]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick;

dv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :dengue]./(10^9)
dv_3b=dv_1b+dv_2b

1051×16 Matrix{Union{Missing, Float64}}:
  missing   missing   missing     missing    …     missing        missing
 0.0       0.0       0.0         0.00116544       0.000495223    0.000104509
 0.0       0.0       0.0         0.00124772       0.000521991    0.000112145
 0.0       0.0       0.0         0.00133582       0.000550206    0.000120339
 0.0       0.0       0.0         0.00142996       0.000579876    0.000129116
 0.0       0.0       0.0         0.00153045  …    0.000611031    0.000138507
 0.0       0.0       0.0         0.00163753       0.000643672    0.000148538
 0.0       0.0       0.0         0.00175148       0.000677819    0.00015924
 0.0       0.0       0.0         0.00187305       0.000713661    0.000170684
 0.0       0.0       0.0         0.00200318       0.000751443    0.000182962
 0.0       0.0       0.0         0.00214353  …    0.000791656    0.00019623
 0.0       0.0       0.0         0.0022935        0.000837065    0.000210673
 0.0       0.0       0.0         0.00245

In [72]:
marg_dengue=10^9*(dv_3b-dv_3)
pd_dengue=(df_r.*marg_dengue)/10^6
dv_SCC=sum(pd_dengue[60:300,:])
perc_dv_SCC=dv_SCC/SCC

0.0053787048369889215

In [73]:
reg_dv_SCC=sum(pd_dengue[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.0  0.0  0.0  0.0106631  0.0  0.0  …  0.00387653  0.00257895  0.000880082

In [74]:
reg_perc_dv_SCC=reg_dv_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.0  0.0  0.0  -0.0456336  0.0  0.0  …  0.00189049  0.00041044  0.0434838

### Schist 

In [75]:
sv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :schisto]./(10^9)

#sv_2=m1[:vslvmorb, :vmorb]*parameters["d2ds"].*m1[:impactvectorbornediseases, :schisto]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2ds]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
sv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :schisto]./(10^9)

sv_3=sv_1+sv_2
pv_sv_1=df_r.*sv_1
pv_sv_2=df_r.*sv_2
pv_sv_3=df_r.*sv_3;

In [76]:
sv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :schisto]./(10^9)

trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2ds]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
sv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :schisto]./(10^9)
sv_3b=sv_1b+sv_2b

marg_schisto=10^9*(sv_3b-sv_3)
pd_schisto=(df_r.*marg_schisto)/10^6
schisto_SCC=sum(pd_schisto[60:300,:])
perc_schisto_SCC=schisto_SCC/SCC

-0.003973395122961255

In [77]:
reg_sv_SCC=sum(pd_schisto[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -0.000233425  -1.86819e-5  …  -0.010432  -0.0429949  -0.000468502

In [78]:
reg_perc_sv_SCC=reg_sv_SCC./reg_SCC

1×16 Matrix{Float64}:
 -3.99848e-5  -9.10849e-5  -9.97086e-5  0.0502075  …  -0.00684264  -0.0231481

### Malaria 

In [79]:
mv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :malaria]./(10^9)

#mv_2=m1[:vslvmorb, :vmorb]*parameters["d2dm"].*m1[:impactvectorbornediseases, :malaria]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dm]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
mv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :malaria]./(10^9)

mv_3=mv_1+mv_2
pv_mv_1=df_r.*mv_1
pv_mv_2=df_r.*mv_2
pv_mv_3=df_r.*mv_3;

In [80]:
mv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :malaria]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dm]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
mv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :malaria]./(10^9)
mv_3b=mv_1b+mv_2b

marg_malaria=10^9*(mv_3b-mv_3)
pd_malaria=(df_r.*marg_malaria)/10^6
malaria_SCC=sum(pd_malaria[60:300,:])
perc_malaria_SCC=malaria_SCC/SCC

0.1053330938485121

In [81]:
reg_mv_SCC=sum(pd_malaria[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.000530003  4.2418e-5  0.0059029  …  0.402835  2.36917  0.0232419

In [82]:
reg_perc_mv_SCC=reg_mv_SCC./reg_SCC

1×16 Matrix{Float64}:
 9.07874e-5  0.000206812  0.000826826  …  0.196453  0.377054  1.14835

### Cardiovascular - Heat Related

In [83]:
hv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)

#hv_2=m1[:vslvmorb, :vmorb]*parameters["d2dc"].*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
hv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)

hv_3=hv_1+hv_2
pv_hv_1=df_r.*hv_1
pv_hv_2=df_r.*hv_2
pv_hv_3=df_r.*hv_3;

In [84]:
hv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :cardheat]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
hv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :cardheat]./(10^9)
hv_3b=hv_1b+hv_2b

marg_chr=10^9*(hv_3b-hv_3)
pd_chr=(df_r.*marg_chr)/10^6
chr_SCC=sum(pd_chr[60:300,:])

-0.0018090816431335574

In [85]:
perc_chr_SCC=chr_SCC/SCC

-5.941943269384635e-5

In [86]:
reg_chr_SCC=sum(pd_chr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -0.000415613  -1.98709e-5  -0.000821712  …  -3.64012e-5  3.03642e-6

In [87]:
reg_perc_chr_SCC=reg_chr_SCC./reg_SCC

1×16 Matrix{Float64}:
 -7.11929e-5  -9.6882e-5  -0.000115098  …  -5.79326e-6  0.000150026

### Cardiovascular - Cold Related

In [88]:
cv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)

#cv_2=m1[:vslvmorb, :vmorb]*parameters["d2dc"].*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
cv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)

cv_3=cv_1+cv_2
pv_cv_1=df_r.*cv_1
pv_cv_2=df_r.*cv_2
pv_cv_3=df_r.*cv_3;

In [89]:
cv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :cardcold]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
cv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :cardcold]./(10^9)
cv_3b=cv_1b+cv_2b

marg_ccr=10^9*(cv_3b-cv_3)
pd_ccr=(df_r.*marg_ccr)/10^6
ccr_SCC=sum(pd_ccr[60:300,:])

0.0015468110869586514

In [90]:
perc_ccr_SCC=ccr_SCC/SCC

5.080513509187683e-5

In [91]:
reg_ccr_SCC=sum(pd_ccr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.000435607  2.04724e-5  0.000860957  …  5.04631e-5  -3.71415e-6

In [92]:
reg_perc_ccr_SCC=reg_ccr_SCC./reg_SCC

1×16 Matrix{Float64}:
 7.46177e-5  9.98148e-5  0.000120595  …  8.03121e-6  -0.000183512

## Cardiovascular - Respiratory

In [93]:
rv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :resp]./(10^9)

#rv_2=m1[:vslvmorb, :vmorb]*parameters["d2dr"].*m1[:impactcardiovascularrespiratory, :resp]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dr]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
rv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :resp]./(10^9)


rv_3=rv_1+rv_2
pv_rv_1=df_r.*rv_1
pv_rv_2=df_r.*rv_2
pv_rv_3=df_r.*rv_3;

In [94]:
rv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :resp]./(10^9)
trick=ones(1051,16)
trick2=trick2=m1[:impactdeathmorbidity, :d2dr]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
rv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :resp]./(10^9)
rv_3b=rv_1b+rv_2b

marg_resp=10^9*(rv_3b-rv_3)
pd_resp=(df_r.*marg_resp)/10^6
resp_SCC=sum(pd_resp[60:300,:])

-0.00018683788375851946

In [95]:
perc_resp_SCC=resp_SCC/SCC

-6.136705383522833e-6

In [96]:
reg_resp_SCC=sum(pd_resp[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -4.56468e-5  -2.09766e-6  -8.03087e-5  …  -7.32067e-6  4.51213e-7

In [97]:
reg_perc_resp_SCC=reg_resp_SCC./reg_SCC

1×16 Matrix{Float64}:
 -7.81912e-6  -1.02273e-5  -1.12489e-5  …  -1.16509e-6  2.22939e-5

## Diarrhea 

In [98]:
d_1=m1[:vslvmorb, :vsl].*m1[:impactdiarrhoea, :diadead]./(10^9)
d_2=m1[:vslvmorb, :vmorb].*m1[:impactdiarrhoea, :diasick]./(10^9)
d_3=d_1+d_2
pv_d_1=df_r.*d_1
pv_d_2=df_r.*d_2
pv_d_3=df_r.*d_3;

In [99]:
d_1b=m3[:vslvmorb, :vsl].*m3[:impactdiarrhoea, :diadead]./(10^9)
d_2b=m3[:vslvmorb, :vmorb].*m3[:impactdiarrhoea, :diasick]./(10^9)
d_3b=d_1b+d_2b

marg_diar=10^9*(d_3b-d_3)
pd_diar=(df_r.*marg_diar)/10^6
diar_SCC=sum(pd_diar[60:300,:])

8.985932778862734

In [100]:
perc_diar_SCC=diar_SCC/SCC

0.29514368794335466

In [101]:
reg_diar_SCC=sum(pd_diar[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 1.81098  0.0  0.780495  0.325504  …  0.280861  2.86365  0.0226673

In [102]:
reg_perc_diar_SCC=reg_diar_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.310214  0.0  0.109325  -1.39302  …  0.60464  0.13697  0.45575  1.11996

## Hurricane 

In [103]:
hd_1=m1[:vslvmorb, :vsl].*m1[:impacttropicalstorms, :hurrdead]./(10^9)
hd_3=hd_1
pv_hd_1=df_r.*hd_1
pv_hd_3=pv_hd_1;

In [104]:
hd_1b=m3[:vslvmorb, :vsl].*m3[:impacttropicalstorms, :hurrdead]./(10^9)
hd_3b=hd_1b

marg_hurr=10^9*(hd_3b-hd_3)
pd_hurr=(df_r.*marg_hurr)/10^6
hurr_SCC=sum(pd_hurr[60:300,:])

0.10093416984198011

In [105]:
perc_hurr_SCC=hurr_SCC/SCC

0.0033151909612251953

In [106]:
reg_hurr_SCC=sum(pd_hurr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.0132273  1.31749e-5  7.88796e-5  0.0150242  …  0.0  0.000406936  0.0014369

In [107]:
reg_perc_hurr_SCC=reg_hurr_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.00226578  6.4235e-5  1.10488e-5  -0.0642973  …  0.0  6.47638e-5  0.0709955

## Extratropical Storms

In [108]:
es_1=m1[:vslvmorb, :vsl].*m1[:impactextratropicalstorms, :extratropicalstormsdead]./(10^9)
es_3=es_1
pv_es_1=df_r.*es_1
pv_es_3=pv_es_1;

In [109]:
es_1b=m3[:vslvmorb, :vsl].*m3[:impactextratropicalstorms, :extratropicalstormsdead]./(10^9)
es_3b=es_1b

marg_extra=10^9*(es_3b-es_3)
pd_extra=(df_r.*marg_extra)/10^6
extra_SCC=sum(pd_extra[60:300,:])

0.006687173382195212

In [110]:
perc_extra_SCC=extra_SCC/SCC

0.0002196407498818972

In [111]:
reg_extra_SCC=sum(pd_extra[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.0022986  3.98737e-5  0.00102387  0.000740404  …  0.000105997  0.000333973

In [112]:
reg_perc_extra_SCC=reg_extra_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.000393741  0.000194407  0.000143415  …  4.60658e-6  1.68694e-5  0.0165012

#### Alternative Regions

In [113]:
dv_SCC_high=sum(reg_dv_SCC[1:5])
dv_SCC_med=(reg_dv_SCC[6]+sum(reg_dv_SCC[8:10])+sum(reg_dv_SCC[12:13]))
dv_SCC_low=(reg_dv_SCC[7]+reg_dv_SCC[11]+reg_dv_SCC[14]+reg_dv_SCC[15]+reg_dv_SCC[16])

sv_SCC_high=sum(reg_sv_SCC[1:5])
sv_SCC_med=(reg_sv_SCC[6]+sum(reg_sv_SCC[8:10])+sum(reg_sv_SCC[12:13]))
sv_SCC_low=(reg_sv_SCC[7]+reg_sv_SCC[11]+reg_sv_SCC[14]+reg_sv_SCC[15]+reg_sv_SCC[16])

mv_SCC_high=sum(reg_mv_SCC[1:5])
mv_SCC_med=(reg_mv_SCC[6]+sum(reg_mv_SCC[8:10])+sum(reg_mv_SCC[12:13]))
mv_SCC_low=(reg_mv_SCC[7]+reg_mv_SCC[11]+reg_mv_SCC[14]+reg_mv_SCC[15]+reg_mv_SCC[16])

chr_SCC_high=sum(reg_chr_SCC[1:5])
chr_SCC_med=(reg_chr_SCC[6]+sum(reg_chr_SCC[8:10])+sum(reg_chr_SCC[12:13]))
chr_SCC_low=(reg_chr_SCC[7]+reg_chr_SCC[11]+reg_chr_SCC[14]+reg_chr_SCC[15]+reg_chr_SCC[16])

ccr_SCC_high=sum(reg_ccr_SCC[1:5])
ccr_SCC_med=(reg_ccr_SCC[6]+sum(reg_ccr_SCC[8:10])+sum(reg_ccr_SCC[12:13]))
ccr_SCC_low=(reg_ccr_SCC[7]+reg_ccr_SCC[11]+reg_ccr_SCC[14]+reg_ccr_SCC[15]+reg_ccr_SCC[16])

resp_SCC_high=sum(reg_resp_SCC[1:5])
resp_SCC_med=(reg_resp_SCC[6]+sum(reg_resp_SCC[8:10])+sum(reg_resp_SCC[12:13]))
resp_SCC_low=(reg_resp_SCC[7]+reg_resp_SCC[11]+reg_resp_SCC[14]+reg_resp_SCC[15]+reg_resp_SCC[16])

diar_SCC_high=sum(reg_diar_SCC[1:5])
diar_SCC_med=(reg_diar_SCC[6]+sum(reg_diar_SCC[8:10])+sum(reg_diar_SCC[12:13]))
diar_SCC_low=(reg_diar_SCC[7]+reg_diar_SCC[11]+reg_diar_SCC[14]+reg_diar_SCC[15]+reg_diar_SCC[16])

hurr_SCC_high=sum(reg_hurr_SCC[1:5])
hurr_SCC_med=(reg_hurr_SCC[6]+sum(reg_hurr_SCC[8:10])+sum(reg_hurr_SCC[12:13]))
hurr_SCC_low=(reg_hurr_SCC[7]+reg_hurr_SCC[11]+reg_hurr_SCC[14]+reg_hurr_SCC[15]+reg_hurr_SCC[16])

extra_SCC_high=sum(reg_extra_SCC[1:5])
extra_SCC_med=(reg_extra_SCC[6]+sum(reg_extra_SCC[8:10])+sum(reg_extra_SCC[12:13]))
extra_SCC_low=(reg_extra_SCC[7]+reg_extra_SCC[11]+reg_extra_SCC[14]+reg_extra_SCC[15]+reg_extra_SCC[16])


0.0014267033967981081

# Mortality Endpoint

## Dengue Fever

### Regional

In [114]:
dead_d=m1[:impactvectorbornediseases, :dengue]
dead_d_region=dead_d[50:350,:];

In [115]:
Kevin_d_dead=permutedims(sum(dead_d[50:350,:],dims=1));

### Global 

In [116]:
dead_d_sum=sum(dead_d,dims=2)
dead_d_global=dead_d_sum[50:350,:];

## Schisto

### Regional

In [117]:
dead_s=m1[:impactvectorbornediseases, :schisto]
dead_s_region=dead_s[50:350,:];

In [118]:
Kevin_s_dead=permutedims(sum(dead_s[50:350,:],dims=1));

### Global 

In [119]:
dead_s_sum=sum(dead_s,dims=2)
dead_s_global=dead_s_sum[50:350,:];

## Malaria

### Regional

In [120]:
dead_m=m1[:impactvectorbornediseases, :malaria]
dead_m_region=dead_m[50:350,:];

In [121]:
Kevin_m_dead=permutedims(sum(dead_m[50:350,:],dims=1));

### Global 

In [122]:
dead_m_sum=sum(dead_m,dims=2)
dead_m_global=dead_m_sum[50:350,:];

## Cardio - Heat

### Regional

In [123]:
dead_ch=m1[:impactcardiovascularrespiratory, :cardheat]
dead_ch_region=dead_ch[50:350,:];

In [124]:
Kevin_ch_dead=permutedims(sum(dead_ch[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  21764.9457211987
   2321.9442287785932
  34255.072670982176
  14539.817332845623
   1672.765871112701
  11864.118577628858
  35013.71996286274
  20500.275667698683
   7670.530316010307
  23430.619167311277
 110654.32534969572
      6.339410953088908
 124917.59277836658
  14925.539466278024
  37185.297333189155
   3091.7200652289653

### Global 

In [125]:
dead_ch_sum=sum(dead_ch,dims=2)
dead_ch_global=dead_ch_sum[50:350,:];

## Cardio - Cold 

### Regional

In [126]:
dead_cc=m1[:impactcardiovascularrespiratory, :cardcold]
dead_cc_region=dead_ch[50:350,:];

In [127]:
Kevin_cc_dead=permutedims(sum(dead_cc[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  -23029.82193703391
   -2466.5517792513233
  -38052.7755130413
  -15361.178022272654
   -1774.4239715126264
  -13934.59881581233
  -43507.193195382926
  -23587.88625469136
   -8727.543487206942
  -25786.68747573516
 -156149.14980700292
   -2581.6930224682233
 -151149.6310332076
  -18443.22200791672
  -50880.506199083895
   -3787.4777891167923

### Global 

In [128]:
dead_cc_sum=sum(dead_cc,dims=2)
dead_cc_global=dead_cc_sum[50:350,:];

## Respiratory

### Regional

In [129]:
dead_r=m1[:impactcardiovascularrespiratory, :resp]
dead_r_region=dead_ch[50:350,:];

In [130]:
Kevin_r_dead=permutedims(sum(dead_r[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  2604.3009695710693
   187.47745118130547
  2877.2166438179333
  1519.799916389879
   180.73663983574554
   590.6577390376381
  2091.4976629284547
  1703.7930582368592
  1176.409615733008
  3383.8376034780977
 12283.519355423767
  6024.946851031833
  7342.791899208971
  1869.487532668165
  6750.539180689936
   409.3824016098244

### Global 

In [131]:
dead_r_sum=sum(dead_r,dims=2)
dead_r_global=dead_r_sum[50:350,:];

## Diarrhea

### Regional

In [132]:
dead_diah=m1[:impactdiarrhoea, :diadead]
dead_diah_reg=sum(dead_diah[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 2.57589e6  0.0  1.37996e6  4.4346e5  …  1.59252e7  3.14025e8  9.46657e5

In [133]:
Kevin_diar_death=permutedims(dead_diah_reg)

16×1 Matrix{Union{Missing, Float64}}:
      2.5758945132456003e6
      0.0
      1.3799557129444862e6
 443460.3920514853
   3492.1863118039437
 677572.9412479668
      2.1666917515632924e7
      2.0679217502939308e6
      2.492150203981022e6
      6.526891294963131e6
      4.419776721777987e7
      7.063348944914783e6
      3.1622542102847125e7
      1.592517377183607e7
      3.1402502205516857e8
 946657.3394748004

### Global 

In [134]:
dead_diah_sum=sum(dead_diah,dims=2)
dead_diah_global=dead_diah_sum[50:350,:];

## Hurricane

### Regional

In [135]:
dead_hurr=m1[:impacttropicalstorms, :hurrdead];
dead_hurr_reg=sum(dead_hurr[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 20693.2  29.2568  153.896  21456.1  …  84895.3  0.0  44601.5  61078.1

In [136]:
Kevin_hurr_dead=permutedims(sum(dead_hurr[50:350,:],dims=1));

### Global 

In [137]:
dead_hurr_sum=sum(dead_hurr,dims=2)
dead_hurr_global=dead_hurr_sum[50:350,:];

## Extra-tropical

### Regional

In [138]:
dead_extra=m1[:impactextratropicalstorms, :extratropicalstormsdead];
dead_extra_reg=sum(dead_extra[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 3347.24  82.3232  1853.24  998.929  …  7454.11  553.446  11987.4  13542.4

In [139]:
Kevin_extra_dead=permutedims(sum(dead_extra[50:350,:],dims=1));

### Global 

In [140]:
dead_extra_sum=sum(dead_extra,dims=2)
dead_extra_global=dead_extra_sum[50:350,:];

# SCC - Breakdown

## Agriculture 

In [141]:
agr_1=m1[:impactagriculture, :agcost]
pv_agr_1=df_r.*agr_1;
agr_3=m3[:impactagriculture, :agcost]
pv_agr_3=df_r.*agr_3;
marg_agr=1000000000.0*(agr_3-agr_1);
pd_agr=(df_r.*marg_agr)/10^6
agr_SCC=-1*sum(pd_agr[60:300,:])

-6.209574193783242

In [142]:
perc_agr_SCC=agr_SCC/SCC

-0.20395396596134108

## Cooling

In [143]:
cool_1=m1[:impactcooling, :cooling]
pv_cool_1=df_r.*cool_1;
cool_3=m3[:impactcooling, :cooling]
pv_cool_3=df_r.*cool_3;
marg_cool=1000000000.0*(cool_3-cool_1);
pd_cool=(df_r.*marg_cool)/10^6
cool_SCC=-1*sum(pd_cool[60:300,:])

24.150447521517144

In [144]:
perc_cool_SCC=cool_SCC/SCC

0.793223399550639

## Biodiversity

In [145]:
bio_1=m1[:impactbiodiversity, :species]
bio_3=m3[:impactbiodiversity, :species]
marg_bio=1000000000.0*(bio_3-bio_1);
pd_bio=(df_r.*marg_bio)/10^6
bio_SCC=sum(pd_bio[60:300,:])

1.548081341344731

In [146]:
perc_bio_SCC=bio_SCC/SCC

0.05084685669979

## Extra-tropical storm: Non-health 

In [147]:
extra_dam_1=m1[:impactextratropicalstorms, :extratropicalstormsdam]
extra_dam_3=m3[:impactextratropicalstorms, :extratropicalstormsdam]
marg_extra_dam=1000000000.0*(extra_dam_3-extra_dam_1);
pd_extra_dam=(df_r.*marg_extra_dam)/10^6
extra_dam_SCC=sum(pd_extra_dam[60:300,:])

0.017552555003359085

In [148]:
perc_extra_dam_SCC=extra_dam_SCC/SCC

0.0005765150868595339

## Forestry

In [149]:
forest_1=m1[:impactforests, :forests]
forest_3=m3[:impactforests, :forests]
marg_forest=1000000000.0*(forest_3-forest_1);
pd_forest=(df_r.*marg_forest)/10^6
forest_SCC=-1*sum(pd_forest[60:300,:])

-0.12672676345746314

In [150]:
perc_forest_SCC=forest_SCC/SCC

-0.004162350781873368

## Health

In [151]:
health_alt_1=m1[:impactdeathmorbidity, :deadcost]+m1[:impactdeathmorbidity, :morbcost]
health_alt_3=m3[:impactdeathmorbidity, :deadcost]+m3[:impactdeathmorbidity, :morbcost]
marg_health_alt=1000000000.0*(health_alt_3-health_alt_1);
pd_health_alt=(df_r.*marg_health_alt)/10^6
health_alt_SCC=sum(pd_health_alt[60:300,:])## Health

12.342858128849794

In [152]:
perc_health_alt_SCC=health_alt_SCC/SCC

0.4054021722129321

## Heating 

In [153]:
heat_1=m1[:impactheating, :heating]
pv_heat_1=df_r.*heat_1;
heat_3=m3[:impactheating, :heating]
pv_heat_3=df_r.*heat_3;
marg_heat=1000000000.0*(heat_3-heat_1);
pd_heat=(df_r.*marg_heat)/10^6
heat_SCC=-1*sum(pd_heat[60:300,:])

-4.837733447093496

In [154]:
perc_heat_SCC=heat_SCC/SCC

-0.15889574582849247

## Energy Consumption

In [155]:
energy_SCC=heat_SCC+cool_SCC

19.31271407442365

In [156]:
perc_energy_SCC=energy_SCC/SCC

0.6343276537221466

## Sea-level rise

In [157]:
slr_1=m1[:impactsealevelrise, :leavecost]+m1[:impactsealevelrise, :entercost]
slr_1=slr_1+m1[:impactsealevelrise, :drycost]+m1[:impactsealevelrise, :protcost]
slr_1=slr_1+m1[:impactsealevelrise, :wetcost]
pv_slr_1=df_r.*slr_1;
slr_3=m3[:impactsealevelrise, :leavecost]+m3[:impactsealevelrise, :entercost]
slr_3=slr_3+m3[:impactsealevelrise, :drycost]+m3[:impactsealevelrise, :protcost]
slr_3=slr_3+m3[:impactsealevelrise, :wetcost]
pv_slr_3=df_r.*slr_3;
marg_slr=1000000000.0*(slr_3-slr_1);
pd_slr=(df_r.*marg_slr)/10^6
slr_SCC=sum(pd_slr[60:300,:])

0.4734398948977594

In [158]:
perc_slr_SCC=slr_SCC/SCC

0.015550171589122839

## Tropical - Non-health

In [159]:
hurr_dam_1=m1[:impacttropicalstorms, :hurrdam]
hurr_dam_3=m3[:impacttropicalstorms, :hurrdam]
marg_hurr_dam=1000000000.0*(hurr_dam_3-hurr_dam_1);
pd_hurr_dam=(df_r.*marg_hurr_dam)/10^6
hurr_dam_SCC=sum(pd_hurr_dam[60:300,:])

0.19376623695365866

In [160]:
perc_hurr_dam_SCC=hurr_dam_SCC/SCC

0.0063642677038417165

## Storms

In [161]:
storm_SCC=hurr_dam_SCC+extra_dam_SCC

0.21131879195701775

In [162]:
perc_storm_SCC=perc_hurr_dam_SCC+perc_extra_dam_SCC

0.0069407827907012505

## Water

In [163]:
water_1=m1[:impactwaterresources, :water]
pv_water_1=df_r.*water_1;
water_3=m3[:impactwaterresources, :water]
pv_water_3=df_r.*water_3;
marg_water=1000000000.0*(water_3-water_1);
pd_water=(df_r.*marg_water)/10^6
water_SCC=-1*sum(pd_water[60:300,:])

2.8938482565124017

In [164]:
perc_water_SCC=water_SCC/SCC

0.09504867973023196

## Other

In [165]:
eloss_other=m1[:impactaggregation, :eloss_other]
eloss_other=sum(eloss_other)

0.0

In [166]:
sloss_other=m1[:impactaggregation, :sloss_other]
sloss_other=sum(sloss_other)

0.0

## SCC - Check

### SCC-Aggregate

In [167]:
SCC_Check_1=m1[:impactaggregation, :loss]
SCC_Check_3=m3[:impactaggregation, :loss]
marg_SCC_Check=(SCC_Check_3-SCC_Check_1);
pd_SCC_Check=(df_r.*marg_SCC_Check)/10^6
SCC_Check=sum(pd_SCC_Check[60:300,:])

30.445959530692576

### SCC-Aggregate-2

In [168]:
SCC_Check_2=agr_SCC+cool_SCC+bio_SCC+forest_SCC+health_alt_SCC+heat_SCC+slr_SCC+hurr_dam_SCC+water_SCC

30.428406975741293

### SCC-Aggregate-3

In [169]:
SCC_Check_3=perc_agr_SCC+perc_cool_SCC+perc_bio_SCC+perc_forest_SCC+perc_health_alt_SCC+perc_heat_SCC+perc_slr_SCC+perc_hurr_dam_SCC+perc_water_SCC

0.9994234849148509

# Tables

## Tables for Figure 1

In [170]:
Table_Fig1a=zeros(10,3)
Table_Fig1a[1,:].=99
Table_Fig1a[:,1].=99

Table_Fig1a[2,2]=agr_SCC
Table_Fig1a[3,2]=bio_SCC
Table_Fig1a[4,2]=energy_SCC
Table_Fig1a[5,2]=forest_SCC
Table_Fig1a[6,2]=health_alt_SCC
Table_Fig1a[7,2]=slr_SCC
Table_Fig1a[8,2]=storm_SCC
Table_Fig1a[9,2]=water_SCC
Table_Fig1a[10,2]=SCC

Table_Fig1a[2,3]=perc_agr_SCC
Table_Fig1a[3,3]=perc_bio_SCC
Table_Fig1a[4,3]=perc_energy_SCC
Table_Fig1a[5,3]=perc_forest_SCC
Table_Fig1a[6,3]=perc_health_alt_SCC
Table_Fig1a[7,3]=perc_slr_SCC
Table_Fig1a[8,3]=perc_storm_SCC
Table_Fig1a[9,3]=perc_water_SCC
Table_Fig1a[10,3]=1

Table_Fig1a

10×3 Matrix{Float64}:
 99.0  99.0       99.0
 99.0  -6.20957   -0.203954
 99.0   1.54808    0.0508469
 99.0  19.3127     0.634328
 99.0  -0.126727  -0.00416235
 99.0  12.3429     0.405402
 99.0   0.47344    0.0155502
 99.0   0.211319   0.00694078
 99.0   2.89385    0.0950487
 99.0  30.446      1.0

In [171]:
Table_Figure1a_row=(["Impact";"SCC";"% of SCC"])

3-element Vector{String}:
 "Impact"
 "SCC"
 "% of SCC"

In [172]:
Table1_Figure1a_col=["Agriculture";"Ecosystems";"Energy consumption";"Forestry";"Health";"Sea level rise";"Storms - non-health";"Water resources";"Total"]

9-element Vector{String}:
 "Agriculture"
 "Ecosystems"
 "Energy consumption"
 "Forestry"
 "Health"
 "Sea level rise"
 "Storms - non-health"
 "Water resources"
 "Total"

In [173]:
table_Fig1a=Array{String}(undef,10,3)
table_Fig1a[1,:]=["Impact";"SCC";"% of SCC"]
table_Fig1a[:,1]=["Impact";"Agriculture";"Ecosystems";"Energy consumption";"Forestry";"Health";"Sea level rise";"Storms - non-health";"Water resources";"Total"]


table_Fig1a[2:10,2]=[string(agr_SCC);string(bio_SCC);string(energy_SCC);string(forest_SCC);string(health_alt_SCC);string(slr_SCC);string(storm_SCC);string(water_SCC);string(SCC)]
table_Fig1a[2:10,3]=[string(perc_agr_SCC);string(perc_bio_SCC);string(perc_energy_SCC);string(perc_forest_SCC);string(perc_health_alt_SCC);string(perc_slr_SCC);string(perc_storm_SCC);string(perc_water_SCC);string(1)]


table_Fig1a

writedlm("../output/Yelas0_fig1a.csv",table_Fig1a, ",")

In [174]:
Table_Fig1b=zeros(17,3)
Table_Fig1b[1,:].=99
Table_Fig1b[:,1].=99

for j=2:17
    Table_Fig1b[j,2]=pop_reg_2015[j-1]
    Table_Fig1b[j,3]=ypc_reg_2015[j-1]
    
end    

Table_Fig1b

17×3 Matrix{Float64}:
 99.0    99.0        99.0
 99.0   296.645   41660.0
 99.0    33.4312  29280.1
 99.0   394.803   34147.3
 99.0   192.84    45751.9
 99.0    23.554   32235.3
 99.0   126.782    4651.7
 99.0   293.649    2816.38
 99.0   316.058    3464.89
 99.0   154.354    4261.06
 99.0   414.72     5537.34
 99.0  1669.5       644.272
 99.0   629.39     2325.36
 99.0  1467.51     1543.71
 99.0   192.371    1732.68
 99.0   878.003     671.595
 99.0    53.3875   1573.95

In [175]:
Table_Figure1b_row=(["Regions";"2015 Population";"2015 GDP per Capita"])

3-element Vector{String}:
 "Regions"
 "2015 Population"
 "2015 GDP per Capita"

In [176]:
Table_Figure1b_col=["Regsions";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

17-element Vector{String}:
 "Regsions"
 "USA"
 "CAN"
 "WEU"
 "JPK"
 "ANZ"
 "CEE"
 "FSU"
 "MDE"
 "CAM"
 "SAM"
 "SAS"
 "SEA"
 "CHI"
 "NAF"
 "SSA"
 "SIS"

In [177]:
table_Fig1b=Array{String}(undef,17,3)
table_Fig1b[1,:]=["Regions";"2015 Population";"2015 GDP per Capita"]
table_Fig1b[:,1]=["Regions";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

table_Fig1b[2:17,2]=[string(pop_reg_2015[1]);string(pop_reg_2015[2]);string(pop_reg_2015[3]);string(pop_reg_2015[4]);string(pop_reg_2015[5]);string(pop_reg_2015[6]);string(pop_reg_2015[7]);string(pop_reg_2015[8]);string(pop_reg_2015[9]);string(pop_reg_2015[10]);string(pop_reg_2015[11]);string(pop_reg_2015[12]);string(pop_reg_2015[13]);string(pop_reg_2015[14]);string(pop_reg_2015[15]);string(pop_reg_2015[16])]
table_Fig1b[2:17,3]=[string(ypc_reg_2015[1]);string(ypc_reg_2015[2]);string(ypc_reg_2015[3]);string(ypc_reg_2015[4]);string(ypc_reg_2015[5]);string(ypc_reg_2015[6]);string(ypc_reg_2015[7]);string(ypc_reg_2015[8]);string(ypc_reg_2015[9]);string(ypc_reg_2015[10]);string(ypc_reg_2015[11]);string(ypc_reg_2015[12]);string(ypc_reg_2015[13]);string(ypc_reg_2015[14]);string(ypc_reg_2015[15]);string(ypc_reg_2015[16])]

table_Fig1b

writedlm("../output/Yelas0_fig1b.csv",table_Fig1b, ",")

#### Alternative Regions

In [178]:
table_Fig1b_Reg=Array{String}(undef,4,3)
table_Fig1b_Reg[1,:]=["Regions";"2015 Population";"2015 GDP per Capita"]
table_Fig1b_Reg[:,1]=["Regions";"HIGH";"MEDIUM";"LOW"]

table_Fig1b_Reg[2:4,2]=[string(pop_high_2015);string(pop_med_2015);string(pop_low_2015)]
table_Fig1b_Reg[2:4,3]=[string(ypc_high_2015);string(ypc_med_2015);string(ypc_low_2015)]

table_Fig1b_Reg


writedlm("../output/Yelas0_fig1b_Reg.csv",table_Fig1b_Reg, ",")

## Table - Figure 2

In [179]:
#table_Fig2=Array{String}(undef,11,17)
#table_Fig2[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
#table_Fig2[:,1]=["Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]

#for j=2:17
#    table_Fig2[2,j]=string(reg_perc_dv_SCC[j-1])
#    table_Fig2[3,j]=string(reg_perc_sv_SCC[j-1])
#    table_Fig2[4,j]=string(reg_perc_mv_SCC[j-1])
#    table_Fig2[5,j]=string(reg_perc_chr_SCC[j-1])
#    table_Fig2[6,j]=string(reg_perc_ccr_SCC[j-1])
#    table_Fig2[7,j]=string(reg_perc_resp_SCC[j-1])
#    table_Fig2[8,j]=string(reg_perc_diar_SCC[j-1])
#    table_Fig2[9,j]=string(reg_perc_hurr_SCC[j-1])
#    table_Fig2[10,j]=string(reg_perc_extra_SCC[j-1])
#    table_Fig2[11,j]=string(Reg_Perc_Health_SCC[j-1])
#end
#        
#table_Fig2
#
#writedlm("Yelas0_Fig2.csv",table_Fig2, ",")

In [180]:
table_Fig2=Array{String}(undef,11,17)
table_Fig2[1,:]=["SCC by Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig2[:,1]=["SCC by Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]

for j=2:17
    table_Fig2[2,j]=string(reg_dv_SCC[j-1])
    table_Fig2[3,j]=string(reg_sv_SCC[j-1])
    table_Fig2[4,j]=string(reg_mv_SCC[j-1])
    table_Fig2[5,j]=string(reg_chr_SCC[j-1])
    table_Fig2[6,j]=string(reg_ccr_SCC[j-1])
    table_Fig2[7,j]=string(reg_resp_SCC[j-1])
    table_Fig2[8,j]=string(reg_diar_SCC[j-1])
    table_Fig2[9,j]=string(reg_hurr_SCC[j-1])
    table_Fig2[10,j]=string(reg_extra_SCC[j-1])
    table_Fig2[11,j]=string(reg_health_SCC[j-1])
end
        
table_Fig2

writedlm("../output/Yelas0_Fig2.csv",table_Fig2, ",")

#### Alternative Regions

In [181]:
table_Fig2_Reg=Array{String}(undef,11,4)
table_Fig2_Reg[1,:]=["SCC by Endpoint/Region";"High";"Medium";"Low"]
table_Fig2_Reg[:,1]=["SCC by Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]


table_Fig2_Reg[2,2:4]=[string(dv_SCC_high);string(dv_SCC_med);string(dv_SCC_low)]
table_Fig2_Reg[3,2:4]=[string(sv_SCC_high);string(sv_SCC_med);string(sv_SCC_low)]
table_Fig2_Reg[4,2:4]=[string(mv_SCC_high);string(mv_SCC_med);string(mv_SCC_low)]
table_Fig2_Reg[5,2:4]=[string(chr_SCC_high);string(chr_SCC_med);string(chr_SCC_low)]
table_Fig2_Reg[6,2:4]=[string(ccr_SCC_high);string(ccr_SCC_med);string(ccr_SCC_low)]
table_Fig2_Reg[7,2:4]=[string(resp_SCC_high);string(resp_SCC_med);string(resp_SCC_low)]
table_Fig2_Reg[8,2:4]=[string(diar_SCC_high);string(diar_SCC_med);string(diar_SCC_low)]
table_Fig2_Reg[9,2:4]=[string(hurr_SCC_high);string(hurr_SCC_med);string(hurr_SCC_low)]
table_Fig2_Reg[10,2:4]=[string(extra_SCC_high);string(extra_SCC_med);string(extra_SCC_low)]
table_Fig2_Reg[11,2:4]=[string(health_SCC_high);string(health_SCC_med);string(health_SCC_low)]
        
table_Fig2_Reg

writedlm("../output/Yelas0_Fig2_Reg.csv",table_Fig2_Reg, ",")

## Table - Appendix Figure 1

In [182]:
table_app1=Array{String}(undef,11,301)
table_app1[:,1]=["Mortalities by Endpoint/Year";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total"]

for j=2:301
    table_app1[1,j]=string(j-2+2000)
    table_app1[2,j]=string(dead_d_global[j-1])
    table_app1[3,j]=string(dead_s_global[j-1])
    table_app1[4,j]=string(dead_m_global[j-1])
    table_app1[5,j]=string(dead_ch_global[j-1])
    table_app1[6,j]=string(dead_cc_global[j-1])
    table_app1[7,j]=string(dead_r_global[j-1])
    table_app1[8,j]=string(dead_diah_global[j-1])
    table_app1[9,j]=string(dead_hurr_global[j-1])
    table_app1[10,j]=string(dead_extra_global[j-1])
    table_app1[11,j]=string(deaths_glob[j-1])
end

table_app1
table_app1b=permutedims(table_app1)

301×11 Matrix{String}:
 "Mortalities by Endpoint/Year"  …  "Total"
 "2000"                             "137078.12637649532"
 "2001"                             "142817.93886540097"
 "2002"                             "148731.7800309848"
 "2003"                             "154848.27082948014"
 "2004"                          …  "161173.97616192544"
 "2005"                             "167716.95464664974"
 "2006"                             "174505.3805910067"
 "2007"                             "181554.08785669177"
 "2008"                             "188961.95116032736"
 "2009"                          …  "196703.7778995916"
 "2010"                             "204786.4698324864"
 "2011"                             "213201.73580438847"
 ⋮                               ⋱  ⋮
 "2288"                             "3.5319949837566437e6"
 "2289"                          …  "3.5278116262662797e6"
 "2290"                             "3.523610991174175e6"
 "2291"                             "3.

In [183]:
writedlm("../output/Yelas0_app1.csv",table_app1b, ",")

## Table_Fig3 

In [184]:
table_Fig3=Array{String}(undef,3,17)
table_Fig3[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig3[:,1]=["Endpoint/Region";"Health";"SCC"]

for j=2:17
    table_Fig3[2,j]=string(reg_health_SCC[j-1])
    table_Fig3[3,j]=string(SCC_reg[j-1])
end
        
table_Fig3
table_Fig3=permutedims(table_Fig3)

writedlm("../output/Yelas0_table_fig3.csv",table_Fig3, ",")

#### Alternative Regions

In [185]:
table_Fig3_Reg=Array{String}(undef,3,4)
table_Fig3_Reg[1,:]=["Endpoint/Region";"High";"Medium";"Low"]
table_Fig3_Reg[:,1]=["Endpoint/Region";"Health";"SCC"]


table_Fig3_Reg[2,2:4]=[string(health_SCC_high);string(health_SCC_med);string(health_SCC_low)]
table_Fig3_Reg[3,2:4]=[string(SCC_high);string(SCC_med);string(SCC_low)]
        
table_Fig3_Reg
table_Fig3_Reg=permutedims(table_Fig3_Reg)

writedlm("../output/Yelas0_fig3_Reg.csv",table_Fig3_Reg, ",")

## Table_Fig4

In [186]:
table_Fig4a=Array{String}(undef,6,17)
table_Fig4a[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig4a[:,1]=["Endpoint/Region";"Avg VSL";"Weighted VSL";"Deaths";"Avg Per Capita GDP";"Weighted Per Capita GDP"]

for j=2:17
    table_Fig4a[2,j]=string(vsl_reg_avg[j-1])
    table_Fig4a[3,j]=string(vsl_reg_pop_avg[j-1])
    table_Fig4a[4,j]=string(deaths_reg_sum[j-1])
    table_Fig4a[5,j]=string(ypc_reg_avg[j-1])
    table_Fig4a[6,j]=string(ypc_reg_pop_avg[j-1])
end
        
table_Fig4a
table_Fig4a=permutedims(table_Fig4a)

writedlm("../output/Yelas0_fig4a.csv",table_Fig4a, ",")

In [187]:
table_Fig4b=Array{String}(undef,17,301)
table_Fig4b[:,1]=["VSL/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4b[1,j]=string(j-2+2000)
    table_Fig4b[2,j]=string(vsl_reg[j-1,1])
    table_Fig4b[3,j]=string(vsl_reg[j-1,2])
    table_Fig4b[4,j]=string(vsl_reg[j-1,3])
    table_Fig4b[5,j]=string(vsl_reg[j-1,4])
    table_Fig4b[6,j]=string(vsl_reg[j-1,5])
    table_Fig4b[7,j]=string(vsl_reg[j-1,6])
    table_Fig4b[8,j]=string(vsl_reg[j-1,7])
    table_Fig4b[9,j]=string(vsl_reg[j-1,8])
    table_Fig4b[10,j]=string(vsl_reg[j-1,9])
    table_Fig4b[11,j]=string(vsl_reg[j-1,10])
    table_Fig4b[12,j]=string(vsl_reg[j-1,11])
    table_Fig4b[13,j]=string(vsl_reg[j-1,12])
    table_Fig4b[14,j]=string(vsl_reg[j-1,13])
    table_Fig4b[15,j]=string(vsl_reg[j-1,14])
    table_Fig4b[16,j]=string(vsl_reg[j-1,15])
    table_Fig4b[17,j]=string(vsl_reg[j-1,16])
    
end

table_Fig4b
table_Fig4b=permutedims(table_Fig4b)
writedlm("../output/Yelas0_fig4b.csv",table_Fig4b, ",")

In [188]:
table_Fig4c=Array{String}(undef,17,301)
table_Fig4c[:,1]=["Mortalities/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4c[1,j]=string(j-2+2000)
    table_Fig4c[2,j]=string(deaths_reg[j-1,1])
    table_Fig4c[3,j]=string(deaths_reg[j-1,2])
    table_Fig4c[4,j]=string(deaths_reg[j-1,3])
    table_Fig4c[5,j]=string(deaths_reg[j-1,4])
    table_Fig4c[6,j]=string(deaths_reg[j-1,5])
    table_Fig4c[7,j]=string(deaths_reg[j-1,6])
    table_Fig4c[8,j]=string(deaths_reg[j-1,7])
    table_Fig4c[9,j]=string(deaths_reg[j-1,8])
    table_Fig4c[10,j]=string(deaths_reg[j-1,9])
    table_Fig4c[11,j]=string(deaths_reg[j-1,10])
    table_Fig4c[12,j]=string(deaths_reg[j-1,11])
    table_Fig4c[13,j]=string(deaths_reg[j-1,12])
    table_Fig4c[14,j]=string(deaths_reg[j-1,13])
    table_Fig4c[15,j]=string(deaths_reg[j-1,14])
    table_Fig4c[16,j]=string(deaths_reg[j-1,15])
    table_Fig4c[17,j]=string(deaths_reg[j-1,16])
    
end

table_Fig4c
table_Fig4c=permutedims(table_Fig4c)
writedlm("../output/Yelas0_fig4c.csv",table_Fig4c, ",")

In [189]:
table_Fig4d=Array{String}(undef,17,301)
table_Fig4d[:,1]=["YPC/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4d[1,j]=string(j-2+2000)
    table_Fig4d[2,j]=string(ypc_reg[j-1,1])
    table_Fig4d[3,j]=string(ypc_reg[j-1,2])
    table_Fig4d[4,j]=string(ypc_reg[j-1,3])
    table_Fig4d[5,j]=string(ypc_reg[j-1,4])
    table_Fig4d[6,j]=string(ypc_reg[j-1,5])
    table_Fig4d[7,j]=string(ypc_reg[j-1,6])
    table_Fig4d[8,j]=string(ypc_reg[j-1,7])
    table_Fig4d[9,j]=string(ypc_reg[j-1,8])
    table_Fig4d[10,j]=string(ypc_reg[j-1,9])
    table_Fig4d[11,j]=string(ypc_reg[j-1,10])
    table_Fig4d[12,j]=string(ypc_reg[j-1,11])
    table_Fig4d[13,j]=string(ypc_reg[j-1,12])
    table_Fig4d[14,j]=string(ypc_reg[j-1,13])
    table_Fig4d[15,j]=string(ypc_reg[j-1,14])
    table_Fig4d[16,j]=string(ypc_reg[j-1,15])
    table_Fig4d[17,j]=string(ypc_reg[j-1,16])
    
end

table_Fig4d
table_Fig4d=permutedims(table_Fig4d)
writedlm("../output/Yelas0_fig4d.csv",table_Fig4d, ",")

#### Alternative Regions

In [190]:
table_Fig4a_Reg=Array{String}(undef,5,4)
table_Fig4a_Reg[1,:]=["Endpoint/Region";"High";"Medium";"Low"]
table_Fig4a_Reg[:,1]=["Endpoint/Region";"Avg VSL";"Weighted VSL";"Deaths";"Avg Per Capita GDP"]


table_Fig4a_Reg[2,2:4]=[string(vsl_high_avg);string(vsl_med_avg);string(vsl_low_avg)]
table_Fig4a_Reg[3,2:4]=[string(vsl_high_pop_avg);string(vsl_med_pop_avg);string(vsl_low_pop_avg)]
table_Fig4a_Reg[4,2:4]=[string(dead_high_sum);string(dead_med_sum);string(dead_low_sum)]
table_Fig4a_Reg[5,2:4]=[string(ypc_high_avg);string(ypc_med_avg);string(ypc_low_avg)]

        
table_Fig4a_Reg
table_Fig4a_Reg=permutedims(table_Fig4a_Reg)

writedlm("../output/Yelas0_fig4a_Reg.csv",table_Fig4a_Reg, ",")

In [191]:
table_Fig4b_Reg=Array{String}(undef,4,301)
table_Fig4b_Reg[:,1]=["VSL/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4b_Reg[1,j]=string(j-2+2000)
    table_Fig4b_Reg[2,j]=string(vsl_high[j-1])
    table_Fig4b_Reg[3,j]=string(vsl_med[j-1])
    table_Fig4b_Reg[4,j]=string(vsl_low[j-1])    
end

table_Fig4b_Reg
table_Fig4b_Reg=permutedims(table_Fig4b_Reg)
writedlm("../output/Yelas0_fig4b_Reg.csv",table_Fig4b_Reg, ",")

In [192]:
table_Fig4c_Reg=Array{String}(undef,4,301)
table_Fig4c_Reg[:,1]=["Mortalities/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4c_Reg[1,j]=string(j-2+2000)
    table_Fig4c_Reg[2,j]=string(dead_high[j-1])
    table_Fig4c_Reg[3,j]=string(dead_med[j-1])
    table_Fig4c_Reg[4,j]=string(dead_low[j-1])
end

table_Fig4c_Reg
table_Fig4c_Reg=permutedims(table_Fig4c_Reg)
writedlm("../output/Yelas0_fig4c_Reg.csv",table_Fig4c_Reg, ",")

In [193]:
table_Fig4d_Reg=Array{String}(undef,4,301)
table_Fig4d_Reg[:,1]=["YPC/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4d_Reg[1,j]=string(j-2+2000)
    table_Fig4d_Reg[2,j]=string(ypc_high[j-1])
    table_Fig4d_Reg[3,j]=string(ypc_med[j-1])
    table_Fig4d_Reg[4,j]=string(ypc_low[j-1])
end

table_Fig4d_Reg
table_Fig4d_Reg=permutedims(table_Fig4d_Reg)
writedlm("../output/Yelas0_fig4d_Reg.csv",table_Fig4d_Reg, ",")