# Poverty Trap Model Run - Tables

In [1]:
using Mimi
using MimiFUND
using DelimitedFiles

In [2]:
parameters = MimiFUND.load_default_parameters();

In [3]:
m0 = MimiFUND.get_model();

In [4]:
run(m0);

In [5]:
parameters[:scenypcgrowth]

1051×16 Matrix{Float64}:
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.9

In [6]:
parameters[:scenypcgrowth][2,4]

3.234

In [7]:
trick=zeros(1051,16)
for j=1:60
trick[j,:]=trick[j,:]+parameters[:scenypcgrowth][j,:]
end

for j=61:1050
    for k=1:5
trick[j,k]=trick[j,k]+parameters[:scenypcgrowth][j,k]
end
end

trick

1051×16 Matrix{Float64}:
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.9

# New Model Run

In [8]:
parameters[:scenypcgrowth]=trick

1051×16 Matrix{Float64}:
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909  …  4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.909     4.471  4.242  3.629  0.77  2.93
 1.868  2.785  2.731  3.234  1.143  2.9

In [9]:
m1 = MimiFUND.get_model(params=parameters);

In [10]:
run(m1);

# Discount Factor

In [11]:
baseyear = 60
prtp = 0.01
eta = 1.0
ypc = m1[:socioeconomic, :ypc]
df_r = [t>=baseyear ? (ypc[baseyear,r]/ypc[t,r])^eta *
(1.0+prtp)^-(t-baseyear) : 0.0 for t in 1:1051, r in 1:16];
#df_r_1=df_r;
df_r_1=df_r[50:350,:];

# Key Variables

### Population - global population is in people while regional population is in millions

In [12]:
pop=m1[:population, :globalpopulation];

In [13]:
pop_glob=pop[50:350,:];

In [14]:
pop_glob_2015=pop[65,:]

1-element Vector{Union{Missing, Float64}}:
 7.137316657934137e9

In [15]:
pop_sum=sum(pop[50:350,:])

2.9022614298303384e12

In [16]:
pop_reg=m1[:population,:population][50:350,:];

In [17]:
pop_reg_2015=m1[:population,:population][65,:]

16-element Vector{Union{Missing, Float64}}:
  296.6694621000862
   33.43463012269337
  394.8249750810085
  192.84357628713477
   23.55806856639281
  126.78370154652103
  293.46431238326204
  316.06359304305676
  154.35828053721616
  414.7332934301782
 1669.702955884264
  629.4246747851677
 1467.6802149743398
  192.4180808890199
  877.9642688779521
   53.39256942584386

In [18]:
pop_reg_sum=sum(m1[:population,:population][50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 91434.1  10560.0  1.21474e5  66752.7  …  1.08234e5  4.58802e5  20090.3

#### Alternative Regions 

In [19]:
pop_r=m1[:population,:population];
pop_high=sum(pop_r[50:350,1:5],dims=2)
pop_med=(pop_r[50:350,6]+sum(pop_r[50:350,8:10],dims=2)+sum(pop_r[50:350,12:13],dims=2))
pop_low=(pop_r[50:350,7]+pop_r[50:350,11]+pop_r[50:350,14]+pop_r[50:350,15]+pop_r[50:350,16])
pop_high_avg=sum(pop_high)/301
pop_med_avg=sum(pop_med)/301
pop_low_avg=sum(pop_low)/301
pop_high_2015=sum(pop_r[65,1:5],dims=2)
pop_med_2015=(pop_r[65,6]+sum(pop_r[65,8:10])+sum(pop_r[65,12:13]))
pop_low_2015=(pop_r[65,7]+pop_r[65,11]+pop_r[65,14]+pop_r[65,15]+pop_r[65,16])

3086.9421874603418

### Income - billions USD1995

In [20]:
globalincome= m1[:socioeconomic, :globalincome];

In [21]:
GDP_glob=globalincome[50:350,:];

In [22]:
GDP_glob_2015=globalincome[65,:]

1-element Vector{Union{Missing, Float64}}:
 46542.34575135166

In [23]:
income= m1[:socioeconomic, :income];

In [24]:
GDP_reg=income[50:350,:];

In [25]:
GDP_reg_2015=income[65,:]

16-element Vector{Union{Missing, Float64}}:
 12358.241088599054
   978.8687250284875
 13481.450709992328
  8822.807438977017
   759.2674481443755
   511.21544281513184
   716.8951075872199
   992.5114742038568
   596.0861057696892
  2081.2723874161366
   974.82763413769
  1326.4232323080669
  2029.8316335038203
   302.0829528432541
   534.4074438528788
    76.15692617266512

In [26]:
GDP_reg_sum=sum(df_r_1.*GDP_reg,dims=1)

1×16 Matrix{Float64}:
 1.09238e6  87499.3  1.18527e6  8.65258e5  …  48318.0  82201.7  8639.32

In [27]:
GDP_glob_sum=sum(df_r_1.*GDP_reg)

4.5105729780956805e6

#### Alternative Regions 

In [28]:
gdp_high=sum(income[50:350,1:5],dims=2)
gdp_med=(income[50:350,6]+sum(income[50:350,8:10],dims=2)+sum(income[50:350,12:13],dims=2))
gdp_low=(income[50:350,7]+income[50:350,11]+income[50:350,14]+income[50:350,15]+income[50:350,16])
gdp_high2=sum(df_r[50:350,1:5].*income[50:350,1:5],dims=2)
gdp_med2=(df_r[50:350,6].*income[50:350,6]+sum(df_r[50:350,8:10].*income[50:350,8:10],dims=2)+sum(df_r[50:350,12:13].*income[50:350,12:13],dims=2))
gdp_low2=(df_r[50:350,7].*income[50:350,7]+df_r[50:350,11].*income[50:350,11]+df_r[50:350,14].*income[50:350,14]+df_r[50:350,15].*income[50:350,15]+df_r[50:350,16].*income[50:350,16])
gdp_high_avg=sum(gdp_high2)/291
gdp_med_avg=sum(gdp_med2)/291
gdp_low_avg=sum(gdp_low2)/291
gdp_high_2015=sum(income[65,1:5],dims=2)
gdp_med_2015=(income[65,6]+sum(income[65,8:10])+sum(income[65,12:13]))
gdp_low_2015=(income[65,7]+income[65,11]+income[65,14]+income[65,15]+income[65,16])

2604.370064593708

### Income per capita 

In [29]:
ypc = m1[:socioeconomic, :ypc];

In [30]:
globalypc=m1[:socioeconomic, :globalypc]
ypc_glob=globalypc[50:350,:]

301×1 Matrix{Union{Missing, Float64}}:
  5337.418689168101
  5422.438217416453
  5569.008529772254
  5637.9743204687875
  5710.2491846359035
  5785.2183492772965
  5862.892168242639
  5943.333324301487
  6026.592385893459
  6112.786392293587
  6202.023668554732
  6294.385496073551
  6351.146655018377
     ⋮
 35692.07585956564
 35898.54583092908
 36106.28398567793
 36315.29825732581
 36525.59662720946
 36737.18712642476
 36950.077837305005
 37164.27688937642
 37379.79246296454
 37596.632790072756
 37814.80615340018
 38034.32088849619

In [31]:
ypc_glob_2015=globalypc[65,:]

1-element Vector{Union{Missing, Float64}}:
 6520.986525042751

In [32]:
ypc_reg=ypc[50:350,:];

In [33]:
ypc_reg_2015=ypc[65,:]

16-element Vector{Union{Missing, Float64}}:
 41656.59991128377
 29277.091489763232
 34145.38481823816
 45751.108794208856
 32229.613646151036
  4032.1858139435253
  2442.8698050717685
  3140.227144316014
  3861.7047539990663
  5018.339304767019
   583.8329690333617
  2107.3581723830507
  1383.0203696922554
  1569.9301824836568
   608.6892858815967
  1426.3581429329474

In [34]:
ypc_reg_sum=sum(df_r_1.*ypc_reg,dims=1)

1×16 Matrix{Float64}:
 3.63316e6  2.55153e6  2.96889e6  3.97382e6  …  1.46459e5  56718.3  1.32729e5

In [35]:
ypc_reg_avg=ypc_reg_sum/291

1×16 Matrix{Float64}:
 12485.1  8768.14  10202.4  13655.7  …  438.298  503.297  194.908  456.114

In [36]:
ypc_reg_pop_avg=sum(df_r_1.*ypc_reg.*pop_reg,dims=1)./sum(pop_reg,dims=1)

1×16 Matrix{Float64}:
 11947.1  8285.89  9757.33  12962.1  …  417.413  446.423  179.166  430.025

In [37]:
ypc_glob_avg=(sum(GDP_reg_sum.*pop_reg)./sum(pop_reg))/291

785.3163818181747

In [38]:
ypc_glob_pop_avg=sum(df_r_1.*ypc_reg.*pop_reg)./sum(pop_reg)

1554.158054727469

#### Alternative Regions 

In [39]:
ypc_high=1000*gdp_high./pop_high
ypc_med=1000*gdp_med./pop_med
ypc_low=1000*gdp_low./pop_low;
ypc_high_avg=1000*gdp_high_avg/pop_high_avg*(301/291)
ypc_med_avg=1000*gdp_med_avg/pop_med_avg*(301/291)
ypc_low_avg=1000*gdp_low_avg/pop_low_avg*(301/291)
ypc_high_2015=1000*gdp_high_2015./pop_high_2015
ypc_med_2015=1000*gdp_med_2015./pop_med_2015
ypc_low_2015=1000*gdp_low_2015./pop_low_2015

843.673093449265

## Deaths

In [40]:
deaths = m1[:impactdeathmorbidity, :dead];

In [41]:
deaths_reg=deaths[50:350,:];

In [42]:
deaths_reg_2015=deaths[65,:]

16-element Vector{Union{Missing, Float64}}:
    602.9939391919431
      5.2801448868344405
    339.5223193052669
    148.37616738794915
      1.2941787845232104
    178.34608699330397
  16857.664063220996
    585.1865442813273
    704.8954230684861
   1609.1894287822945
   7985.018956788081
    991.2921722026083
   2334.6225339902953
   5211.948969614168
 146972.17312618264
    362.0436053304614

In [43]:
deaths_reg_sum=sum(deaths_reg,dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 1.23671e5  47.9254  70073.2  29379.6  …  2.50618e7  3.75273e8  5.94722e5

In [44]:
deaths_reg_avg=sum(deaths_reg,dims=1)/301

1×16 Matrix{Float64}:
 410.866  0.159221  232.801  97.6066  1.69611  …  83261.8  1.24675e6  1975.82

In [45]:
deaths_glob=sum(deaths,dims=2)[50:350,:];

In [46]:
deaths_glob_2015=sum(deaths,dims=2)[65,:]

1-element Vector{Union{Missing, Float64}}:
 184889.84766001118

In [47]:
deaths_glob_sum=sum(deaths_glob)

4.6941805116226685e8

In [48]:
deaths_glob_avg=deaths_glob_sum/301

1.5595284091769662e6

#### Alternative Regions 

In [49]:
dead_high=sum(deaths[50:350,1:5],dims=2)
dead_med=(deaths[50:350,6]+sum(deaths[50:350,8:10],dims=2)+sum(deaths[50:350,12:13],dims=2))
dead_low=(deaths[50:350,7]+deaths[50:350,11]+deaths[50:350,14]+deaths[50:350,15]+deaths[50:350,16])
dead_high_sum=sum(dead_high)
dead_med_sum=sum(dead_med)
dead_low_sum=sum(dead_low)
dead_high_avg=sum(dead_high)/301
dead_med_avg=sum(dead_med)/301
dead_low_avg=sum(dead_low)/301

1.5168387799921338e6

### VSL

In [50]:
vsl=m1[:vslvmorb, :vsl];

In [51]:
vsl_reg=vsl[50:350,:];

In [52]:
vsl_reg_2015=vsl[65,:]

16-element Vector{Union{Missing, Float64}}:
      8.331319982256753e6
      5.855418297952646e6
      6.829076963647633e6
      9.150221758841772e6
      6.445922729230207e6
 806437.1627887051
 488573.96101435367
 628045.4288632029
 772340.9507998133
      1.0036678609534038e6
 116766.59380667233
 421471.6344766101
 276604.07393845107
 313986.0364967314
 121737.85717631935
 285271.6285865895

In [53]:
vsl_reg_avg=sum(df_r_1.*vsl_reg,dims=1)/291

1×16 Matrix{Float64}:
 2.49702e6  1.75363e6  2.04047e6  2.73115e6  …  1.00659e5  38981.7  91222.7

In [54]:
vsl_reg_pop_avg=vsl_reg_pop_avg=sum(df_r_1[10:300,:].*vsl_reg[10:300,:].*deaths_reg[10:300,:],dims=1)./sum(deaths_reg[10:300,:],dims=1)

1×16 Matrix{Float64}:
 3.0318e6  -1.61796e7  2.46198e6  …  56775.1  53608.7  26142.8  62161.3

In [55]:
#Incorrect
vsl_glob=sum(df_r.*vsl.*deaths,dims=2)./sum(deaths,dims=2)
vsl_glob=vsl_glob[50:350,:]

301×1 Matrix{Union{Missing, Float64}}:
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
 228575.34846442926
 225647.78688795803
 220507.80373317158
      ⋮
  11514.750946962726
  11413.440591207946
  11313.026994125408
  11213.501693682349
  11114.85631018214
  11017.082546024181
  10920.17221143153
  10824.117189310282
  10728.909444689034
  10634.5410323509
  10541.004081874855
  10448.290816125722

In [56]:
vsl_glob_2015=vsl_glob[65,:]

1-element Vector{Union{Missing, Float64}}:
 97460.03252517224

In [57]:
vsl_glob_avg=sum(vsl_glob)/291

57590.95920632492

#### Alternative Regions 

In [58]:
mort_val=vsl.*deaths
vsl_high=sum(mort_val[50:350,1:5],dims=2)./sum(deaths[50:350,1:5],dims=2)
vsl_med=(mort_val[50:350,6]+sum(mort_val[50:350,8:10],dims=2)+sum(mort_val[50:350,12:13],dims=2))./(deaths[50:350,6]+sum(deaths[50:350,8:10],dims=2)+sum(deaths[50:350,12:13],dims=2))
vsl_low=(mort_val[50:350,7]+mort_val[50:350,11]+mort_val[50:350,14]+mort_val[50:350,15]+mort_val[50:350,16])./(deaths[50:350,7]+deaths[50:350,11]+deaths[50:350,14]+deaths[50:350,15]+deaths[50:350,16]);
vsl_high_avg=sum(vsl_high)/291
vsl_med_avg=sum(vsl_med)/291
vsl_low_avg=sum(vsl_low)/291
vsl_high_pop_avg=sum(mort_val[50:350,1:5])./sum(deaths[50:350,1:5])
vsl_med_pop_avg=(sum(mort_val[50:350,6])+sum(mort_val[50:350,8:10])+sum(mort_val[50:350,12:13]))./(sum(deaths[50:350,6])+sum(deaths[50:350,8:10])+sum(deaths[50:350,12:13]))
vsl_low_pop_avg=(sum(mort_val[50:350,7])+sum(mort_val[50:350,11])+sum(mort_val[50:350,14])+sum(mort_val[50:350,15])+sum(mort_val[50:350,16]))./(sum(deaths[50:350,7])+sum(deaths[50:350,11])+sum(deaths[50:350,14])+sum(deaths[50:350,15])+sum(deaths[50:350,16]))


150996.0998521173

# SCC

In [59]:
m3 = MimiFUND.get_model(params=parameters);

In [60]:
add_comp!(m3, Mimi.adder, :co2marg, before=:climateco2cycle);

In [61]:
connect_param!(m3, :co2marg, :input, :emissions, :mco2)

In [62]:
connect_param!(m3, :climateco2cycle, :mco2, :co2marg, :output)

In [63]:
marginalemissions = zeros(1051)
marginalemissions[60] = 1
set_param!(m3, :co2marg, :add, marginalemissions);

In [64]:
run(m3)

In [65]:
md = (m3[:impactaggregation, :loss]-
    m1[:impactaggregation, :loss])/10^6;

In [66]:
pd=df_r.*md
SCC=sum(pd[60:300,:])

35.724475961381174

# Regional SCC

In [67]:
reg_SCC=sum(pd[60:300,:],dims=1);
SCC_reg=reg_SCC

1×16 Matrix{Union{Missing, Float64}}:
 4.68316  0.203971  6.7662  -1.11955  …  3.06773  7.14401  -0.00988374

#### Alternative Regions 

In [68]:
SCC_high=sum(SCC_reg[1:5])
SCC_med=(SCC_reg[6]+sum(SCC_reg[8:10])+sum(SCC_reg[12:13]))
SCC_low=(SCC_reg[7]+SCC_reg[11]+SCC_reg[14]+SCC_reg[15]+SCC_reg[16])

16.98740999513364

## Health SCC

In [69]:
marg_health=10^9*((m3[:impactdeathmorbidity, :deadcost]+m3[:impactdeathmorbidity, :morbcost])-(m1[:impactdeathmorbidity, :deadcost]+m1[:impactdeathmorbidity, :morbcost]));

In [70]:
pd_health=(df_r.*marg_health)/10^6
health_SCC=sum(pd_health[60:300,:])

10.005313623267723

In [71]:
Perc_Health_SCC=health_SCC/SCC

0.2800688702637277

## Health Regional SCC

In [72]:
reg_health_SCC=sum(pd_health[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.407704  3.32843e-5  0.193969  0.082077  …  0.865947  5.31865  0.0211097

In [73]:
Reg_Perc_Health_SCC=reg_health_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.0870575  0.000163181  0.0286674  …  0.282277  0.744491  -2.1358

In [74]:
Perc_health_SCC_reg=reg_health_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.0870575  0.000163181  0.0286674  …  0.282277  0.744491  -2.1358

#### Alternative Regions 

In [75]:
health_SCC_high=sum(reg_health_SCC[1:5])
health_SCC_med=(reg_health_SCC[6]+sum(reg_health_SCC[8:10])+sum(reg_health_SCC[12:13]))
health_SCC_low=(reg_health_SCC[7]+reg_health_SCC[11]+reg_health_SCC[14]+reg_health_SCC[15]+reg_health_SCC[16])

8.415984837740972

# Health Endpoint SCC

### Dengue Fever 

In [76]:
dv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :dengue]./(10^9)

trick=ones(1051,16)
trick2=parameters[:d2dd]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick

#dv_2=m1[:vslvmorb, :vmorb]*parameters["d2dd"].*m1[:impactvectorbornediseases, :dengue]./1000000000.0
dv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :dengue]./(10^9)
dv_3=dv_1+dv_2
pv_dv_1=df_r.*dv_1
pv_dv_2=df_r.*dv_2
pv_dv_3=df_r.*dv_3;

In [77]:
dv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :dengue]./(10^9)

trick=ones(1051,16)
trick2=parameters[:d2dd]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick;

dv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :dengue]./(10^9)
dv_3b=dv_1b+dv_2b

1051×16 Matrix{Union{Missing, Float64}}:
  missing   missing   missing  …   missing     missing      missing
 0.0       0.0       0.0          0.00714076  0.000529003  0.00135431
 0.0       0.0       0.0          0.00705276  0.000546377  0.00134619
 0.0       0.0       0.0          0.00696585  0.000564321  0.00133812
 0.0       0.0       0.0          0.00687919  0.000582785  0.00132995
 0.0       0.0       0.0       …  0.00679232  0.00060174   0.00132157
 0.0       0.0       0.0          0.0067046   0.00062113   0.00131286
 0.0       0.0       0.0          0.00661568  0.00064092   0.00130376
 0.0       0.0       0.0          0.00652688  0.000661233  0.0012945
 0.0       0.0       0.0          0.00643965  0.00068223   0.00128539
 0.0       0.0       0.0       …  0.00635705  0.000704277  0.00127704
 0.0       0.0       0.0          0.00628238  0.00072969   0.00127002
 0.0       0.0       0.0          0.0062078   0.000755924  0.00126288
 ⋮                             ⋱                    

In [78]:
marg_dengue=10^9*(dv_3b-dv_3)
pd_dengue=(df_r.*marg_dengue)/10^6
dv_SCC=sum(pd_dengue[60:300,:])
perc_dv_SCC=dv_SCC/SCC

0.0013075520145644113

In [79]:
reg_dv_SCC=sum(pd_dengue[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.0  0.0  0.0  0.000801006  0.0  0.0  …  0.00503374  0.00253846  0.000276496

In [80]:
reg_perc_dv_SCC=reg_dv_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.0  0.0  0.0  -0.000715468  -0.0  …  0.00164087  0.000355327  -0.0279748

### Schist 

In [81]:
sv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :schisto]./(10^9)

#sv_2=m1[:vslvmorb, :vmorb]*parameters["d2ds"].*m1[:impactvectorbornediseases, :schisto]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2ds]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
sv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :schisto]./(10^9)

sv_3=sv_1+sv_2
pv_sv_1=df_r.*sv_1
pv_sv_2=df_r.*sv_2
pv_sv_3=df_r.*sv_3;

In [82]:
sv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :schisto]./(10^9)

trick=ones(1051,16)
trick2=parameters[:d2ds]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
sv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :schisto]./(10^9)
sv_3b=sv_1b+sv_2b

marg_schisto=10^9*(sv_3b-sv_3)
pd_schisto=(df_r.*marg_schisto)/10^6
schisto_SCC=sum(pd_schisto[60:300,:])
perc_schisto_SCC=schisto_SCC/SCC

-0.0021829187002273998

In [83]:
reg_sv_SCC=sum(pd_schisto[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -1.46154e-5  -1.47804e-6  -5.49512e-5  …  -0.0423199  -0.000147189

In [84]:
reg_perc_sv_SCC=reg_sv_SCC./reg_SCC

1×16 Matrix{Float64}:
 -3.12083e-6  -7.24632e-6  …  -0.00441571  -0.00592383  0.0148921

### Malaria 

In [85]:
mv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :malaria]./(10^9)

#mv_2=m1[:vslvmorb, :vmorb]*parameters["d2dm"].*m1[:impactvectorbornediseases, :malaria]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dm]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
mv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :malaria]./(10^9)

mv_3=mv_1+mv_2
pv_mv_1=df_r.*mv_1
pv_mv_2=df_r.*mv_2
pv_mv_3=df_r.*mv_3;

In [86]:
mv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :malaria]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dm]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
mv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :malaria]./(10^9)
mv_3b=mv_1b+mv_2b

marg_malaria=10^9*(mv_3b-mv_3)
pd_malaria=(df_r.*marg_malaria)/10^6
malaria_SCC=sum(pd_malaria[60:300,:])
perc_malaria_SCC=malaria_SCC/SCC

0.08318774201036569

In [87]:
reg_mv_SCC=sum(pd_malaria[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 3.31848e-5  3.35596e-6  0.000455679  …  0.523089  2.33198  0.00730192

In [88]:
reg_perc_mv_SCC=reg_mv_SCC./reg_SCC

1×16 Matrix{Float64}:
 7.08599e-6  1.64531e-5  6.73464e-5  …  0.170514  0.326424  -0.738781

### Cardiovascular - Heat Related

In [89]:
hv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)

#hv_2=m1[:vslvmorb, :vmorb]*parameters["d2dc"].*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
hv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)

hv_3=hv_1+hv_2
pv_hv_1=df_r.*hv_1
pv_hv_2=df_r.*hv_2
pv_hv_3=df_r.*hv_3;

In [90]:
hv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :cardheat]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
hv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :cardheat]./(10^9)
hv_3b=hv_1b+hv_2b

marg_chr=10^9*(hv_3b-hv_3)
pd_chr=(df_r.*marg_chr)/10^6
chr_SCC=sum(pd_chr[60:300,:])

-0.001789550648747232

In [91]:
perc_chr_SCC=chr_SCC/SCC

-5.009312524784883e-5

In [92]:
reg_chr_SCC=sum(pd_chr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -0.00052082  -3.02326e-5  -0.000919724  …  -2.27135e-5  2.10952e-6

In [93]:
reg_perc_chr_SCC=reg_chr_SCC./reg_SCC

1×16 Matrix{Float64}:
 -0.000111211  -0.00014822  -0.000135929  …  -3.17937e-6  -0.000213434

### Cardiovascular - Cold Related

In [94]:
cv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)

#cv_2=m1[:vslvmorb, :vmorb]*parameters["d2dc"].*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
cv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)

cv_3=cv_1+cv_2
pv_cv_1=df_r.*cv_1
pv_cv_2=df_r.*cv_2
pv_cv_3=df_r.*cv_3;

In [95]:
cv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :cardcold]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
cv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :cardcold]./(10^9)
cv_3b=cv_1b+cv_2b

marg_ccr=10^9*(cv_3b-cv_3)
pd_ccr=(df_r.*marg_ccr)/10^6
ccr_SCC=sum(pd_ccr[60:300,:])

0.002218256042803651

In [96]:
perc_ccr_SCC=ccr_SCC/SCC

6.209345226509766e-5

In [97]:
reg_ccr_SCC=sum(pd_ccr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.000535499  2.97589e-5  0.000949858  …  5.38671e-5  -3.21067e-6

In [98]:
reg_perc_ccr_SCC=reg_ccr_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.000114346  0.000145898  …  4.20068e-5  7.54018e-6  0.000324844

## Cardiovascular - Respiratory

In [99]:
rv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :resp]./(10^9)

#rv_2=m1[:vslvmorb, :vmorb]*parameters["d2dr"].*m1[:impactcardiovascularrespiratory, :resp]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dr]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
rv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :resp]./(10^9)


rv_3=rv_1+rv_2
pv_rv_1=df_r.*rv_1
pv_rv_2=df_r.*rv_2
pv_rv_3=df_r.*rv_3;

In [100]:
rv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :resp]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dr]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
rv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :resp]./(10^9)
rv_3b=rv_1b+rv_2b

marg_resp=10^9*(rv_3b-rv_3)
pd_resp=(df_r.*marg_resp)/10^6
resp_SCC=sum(pd_resp[60:300,:])

-0.0001870637261446131

In [101]:
perc_resp_SCC=resp_SCC/SCC

-5.236290277479017e-6

In [102]:
reg_resp_SCC=sum(pd_resp[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -5.37188e-5  -2.03785e-6  -8.67926e-5  …  -6.04808e-6  4.02155e-7

In [103]:
reg_perc_resp_SCC=reg_resp_SCC./reg_SCC

1×16 Matrix{Float64}:
 -1.14706e-5  -9.99089e-6  -1.28274e-5  …  -8.46595e-7  -4.06885e-5

## Diarrhea 

In [104]:
d_1=m1[:vslvmorb, :vsl].*m1[:impactdiarrhoea, :diadead]./(10^9)
d_2=m1[:vslvmorb, :vmorb].*m1[:impactdiarrhoea, :diasick]./(10^9)
d_3=d_1+d_2
pv_d_1=df_r.*d_1
pv_d_2=df_r.*d_2
pv_d_3=df_r.*d_3;

In [105]:
d_1b=m3[:vslvmorb, :vsl].*m3[:impactdiarrhoea, :diadead]./(10^9)
d_2b=m3[:vslvmorb, :vmorb].*m3[:impactdiarrhoea, :diasick]./(10^9)
d_3b=d_1b+d_2b

marg_diar=10^9*(d_3b-d_3)
pd_diar=(df_r.*marg_diar)/10^6
diar_SCC=sum(pd_diar[60:300,:])

6.980167967038792

In [106]:
perc_diar_SCC=diar_SCC/SCC

0.19538895334908438

In [107]:
reg_diar_SCC=sum(pd_diar[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.398425  0.0  0.192917  0.0692558  …  0.351324  3.02587  0.0121339

In [108]:
reg_perc_diar_SCC=reg_diar_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.085076  0.0  0.0285118  -0.0618601  …  0.114523  0.423553  -1.22766

## Hurricane 

In [109]:
hd_1=m1[:vslvmorb, :vsl].*m1[:impacttropicalstorms, :hurrdead]./(10^9)
hd_3=hd_1
pv_hd_1=df_r.*hd_1
pv_hd_3=pv_hd_1;

In [110]:
hd_1b=m3[:vslvmorb, :vsl].*m3[:impacttropicalstorms, :hurrdead]./(10^9)
hd_3b=hd_1b

marg_hurr=10^9*(hd_3b-hd_3)
pd_hurr=(df_r.*marg_hurr)/10^6
hurr_SCC=sum(pd_hurr[60:300,:])

0.07975524886025173

In [111]:
perc_hurr_SCC=hurr_SCC/SCC

0.002232509972895576

In [112]:
reg_hurr_SCC=sum(pd_hurr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.00789262  8.28624e-6  4.95158e-5  …  0.0  0.000452589  0.00127288

In [113]:
reg_perc_hurr_SCC=reg_hurr_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.00168532  4.06246e-5  7.31811e-6  …  0.0  6.33523e-5  -0.128786

## Extratropical Storms

In [114]:
es_1=m1[:vslvmorb, :vsl].*m1[:impactextratropicalstorms, :extratropicalstormsdead]./(10^9)
es_3=es_1
pv_es_1=df_r.*es_1
pv_es_3=pv_es_1;

In [115]:
es_1b=m3[:vslvmorb, :vsl].*m3[:impactextratropicalstorms, :extratropicalstormsdead]./(10^9)
es_3b=es_1b

marg_extra=10^9*(es_3b-es_3)
pd_extra=(df_r.*marg_extra)/10^6
extra_SCC=sum(pd_extra[60:300,:])

0.0045822921548098125

In [116]:
perc_extra_SCC=extra_SCC/SCC

0.00012826758214069692

In [117]:
reg_extra_SCC=sum(pd_extra[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.00140746  2.56316e-5  0.000658839  …  0.000108823  0.000272428

In [118]:
reg_perc_extra_SCC=reg_extra_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.000300537  0.000125663  9.73721e-5  …  3.36714e-6  1.52327e-5  -0.0275632

#### Alternative Regions

In [119]:
dv_SCC_high=sum(reg_dv_SCC[1:5])
dv_SCC_med=(reg_dv_SCC[6]+sum(reg_dv_SCC[8:10])+sum(reg_dv_SCC[12:13]))
dv_SCC_low=(reg_dv_SCC[7]+reg_dv_SCC[11]+reg_dv_SCC[14]+reg_dv_SCC[15]+reg_dv_SCC[16])

sv_SCC_high=sum(reg_sv_SCC[1:5])
sv_SCC_med=(reg_sv_SCC[6]+sum(reg_sv_SCC[8:10])+sum(reg_sv_SCC[12:13]))
sv_SCC_low=(reg_sv_SCC[7]+reg_sv_SCC[11]+reg_sv_SCC[14]+reg_sv_SCC[15]+reg_sv_SCC[16])

mv_SCC_high=sum(reg_mv_SCC[1:5])
mv_SCC_med=(reg_mv_SCC[6]+sum(reg_mv_SCC[8:10])+sum(reg_mv_SCC[12:13]))
mv_SCC_low=(reg_mv_SCC[7]+reg_mv_SCC[11]+reg_mv_SCC[14]+reg_mv_SCC[15]+reg_mv_SCC[16])

chr_SCC_high=sum(reg_chr_SCC[1:5])
chr_SCC_med=(reg_chr_SCC[6]+sum(reg_chr_SCC[8:10])+sum(reg_chr_SCC[12:13]))
chr_SCC_low=(reg_chr_SCC[7]+reg_chr_SCC[11]+reg_chr_SCC[14]+reg_chr_SCC[15]+reg_chr_SCC[16])

ccr_SCC_high=sum(reg_ccr_SCC[1:5])
ccr_SCC_med=(reg_ccr_SCC[6]+sum(reg_ccr_SCC[8:10])+sum(reg_ccr_SCC[12:13]))
ccr_SCC_low=(reg_ccr_SCC[7]+reg_ccr_SCC[11]+reg_ccr_SCC[14]+reg_ccr_SCC[15]+reg_ccr_SCC[16])

resp_SCC_high=sum(reg_resp_SCC[1:5])
resp_SCC_med=(reg_resp_SCC[6]+sum(reg_resp_SCC[8:10])+sum(reg_resp_SCC[12:13]))
resp_SCC_low=(reg_resp_SCC[7]+reg_resp_SCC[11]+reg_resp_SCC[14]+reg_resp_SCC[15]+reg_resp_SCC[16])

diar_SCC_high=sum(reg_diar_SCC[1:5])
diar_SCC_med=(reg_diar_SCC[6]+sum(reg_diar_SCC[8:10])+sum(reg_diar_SCC[12:13]))
diar_SCC_low=(reg_diar_SCC[7]+reg_diar_SCC[11]+reg_diar_SCC[14]+reg_diar_SCC[15]+reg_diar_SCC[16])

hurr_SCC_high=sum(reg_hurr_SCC[1:5])
hurr_SCC_med=(reg_hurr_SCC[6]+sum(reg_hurr_SCC[8:10])+sum(reg_hurr_SCC[12:13]))
hurr_SCC_low=(reg_hurr_SCC[7]+reg_hurr_SCC[11]+reg_hurr_SCC[14]+reg_hurr_SCC[15]+reg_hurr_SCC[16])

extra_SCC_high=sum(reg_extra_SCC[1:5])
extra_SCC_med=(reg_extra_SCC[6]+sum(reg_extra_SCC[8:10])+sum(reg_extra_SCC[12:13]))
extra_SCC_low=(reg_extra_SCC[7]+reg_extra_SCC[11]+reg_extra_SCC[14]+reg_extra_SCC[15]+reg_extra_SCC[16])

0.0011756213149214563

# Mortality Endpoint

## Dengue Fever

### Regional

In [120]:
dead_d=m1[:impactvectorbornediseases, :dengue]
dead_d_region=dead_d[50:350,:];

In [121]:
Kevin_d_dead=permutedims(sum(dead_d[50:350,:],dims=1));

### Global 

In [122]:
dead_d_sum=sum(dead_d,dims=2)
dead_d_global=dead_d_sum[50:350,:];

## Schisto

### Regional

In [123]:
dead_s=m1[:impactvectorbornediseases, :schisto]
dead_s_region=dead_s[50:350,:];

In [124]:
Kevin_s_dead=permutedims(sum(dead_s[50:350,:],dims=1));

### Global 

In [125]:
dead_s_sum=sum(dead_s,dims=2)
dead_s_global=dead_s_sum[50:350,:];

## Malaria

### Regional

In [126]:
dead_m=m1[:impactvectorbornediseases, :malaria]
dead_m_region=dead_m[50:350,:];

In [127]:
Kevin_m_dead=permutedims(sum(dead_m[50:350,:],dims=1));

### Global 

In [128]:
dead_m_sum=sum(dead_m,dims=2)
dead_m_global=dead_m_sum[50:350,:];

## Cardio - Heat

### Regional

In [129]:
dead_ch=m1[:impactcardiovascularrespiratory, :cardheat]
dead_ch_region=dead_ch[50:350,:];

In [130]:
Kevin_ch_dead=permutedims(sum(dead_ch[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
 22334.0345629733
  2420.3895628220826
 35180.18838445287
 14626.816471688999
  1758.433081121272
  6219.273730420876
 20894.424061174
  9884.005819029653
  3629.1969042242413
 10543.67386762377
 35340.40576942649
  1452.0359030524355
 34441.84273124489
  6539.44063750345
 13591.615039868444
  1034.6260554792768

### Global 

In [131]:
dead_ch_sum=sum(dead_ch,dims=2)
dead_ch_global=dead_ch_sum[50:350,:];

## Cardio - Cold 

### Regional

In [132]:
dead_cc=m1[:impactcardiovascularrespiratory, :cardcold]
dead_cc_region=dead_ch[50:350,:];

In [133]:
Kevin_cc_dead=permutedims(sum(dead_cc[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  -23653.63178585394
   -2576.8389217522968
  -39065.881342807545
  -15452.580670576608
   -1870.133610857323
   -9589.739630999487
  -35953.01467018173
  -15733.077615202805
   -5582.551983418151
  -14983.993292179306
 -110420.22490138229
  -31095.625326655358
  -67925.92870718252
  -13001.849042875469
  -34646.12713933369
   -2027.0733349751124

### Global 

In [134]:
dead_cc_sum=sum(dead_cc,dims=2)
dead_cc_global=dead_cc_sum[50:350,:];

## Respiratory

### Regional

In [135]:
dead_r=m1[:impactcardiovascularrespiratory, :resp]
dead_r_region=dead_ch[50:350,:];

In [136]:
Kevin_r_dead=permutedims(sum(dead_r[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
 2675.0172123594384
  168.48101834554922
 2937.8958883004934
 1527.9139274841775
  190.69098622096303
  261.1275411828764
 1242.2339752482537
  935.389919589962
  754.6609308178872
 2170.3996200774172
 4748.307194526771
 3412.5938393643496
 1919.702608848296
 1012.2391208068387
 3430.6662341223873
  206.14794911797395

### Global 

In [137]:
dead_r_sum=sum(dead_r,dims=2)
dead_r_global=dead_r_sum[50:350,:];

## Diarrhea

### Regional

In [138]:
dead_diah=m1[:impactdiarrhoea, :diadead]
dead_diah_reg=sum(dead_diah[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 115468.0  0.0  70259.3  21495.8  141.138  …  1.1238e7  2.17577e8  3.41407e5

In [139]:
Kevin_diar_death=permutedims(dead_diah_reg)

16×1 Matrix{Union{Missing, Float64}}:
 115467.95321805614
      0.0
  70259.3443104782
  21495.79017858301
    141.13819412915691
 306571.2298730135
      3.527817006267024e7
 962378.9049742644
      1.2368313643665297e6
      3.074560083833563e6
      1.3865850790010726e7
      1.9825242077212536e6
      3.5571199695247733e6
      1.1237973824285563e7
      2.1757665209630427e8
 341407.1556618294

### Global 

In [140]:
dead_diah_sum=sum(dead_diah,dims=2)
dead_diah_global=dead_diah_sum[50:350,:];

## Hurricane

### Regional

In [141]:
dead_hurr=m1[:impacttropicalstorms, :hurrdead];
dead_hurr_reg=sum(dead_hurr[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 5842.29  8.88812  45.267  6038.39  …  34648.8  0.0  33237.1  35710.9

In [142]:
Kevin_hurr_dead=permutedims(sum(dead_hurr[50:350,:],dims=1));

### Global 

In [143]:
dead_hurr_sum=sum(dead_hurr,dims=2)
dead_hurr_global=dead_hurr_sum[50:350,:];

## Extra-tropical

### Regional

In [144]:
dead_extra=m1[:impactextratropicalstorms, :extratropicalstormsdead];
dead_extra_reg=sum(dead_extra[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 999.787  26.2521  576.957  298.142  …  2886.45  372.904  8387.04  7537.54

In [145]:
Kevin_extra_dead=permutedims(sum(dead_extra[50:350,:],dims=1));

### Global 

In [146]:
dead_extra_sum=sum(dead_extra,dims=2)
dead_extra_global=dead_extra_sum[50:350,:];

# SCC - Breakdown

## Agriculture 

In [147]:
agr_1=m1[:impactagriculture, :agcost]
pv_agr_1=df_r.*agr_1;
agr_3=m3[:impactagriculture, :agcost]
pv_agr_3=df_r.*agr_3;
marg_agr=1000000000.0*(agr_3-agr_1);
pd_agr=(df_r.*marg_agr)/10^6
agr_SCC=-1*sum(pd_agr[60:300,:])

-5.684341463636025

In [148]:
perc_agr_SCC=agr_SCC/SCC

-0.15911616085792007

## Cooling

In [149]:
cool_1=m1[:impactcooling, :cooling]
pv_cool_1=df_r.*cool_1;
cool_3=m3[:impactcooling, :cooling]
pv_cool_3=df_r.*cool_3;
marg_cool=1000000000.0*(cool_3-cool_1);
pd_cool=(df_r.*marg_cool)/10^6
cool_SCC=-1*sum(pd_cool[60:300,:])

30.764357987285948

In [150]:
perc_cool_SCC=cool_SCC/SCC

0.8611563125668461

## Biodiversity

In [151]:
bio_1=m1[:impactbiodiversity, :species]
bio_3=m3[:impactbiodiversity, :species]
marg_bio=1000000000.0*(bio_3-bio_1);
pd_bio=(df_r.*marg_bio)/10^6
bio_SCC=sum(pd_bio[60:300,:])

1.8044597822156396

In [152]:
perc_bio_SCC=bio_SCC/SCC

0.05051046190758108

## Extra-tropical storm: Non-health 

In [153]:
extra_dam_1=m1[:impactextratropicalstorms, :extratropicalstormsdam]
extra_dam_3=m3[:impactextratropicalstorms, :extratropicalstormsdam]
marg_extra_dam=1000000000.0*(extra_dam_3-extra_dam_1);
pd_extra_dam=(df_r.*marg_extra_dam)/10^6
extra_dam_SCC=sum(pd_extra_dam[60:300,:])

0.024229623548065946

In [154]:
perc_extra_dam_SCC=extra_dam_SCC/SCC

0.0006782359403748461

## Forestry

In [155]:
forest_1=m1[:impactforests, :forests]
forest_3=m3[:impactforests, :forests]
marg_forest=1000000000.0*(forest_3-forest_1);
pd_forest=(df_r.*marg_forest)/10^6
forest_SCC=-1*sum(pd_forest[60:300,:])

-0.1612012823683333

In [156]:
perc_forest_SCC=forest_SCC/SCC

-0.004512348411845003

## Health

In [157]:
health_alt_1=m1[:impactdeathmorbidity, :deadcost]+m1[:impactdeathmorbidity, :morbcost]
health_alt_3=m3[:impactdeathmorbidity, :deadcost]+m3[:impactdeathmorbidity, :morbcost]
marg_health_alt=1000000000.0*(health_alt_3-health_alt_1);
pd_health_alt=(df_r.*marg_health_alt)/10^6
health_alt_SCC=sum(pd_health_alt[60:300,:])## Health

10.005313623267723

In [158]:
perc_health_alt_SCC=health_alt_SCC/SCC

0.2800688702637277

## Heating 

In [159]:
heat_1=m1[:impactheating, :heating]
pv_heat_1=df_r.*heat_1;
heat_3=m3[:impactheating, :heating]
pv_heat_3=df_r.*heat_3;
marg_heat=1000000000.0*(heat_3-heat_1);
pd_heat=(df_r.*marg_heat)/10^6
heat_SCC=-1*sum(pd_heat[60:300,:])

-5.913436394440914

In [160]:
perc_heat_SCC=heat_SCC/SCC

-0.16552898916791525

## Energy Consumption

In [161]:
energy_SCC=heat_SCC+cool_SCC

24.850921592845033

In [162]:
perc_energy_SCC=energy_SCC/SCC

0.6956273233989309

## Sea-level rise

In [163]:
slr_1=m1[:impactsealevelrise, :leavecost]+m1[:impactsealevelrise, :entercost]
slr_1=slr_1+m1[:impactsealevelrise, :drycost]+m1[:impactsealevelrise, :protcost]
slr_1=slr_1+m1[:impactsealevelrise, :wetcost]
pv_slr_1=df_r.*slr_1;
slr_3=m3[:impactsealevelrise, :leavecost]+m3[:impactsealevelrise, :entercost]
slr_3=slr_3+m3[:impactsealevelrise, :drycost]+m3[:impactsealevelrise, :protcost]
slr_3=slr_3+m3[:impactsealevelrise, :wetcost]
pv_slr_3=df_r.*slr_3;
marg_slr=1000000000.0*(slr_3-slr_1);
pd_slr=(df_r.*marg_slr)/10^6
slr_SCC=sum(pd_slr[60:300,:])

0.93813314151531

In [164]:
perc_slr_SCC=slr_SCC/SCC

0.026260235210432463

## Tropical - Non-health

In [165]:
hurr_dam_1=m1[:impacttropicalstorms, :hurrdam]
hurr_dam_3=m3[:impacttropicalstorms, :hurrdam]
marg_hurr_dam=1000000000.0*(hurr_dam_3-hurr_dam_1);
pd_hurr_dam=(df_r.*marg_hurr_dam)/10^6
hurr_dam_SCC=sum(pd_hurr_dam[60:300,:])

0.2704239895936219

In [166]:
perc_hurr_dam_SCC=hurr_dam_SCC/SCC

0.007569711866059429

## Storms

In [167]:
storm_SCC=hurr_dam_SCC+extra_dam_SCC

0.29465361314168786

In [168]:
perc_storm_SCC=perc_hurr_dam_SCC+perc_extra_dam_SCC

0.008247947806434276

## Water

In [169]:
water_1=m1[:impactwaterresources, :water]
pv_water_1=df_r.*water_1;
water_3=m3[:impactwaterresources, :water]
pv_water_3=df_r.*water_3;
marg_water=1000000000.0*(water_3-water_1);
pd_water=(df_r.*marg_water)/10^6
water_SCC=-1*sum(pd_water[60:300,:])

3.6765369543703366

In [170]:
perc_water_SCC=water_SCC/SCC

0.10291367068182447

## Other

In [171]:
eloss_other=parameters[:eloss_other]
eloss_other=sum(eloss_other)

0.0

In [172]:
sloss_other=parameters[:sloss_other]
sloss_other=sum(sloss_other)

0.0

## SCC - Check

### SCC-Aggregate

In [173]:
SCC_Check_1=m1[:impactaggregation, :loss]
SCC_Check_3=m3[:impactaggregation, :loss]
marg_SCC_Check=(SCC_Check_3-SCC_Check_1);
pd_SCC_Check=(df_r.*marg_SCC_Check)/10^6
SCC_Check=sum(pd_SCC_Check[60:300,:])

35.724475961381174

### SCC-Aggregate-2

In [174]:
SCC_Check_2=agr_SCC+cool_SCC+bio_SCC+forest_SCC+health_alt_SCC+heat_SCC+slr_SCC+hurr_dam_SCC+water_SCC

35.70024633780331

### SCC-Aggregate-3

In [175]:
SCC_Check_3=perc_agr_SCC+perc_cool_SCC+perc_bio_SCC+perc_forest_SCC+perc_health_alt_SCC+perc_heat_SCC+perc_slr_SCC+perc_hurr_dam_SCC+perc_water_SCC

0.999321764058791

# Tables

## Tables for Figure 1

In [176]:
Table_Fig1a=zeros(10,3)
Table_Fig1a[1,:].=99
Table_Fig1a[:,1].=99

Table_Fig1a[2,2]=agr_SCC
Table_Fig1a[3,2]=bio_SCC
Table_Fig1a[4,2]=energy_SCC
Table_Fig1a[5,2]=forest_SCC
Table_Fig1a[6,2]=health_alt_SCC
Table_Fig1a[7,2]=slr_SCC
Table_Fig1a[8,2]=storm_SCC
Table_Fig1a[9,2]=water_SCC
Table_Fig1a[10,2]=SCC

Table_Fig1a[2,3]=perc_agr_SCC
Table_Fig1a[3,3]=perc_bio_SCC
Table_Fig1a[4,3]=perc_energy_SCC
Table_Fig1a[5,3]=perc_forest_SCC
Table_Fig1a[6,3]=perc_health_alt_SCC
Table_Fig1a[7,3]=perc_slr_SCC
Table_Fig1a[8,3]=perc_storm_SCC
Table_Fig1a[9,3]=perc_water_SCC
Table_Fig1a[10,3]=1

Table_Fig1a

10×3 Matrix{Float64}:
 99.0  99.0       99.0
 99.0  -5.68434   -0.159116
 99.0   1.80446    0.0505105
 99.0  24.8509     0.695627
 99.0  -0.161201  -0.00451235
 99.0  10.0053     0.280069
 99.0   0.938133   0.0262602
 99.0   0.294654   0.00824795
 99.0   3.67654    0.102914
 99.0  35.7245     1.0

In [177]:
Table_Figure1a_row=(["Impact";"SCC";"% of SCC"])

3-element Vector{String}:
 "Impact"
 "SCC"
 "% of SCC"

In [178]:
Table1_Figure1a_col=["Agriculture";"Ecosystems";"Energy consumption";"Forestry";"Health";"Sea level rise";"Storms - non-health";"Water resources";"Total"]

9-element Vector{String}:
 "Agriculture"
 "Ecosystems"
 "Energy consumption"
 "Forestry"
 "Health"
 "Sea level rise"
 "Storms - non-health"
 "Water resources"
 "Total"

In [179]:
table_Fig1a=Array{String}(undef,10,3)
table_Fig1a[1,:]=["Impact";"SCC";"% of SCC"]
table_Fig1a[:,1]=["Impact";"Agriculture";"Ecosystems";"Energy consumption";"Forestry";"Health";"Sea level rise";"Storms - non-health";"Water resources";"Total"]


table_Fig1a[2:10,2]=[string(agr_SCC);string(bio_SCC);string(energy_SCC);string(forest_SCC);string(health_alt_SCC);string(slr_SCC);string(storm_SCC);string(water_SCC);string(SCC)]
table_Fig1a[2:10,3]=[string(perc_agr_SCC);string(perc_bio_SCC);string(perc_energy_SCC);string(perc_forest_SCC);string(perc_health_alt_SCC);string(perc_slr_SCC);string(perc_storm_SCC);string(perc_water_SCC);string(1)]


table_Fig1a

writedlm("../output/poverty_fig1a.csv",table_Fig1a, ",")

In [180]:
Table_Fig1b=zeros(17,3)
Table_Fig1b[1,:].=99
Table_Fig1b[:,1].=99

for j=2:17
    Table_Fig1b[j,2]=pop_reg_2015[j-1]
    Table_Fig1b[j,3]=ypc_reg_2015[j-1]
    
end    

Table_Fig1b

17×3 Matrix{Float64}:
 99.0    99.0        99.0
 99.0   296.669   41656.6
 99.0    33.4346  29277.1
 99.0   394.825   34145.4
 99.0   192.844   45751.1
 99.0    23.5581  32229.6
 99.0   126.784    4032.19
 99.0   293.464    2442.87
 99.0   316.064    3140.23
 99.0   154.358    3861.7
 99.0   414.733    5018.34
 99.0  1669.7       583.833
 99.0   629.425    2107.36
 99.0  1467.68     1383.02
 99.0   192.418    1569.93
 99.0   877.964     608.689
 99.0    53.3926   1426.36

In [181]:
Table_Figure1b_row=(["Regions";"2015 Population";"2015 GDP per Capita"])

3-element Vector{String}:
 "Regions"
 "2015 Population"
 "2015 GDP per Capita"

In [182]:
Table_Figure1b_col=["Regsions";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

17-element Vector{String}:
 "Regsions"
 "USA"
 "CAN"
 "WEU"
 "JPK"
 "ANZ"
 "CEE"
 "FSU"
 "MDE"
 "CAM"
 "SAM"
 "SAS"
 "SEA"
 "CHI"
 "NAF"
 "SSA"
 "SIS"

In [183]:
table_Fig1b=Array{String}(undef,17,3)
table_Fig1b[1,:]=["Regions";"2015 Population";"2015 GDP per Capita"]
table_Fig1b[:,1]=["Regions";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

table_Fig1b[2:17,2]=[string(pop_reg_2015[1]);string(pop_reg_2015[2]);string(pop_reg_2015[3]);string(pop_reg_2015[4]);string(pop_reg_2015[5]);string(pop_reg_2015[6]);string(pop_reg_2015[7]);string(pop_reg_2015[8]);string(pop_reg_2015[9]);string(pop_reg_2015[10]);string(pop_reg_2015[11]);string(pop_reg_2015[12]);string(pop_reg_2015[13]);string(pop_reg_2015[14]);string(pop_reg_2015[15]);string(pop_reg_2015[16])]
table_Fig1b[2:17,3]=[string(ypc_reg_2015[1]);string(ypc_reg_2015[2]);string(ypc_reg_2015[3]);string(ypc_reg_2015[4]);string(ypc_reg_2015[5]);string(ypc_reg_2015[6]);string(ypc_reg_2015[7]);string(ypc_reg_2015[8]);string(ypc_reg_2015[9]);string(ypc_reg_2015[10]);string(ypc_reg_2015[11]);string(ypc_reg_2015[12]);string(ypc_reg_2015[13]);string(ypc_reg_2015[14]);string(ypc_reg_2015[15]);string(ypc_reg_2015[16])]

table_Fig1b

writedlm("../output/poverty_fig1b.csv",table_Fig1b, ",")

#### Alternative Regions

In [184]:
table_Fig1b_Reg=Array{String}(undef,4,3)
table_Fig1b_Reg[1,:]=["Regions";"2015 Population";"2015 GDP per Capita"]
table_Fig1b_Reg[:,1]=["Regions";"HIGH";"MEDIUM";"LOW"]

table_Fig1b_Reg[2:4,2]=[string(pop_high_2015);string(pop_med_2015);string(pop_low_2015)]
table_Fig1b_Reg[2:4,3]=[string(ypc_high_2015);string(ypc_med_2015);string(ypc_low_2015)]

table_Fig1b_Reg


writedlm("../output/poverty_fig1b_Reg.csv",table_Fig1b_Reg, ",")

## Table - Figure 2

In [185]:
#table_Fig2=Array{String}(undef,11,17)
#table_Fig2[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
#table_Fig2[:,1]=["Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]

#for j=2:17
#    table_Fig2[2,j]=string(reg_perc_dv_SCC[j-1])
#    table_Fig2[3,j]=string(reg_perc_sv_SCC[j-1])
#    table_Fig2[4,j]=string(reg_perc_mv_SCC[j-1])
#    table_Fig2[5,j]=string(reg_perc_chr_SCC[j-1])
#    table_Fig2[6,j]=string(reg_perc_ccr_SCC[j-1])
#    table_Fig2[7,j]=string(reg_perc_resp_SCC[j-1])
#    table_Fig2[8,j]=string(reg_perc_diar_SCC[j-1])
#    table_Fig2[9,j]=string(reg_perc_hurr_SCC[j-1])
#    table_Fig2[10,j]=string(reg_perc_extra_SCC[j-1])
#    table_Fig2[11,j]=string(Reg_Perc_Health_SCC[j-1])
#end
#        
#table_Fig2
#
#writedlm("poverty_Fig2.csv",table_Fig2, ",")

In [186]:
table_Fig2=Array{String}(undef,11,17)
table_Fig2[1,:]=["SCC by Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig2[:,1]=["SCC by Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]

for j=2:17
    table_Fig2[2,j]=string(reg_dv_SCC[j-1])
    table_Fig2[3,j]=string(reg_sv_SCC[j-1])
    table_Fig2[4,j]=string(reg_mv_SCC[j-1])
    table_Fig2[5,j]=string(reg_chr_SCC[j-1])
    table_Fig2[6,j]=string(reg_ccr_SCC[j-1])
    table_Fig2[7,j]=string(reg_resp_SCC[j-1])
    table_Fig2[8,j]=string(reg_diar_SCC[j-1])
    table_Fig2[9,j]=string(reg_hurr_SCC[j-1])
    table_Fig2[10,j]=string(reg_extra_SCC[j-1])
    table_Fig2[11,j]=string(reg_health_SCC[j-1])
end
        
table_Fig2

writedlm("../output/poverty_Fig2.csv",table_Fig2, ",")

#### Alternative Regions

In [187]:
table_Fig2_Reg=Array{String}(undef,11,4)
table_Fig2_Reg[1,:]=["SCC by Endpoint/Region";"High";"Medium";"Low"]
table_Fig2_Reg[:,1]=["SCC by Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]


table_Fig2_Reg[2,2:4]=[string(dv_SCC_high);string(dv_SCC_med);string(dv_SCC_low)]
table_Fig2_Reg[3,2:4]=[string(sv_SCC_high);string(sv_SCC_med);string(sv_SCC_low)]
table_Fig2_Reg[4,2:4]=[string(mv_SCC_high);string(mv_SCC_med);string(mv_SCC_low)]
table_Fig2_Reg[5,2:4]=[string(chr_SCC_high);string(chr_SCC_med);string(chr_SCC_low)]
table_Fig2_Reg[6,2:4]=[string(ccr_SCC_high);string(ccr_SCC_med);string(ccr_SCC_low)]
table_Fig2_Reg[7,2:4]=[string(resp_SCC_high);string(resp_SCC_med);string(resp_SCC_low)]
table_Fig2_Reg[8,2:4]=[string(diar_SCC_high);string(diar_SCC_med);string(diar_SCC_low)]
table_Fig2_Reg[9,2:4]=[string(hurr_SCC_high);string(hurr_SCC_med);string(hurr_SCC_low)]
table_Fig2_Reg[10,2:4]=[string(extra_SCC_high);string(extra_SCC_med);string(extra_SCC_low)]
table_Fig2_Reg[11,2:4]=[string(health_SCC_high);string(health_SCC_med);string(health_SCC_low)]
        
table_Fig2_Reg

writedlm("../output/poverty_Fig2_Reg.csv",table_Fig2_Reg, ",")

## Table - Appendix Figure 1

In [188]:
table_app1=Array{String}(undef,11,301)
table_app1[:,1]=["Mortalities by Endpoint/Year";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total"]

for j=2:301
    table_app1[1,j]=string(j-2+2000)
    table_app1[2,j]=string(dead_d_global[j-1])
    table_app1[3,j]=string(dead_s_global[j-1])
    table_app1[4,j]=string(dead_m_global[j-1])
    table_app1[5,j]=string(dead_ch_global[j-1])
    table_app1[6,j]=string(dead_cc_global[j-1])
    table_app1[7,j]=string(dead_r_global[j-1])
    table_app1[8,j]=string(dead_diah_global[j-1])
    table_app1[9,j]=string(dead_hurr_global[j-1])
    table_app1[10,j]=string(dead_extra_global[j-1])
    table_app1[11,j]=string(deaths_glob[j-1])
end

table_app1
table_app1b=permutedims(table_app1)

301×11 Matrix{String}:
 "Mortalities by Endpoint/Year"  …  "Total"
 "2000"                             "146329.3760479393"
 "2001"                             "151046.17592244447"
 "2002"                             "152292.32208001942"
 "2003"                             "154682.1588934941"
 "2004"                          …  "156637.28707168964"
 "2005"                             "158137.86526846"
 "2006"                             "159187.69793021708"
 "2007"                             "159776.56181101955"
 "2008"                             "159984.32029920336"
 "2009"                          …  "159766.82873739584"
 "2010"                             "159119.59059339002"
 "2011"                             "158032.50898717623"
 ⋮                               ⋱  ⋮
 "2288"                             "2.358140897794621e6"
 "2289"                          …  "2.3593990724841915e6"
 "2290"                             "2.3606458609262207e6"
 "2291"                             "2.3

In [189]:
writedlm("../output/poverty_app1.csv",table_app1b, ",")

## Table_Fig3 

In [190]:
table_Fig3=Array{String}(undef,3,17)
table_Fig3[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig3[:,1]=["Endpoint/Region";"Health";"SCC"]

for j=2:17
    table_Fig3[2,j]=string(reg_health_SCC[j-1])
    table_Fig3[3,j]=string(SCC_reg[j-1])
end
        
table_Fig3
table_Fig3=permutedims(table_Fig3)

writedlm("../output/poverty_table_fig3.csv",table_Fig3, ",")

#### Alternative Regions

In [191]:
table_Fig3_Reg=Array{String}(undef,3,4)
table_Fig3_Reg[1,:]=["Endpoint/Region";"High";"Medium";"Low"]
table_Fig3_Reg[:,1]=["Endpoint/Region";"Health";"SCC"]


table_Fig3_Reg[2,2:4]=[string(health_SCC_high);string(health_SCC_med);string(health_SCC_low)]
table_Fig3_Reg[3,2:4]=[string(SCC_high);string(SCC_med);string(SCC_low)]
        
table_Fig3_Reg
table_Fig3_Reg=permutedims(table_Fig3_Reg)

writedlm("../output/poverty_fig3_Reg.csv",table_Fig3_Reg, ",")

## Table_Fig4

In [192]:
table_Fig4a=Array{String}(undef,6,17)
table_Fig4a[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig4a[:,1]=["Endpoint/Region";"Avg VSL";"Weighted VSL";"Deaths";"Avg Per Capita GDP";"Weighted Per Capita GDP"]

for j=2:17
    table_Fig4a[2,j]=string(vsl_reg_avg[j-1])
    table_Fig4a[3,j]=string(vsl_reg_pop_avg[j-1])
    table_Fig4a[4,j]=string(deaths_reg_sum[j-1])
    table_Fig4a[5,j]=string(ypc_reg_avg[j-1])
    table_Fig4a[6,j]=string(ypc_reg_pop_avg[j-1])
end
        
table_Fig4a
table_Fig4a=permutedims(table_Fig4a)

writedlm("../output/poverty_fig4a.csv",table_Fig4a, ",")

In [193]:
table_Fig4b=Array{String}(undef,17,301)
table_Fig4b[:,1]=["VSL/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4b[1,j]=string(j-2+2000)
    table_Fig4b[2,j]=string(vsl_reg[j-1,1])
    table_Fig4b[3,j]=string(vsl_reg[j-1,2])
    table_Fig4b[4,j]=string(vsl_reg[j-1,3])
    table_Fig4b[5,j]=string(vsl_reg[j-1,4])
    table_Fig4b[6,j]=string(vsl_reg[j-1,5])
    table_Fig4b[7,j]=string(vsl_reg[j-1,6])
    table_Fig4b[8,j]=string(vsl_reg[j-1,7])
    table_Fig4b[9,j]=string(vsl_reg[j-1,8])
    table_Fig4b[10,j]=string(vsl_reg[j-1,9])
    table_Fig4b[11,j]=string(vsl_reg[j-1,10])
    table_Fig4b[12,j]=string(vsl_reg[j-1,11])
    table_Fig4b[13,j]=string(vsl_reg[j-1,12])
    table_Fig4b[14,j]=string(vsl_reg[j-1,13])
    table_Fig4b[15,j]=string(vsl_reg[j-1,14])
    table_Fig4b[16,j]=string(vsl_reg[j-1,15])
    table_Fig4b[17,j]=string(vsl_reg[j-1,16])
    
end

table_Fig4b
table_Fig4b=permutedims(table_Fig4b)
writedlm("../output/poverty_fig4b.csv",table_Fig4b, ",")

In [194]:
table_Fig4c=Array{String}(undef,17,301)
table_Fig4c[:,1]=["Mortalities/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4c[1,j]=string(j-2+2000)
    table_Fig4c[2,j]=string(deaths_reg[j-1,1])
    table_Fig4c[3,j]=string(deaths_reg[j-1,2])
    table_Fig4c[4,j]=string(deaths_reg[j-1,3])
    table_Fig4c[5,j]=string(deaths_reg[j-1,4])
    table_Fig4c[6,j]=string(deaths_reg[j-1,5])
    table_Fig4c[7,j]=string(deaths_reg[j-1,6])
    table_Fig4c[8,j]=string(deaths_reg[j-1,7])
    table_Fig4c[9,j]=string(deaths_reg[j-1,8])
    table_Fig4c[10,j]=string(deaths_reg[j-1,9])
    table_Fig4c[11,j]=string(deaths_reg[j-1,10])
    table_Fig4c[12,j]=string(deaths_reg[j-1,11])
    table_Fig4c[13,j]=string(deaths_reg[j-1,12])
    table_Fig4c[14,j]=string(deaths_reg[j-1,13])
    table_Fig4c[15,j]=string(deaths_reg[j-1,14])
    table_Fig4c[16,j]=string(deaths_reg[j-1,15])
    table_Fig4c[17,j]=string(deaths_reg[j-1,16])
    
end

table_Fig4c
table_Fig4c=permutedims(table_Fig4c)
writedlm("../output/poverty_fig4c.csv",table_Fig4c, ",")

In [195]:
table_Fig4d=Array{String}(undef,17,301)
table_Fig4d[:,1]=["YPC/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4d[1,j]=string(j-2+2000)
    table_Fig4d[2,j]=string(ypc_reg[j-1,1])
    table_Fig4d[3,j]=string(ypc_reg[j-1,2])
    table_Fig4d[4,j]=string(ypc_reg[j-1,3])
    table_Fig4d[5,j]=string(ypc_reg[j-1,4])
    table_Fig4d[6,j]=string(ypc_reg[j-1,5])
    table_Fig4d[7,j]=string(ypc_reg[j-1,6])
    table_Fig4d[8,j]=string(ypc_reg[j-1,7])
    table_Fig4d[9,j]=string(ypc_reg[j-1,8])
    table_Fig4d[10,j]=string(ypc_reg[j-1,9])
    table_Fig4d[11,j]=string(ypc_reg[j-1,10])
    table_Fig4d[12,j]=string(ypc_reg[j-1,11])
    table_Fig4d[13,j]=string(ypc_reg[j-1,12])
    table_Fig4d[14,j]=string(ypc_reg[j-1,13])
    table_Fig4d[15,j]=string(ypc_reg[j-1,14])
    table_Fig4d[16,j]=string(ypc_reg[j-1,15])
    table_Fig4d[17,j]=string(ypc_reg[j-1,16])
    
end

table_Fig4d
table_Fig4d=permutedims(table_Fig4d)
writedlm("../output/poverty_fig4d.csv",table_Fig4d, ",")

#### Alternative Regions

In [196]:
table_Fig4a_Reg=Array{String}(undef,5,4)
table_Fig4a_Reg[1,:]=["Endpoint/Region";"High";"Medium";"Low"]
table_Fig4a_Reg[:,1]=["Endpoint/Region";"Avg VSL";"Weighted VSL";"Deaths";"Avg Per Capita GDP"]


table_Fig4a_Reg[2,2:4]=[string(vsl_high_avg);string(vsl_med_avg);string(vsl_low_avg)]
table_Fig4a_Reg[3,2:4]=[string(vsl_high_pop_avg);string(vsl_med_pop_avg);string(vsl_low_pop_avg)]
table_Fig4a_Reg[4,2:4]=[string(dead_high_sum);string(dead_med_sum);string(dead_low_sum)]
table_Fig4a_Reg[5,2:4]=[string(ypc_high_avg);string(ypc_med_avg);string(ypc_low_avg)]

        
table_Fig4a_Reg
table_Fig4a_Reg=permutedims(table_Fig4a_Reg)

writedlm("../output/poverty_fig4a_Reg.csv",table_Fig4a_Reg, ",")

In [197]:
table_Fig4b_Reg=Array{String}(undef,4,301)
table_Fig4b_Reg[:,1]=["VSL/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4b_Reg[1,j]=string(j-2+2000)
    table_Fig4b_Reg[2,j]=string(vsl_high[j-1])
    table_Fig4b_Reg[3,j]=string(vsl_med[j-1])
    table_Fig4b_Reg[4,j]=string(vsl_low[j-1])    
end

table_Fig4b_Reg
table_Fig4b_Reg=permutedims(table_Fig4b_Reg)
writedlm("../output/poverty_fig4b_Reg.csv",table_Fig4b_Reg, ",")

In [198]:
table_Fig4c_Reg=Array{String}(undef,4,301)
table_Fig4c_Reg[:,1]=["Mortalities/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4c_Reg[1,j]=string(j-2+2000)
    table_Fig4c_Reg[2,j]=string(dead_high[j-1])
    table_Fig4c_Reg[3,j]=string(dead_med[j-1])
    table_Fig4c_Reg[4,j]=string(dead_low[j-1])
end

table_Fig4c_Reg
table_Fig4c_Reg=permutedims(table_Fig4c_Reg)
writedlm("../output/poverty_fig4c_Reg.csv",table_Fig4c_Reg, ",")

In [199]:
table_Fig4d_Reg=Array{String}(undef,4,301)
table_Fig4d_Reg[:,1]=["YPC/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4d_Reg[1,j]=string(j-2+2000)
    table_Fig4d_Reg[2,j]=string(ypc_high[j-1])
    table_Fig4d_Reg[3,j]=string(ypc_med[j-1])
    table_Fig4d_Reg[4,j]=string(ypc_low[j-1])
end

table_Fig4d_Reg
table_Fig4d_Reg=permutedims(table_Fig4d_Reg)
writedlm("../output/poverty_fig4d_Reg.csv",table_Fig4d_Reg, ",")