# VSL = 0 Model Run - Tables

In [1]:
using Mimi
using MimiFUND
using DelimitedFiles

In [2]:
parameters = MimiFUND.load_default_parameters();

In [3]:
m0 = MimiFUND.get_model(params=parameters);

In [4]:
run(m0);

# VSL and VMORB in 1950

In [5]:
vsl_1950 = m0[:vslvmorb, :vslbm] .* (m0[:socioeconomic, :ypc][1,:] ./  m0[:vslvmorb, :vslypc0]) .^ m0[:vslvmorb, :vslel]

16-element Vector{Float64}:
      2.0835227406450824e6
      1.2382844253883285e6
      1.25751895043233e6
      1.1846576551391e6
      2.3575787745608715e6
 200499.91081913593
 185795.53443847643
 259607.45039951298
 231508.00590938915
 336185.4191303534
  24982.275421174447
  28050.496290017694
   6629.558041336494
  60989.77875388889
 107720.13397436087
  68900.37750474535

In [6]:
vmorb_1950=  m0[:vslvmorb, :vmorbbm] .* (m0[:socioeconomic, :ypc][1,:] ./  m0[:vslvmorb, :vmorbypc0]) .^  m0[:vslvmorb, :vmorbel]

16-element Vector{Float64}:
 8334.090962580312
 4953.1377015533035
 5030.075801729309
 4738.63062055639
 9430.315098243467
  801.999643276542
  743.1821377539042
 1038.4298015980498
  926.0320236375546
 1344.7416765214107
   99.92910168469759
  112.20198516007054
   26.51823216534592
  243.95911501555506
  430.8805358974426
  275.60151001898083

## VSL and VMORB Matrix - Constant Starting in 2010

In [7]:
trick=zeros(1050,16)

trick[1,:]=trick[1,:]+vsl_1950

for j=2:60
trick[j,:]=trick[j,:]+m0[:vslvmorb,:vsl][j,:]
end

for j=61:1050
trick[j,:]=trick[j,:]+m0[:vslvmorb,:vsl][60,:]
end

trick
vsl_matrix=trick

1050×16 Matrix{Float64}:
 2.08352e6  1.23828e6  1.25752e6  1.18466e6  …       1.0772e5    68900.4
 2.12244e6  1.27277e6  1.29186e6  1.22297e6          1.0855e5    70919.2
 2.16209e6  1.30822e6  1.32714e6  1.26252e6          1.09385e5   72997.1
 2.20248e6  1.34465e6  1.36339e6  1.30335e6          1.10228e5   75135.9
 2.24362e6  1.3821e6   1.40062e6  1.3455e6           1.11076e5   77337.4
 2.28553e6  1.42059e6  1.43887e6  1.38901e6  …       1.11932e5   79603.4
 2.32822e6  1.46015e6  1.47817e6  1.43393e6          1.12794e5   81935.8
 2.37172e6  1.50082e6  1.51854e6  1.48031e6          1.13662e5   84336.5
 2.41602e6  1.54262e6  1.56001e6  1.52818e6          1.14537e5   86807.5
 2.46115e6  1.58558e6  1.60261e6  1.5776e6           1.15419e5   89351.0
 2.50713e6  1.62974e6  1.64638e6  1.62862e6  …  116308.0         91969.0
 2.55396e6  1.67513e6  1.69134e6  1.68129e6          1.17204e5   94663.7
 2.60167e6  1.72178e6  1.73753e6  1.73567e6     118106.0         97437.3
 ⋮                        

In [8]:
trick2=zeros(1050,16)

trick2[1,:]=trick2[1,:]+vmorb_1950

for j=2:60
trick2[j,:]=trick2[j,:]+m0[:vslvmorb,:vmorb][j,:]
end

for j=61:1050
trick2[j,:]=trick2[j,:]+m0[:vslvmorb,:vmorb][60,:]
end

trick2
vmorb_matrix=trick2

1050×16 Matrix{Float64}:
  8334.09   4953.14   5030.08   4738.63  …   243.959  430.881   275.602
  8489.77   5091.08   5167.45   4891.88      252.812  434.198   283.677
  8648.36   5232.87   5308.57   5050.08      261.987  437.542   291.988
  8809.91   5378.6    5453.55   5213.4       271.494  440.911   300.544
  8974.48   5528.4    5602.48   5382.0       281.347  444.306   309.35
  9142.12   5682.36   5755.49   5556.06  …   291.557  447.727   318.413
  9312.9    5840.62   5912.67   5735.74      302.138  451.174   327.743
  9486.86   6003.28   6074.14   5921.23      313.102  454.648   337.346
  9664.08   6170.47   6240.03   6112.73      324.465  458.149   347.23
  9844.6    6342.32   6410.44   6310.41      336.24   461.677   357.404
 10028.5    6518.95   6585.51   6514.49  …   348.442  465.232   367.876
 10215.8    6700.51   6765.36   6725.17      361.087  468.814   378.655
 10406.7    6887.11   6950.13   6942.66      374.19   472.424   389.749
     ⋮                                   

# VSL Model Run

In [9]:
m1 = getfund(params=parameters);

In [10]:
run(m1);

# Discount Factor

In [11]:
baseyear = 60
prtp = 0.01
eta = 1.0
ypc = m1[:socioeconomic, :ypc]
df_r = [t>=baseyear ? (ypc[baseyear,r]/ypc[t,r])^eta *
(1.0+prtp)^-(t-baseyear) : 0.0 for t in 1:1051, r in 1:16];
#df_r_1=df_r;
df_r_1=df_r[50:350,:];

# Key Variables

### Population - global population is in people while regional population is in millions

In [12]:
pop=m1[:population, :globalpopulation];

In [13]:
pop_glob=pop[50:350,:];

In [14]:
pop_glob_2015=pop[65,:]

1-element Vector{Union{Missing, Float64}}:
 7.137367861265218e9

In [15]:
pop_sum=sum(pop[50:350,:])

2.9525718318084233e12

In [16]:
pop_reg=m1[:population,:population][50:350,:];

In [17]:
pop_reg_2015=m1[:population,:population][65,:]

16-element Vector{Union{Missing, Float64}}:
  296.6535970838122
   33.431249558910004
  394.8071123966149
  192.84156190322105
   23.554005318590036
  126.78375950558814
  293.46950536833117
  316.0640013729959
  154.35852541453133
  414.73441564859706
 1669.7185639001902
  629.4278040754219
 1467.6906821341474
  192.4216987419381
  878.0180223464826
   53.39335649584536

In [18]:
pop_reg_sum=sum(m1[:population,:population][50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 89207.3  10082.8  1.185e5  66521.1  8192.45  …  110780.0  5.0317e5  20294.9

#### Alternative Regions 

In [19]:
pop_r=m1[:population,:population];
pop_high=sum(pop_r[50:350,1:5],dims=2)
pop_med=(pop_r[50:350,6]+sum(pop_r[50:350,8:10],dims=2)+sum(pop_r[50:350,12:13],dims=2))
pop_low=(pop_r[50:350,7]+pop_r[50:350,11]+pop_r[50:350,14]+pop_r[50:350,15]+pop_r[50:350,16])
pop_high_avg=sum(pop_high)/301
pop_med_avg=sum(pop_med)/301
pop_low_avg=sum(pop_low)/301
pop_high_2015=sum(pop_r[65,1:5],dims=2)
pop_med_2015=(pop_r[65,6]+sum(pop_r[65,8:10])+sum(pop_r[65,12:13]))
pop_low_2015=(pop_r[65,7]+pop_r[65,11]+pop_r[65,14]+pop_r[65,15]+pop_r[65,16])

3087.0211468527873

### Income - billions USD1995

In [20]:
globalincome= m1[:socioeconomic, :globalincome];

In [21]:
GDP_glob=globalincome[50:350,:];

In [22]:
GDP_glob_2015=globalincome[65,:]

1-element Vector{Union{Missing, Float64}}:
 47678.276069999585

In [23]:
income= m1[:socioeconomic, :income];

In [24]:
GDP_reg=income[50:350,:];

In [25]:
GDP_reg_2015=income[65,:]

16-element Vector{Union{Missing, Float64}}:
 12358.248121308387
   978.869745628328
 13481.458522413834
  8822.809906191913
   759.2688531103068
   589.752480936265
   827.0252943184078
  1095.1064692162138
   657.7103925191634
  2296.44173224361
  1075.6118744144867
  1463.5582030015614
  2265.4061267986417
   333.3163392439387
   589.6628853610193
    84.02912329351423

In [26]:
GDP_reg_sum=sum(df_r_1.*GDP_reg,dims=1)

1×16 Matrix{Float64}:
 1.07976e6  85617.3  1.17119e6  863831.0  …  48851.4  86012.6  8682.06

In [27]:
GDP_glob_sum=sum(df_r_1.*GDP_reg)

4.484847901103414e6

#### Alternative Regions 

In [28]:
gdp_high=sum(income[50:350,1:5],dims=2)
gdp_med=(income[50:350,6]+sum(income[50:350,8:10],dims=2)+sum(income[50:350,12:13],dims=2))
gdp_low=(income[50:350,7]+income[50:350,11]+income[50:350,14]+income[50:350,15]+income[50:350,16])
gdp_high2=sum(df_r[50:350,1:5].*income[50:350,1:5],dims=2)
gdp_med2=(df_r[50:350,6].*income[50:350,6]+sum(df_r[50:350,8:10].*income[50:350,8:10],dims=2)+sum(df_r[50:350,12:13].*income[50:350,12:13],dims=2))
gdp_low2=(df_r[50:350,7].*income[50:350,7]+df_r[50:350,11].*income[50:350,11]+df_r[50:350,14].*income[50:350,14]+df_r[50:350,15].*income[50:350,15]+df_r[50:350,16].*income[50:350,16])
gdp_high_avg=sum(gdp_high2)/291
gdp_med_avg=sum(gdp_med2)/291
gdp_low_avg=sum(gdp_low2)/291
gdp_high_2015=sum(income[65,1:5],dims=2)
gdp_med_2015=(income[65,6]+sum(income[65,8:10])+sum(income[65,12:13]))
gdp_low_2015=(income[65,7]+income[65,11]+income[65,14]+income[65,15]+income[65,16])

2909.6455166313663

### Income per capita 

In [29]:
ypc = m1[:socioeconomic, :ypc];

In [30]:
globalypc=m1[:socioeconomic, :globalypc]
ypc_glob=globalypc[50:350,:]

301×1 Matrix{Union{Missing, Float64}}:
   5337.418689168101
   5422.438217416453
   5569.008529772254
   5637.9743204687875
   5710.2491846359035
   5785.2183492772965
   5862.892168242639
   5943.333324301487
   6026.592385893459
   6112.786392293587
   6202.023668554732
   6294.385496073551
   6389.471703069227
      ⋮
 109299.60875363878
 109925.7274757352
 110552.58398571922
 111180.14861235594
 111808.39152286264
 112437.28274042773
 113066.79215836048
 113696.88951131578
 114327.54440596217
 114958.72633061686
 115590.404650417
 116222.54862704025

In [31]:
ypc_glob_2015=globalypc[65,:]

1-element Vector{Union{Missing, Float64}}:
 6680.092296874805

In [32]:
ypc_reg=ypc[50:350,:];

In [33]:
ypc_reg_2015=ypc[65,:]

16-element Vector{Union{Missing, Float64}}:
 41658.85141051186
 29280.082513919744
 34146.94948268978
 45751.59949502849
 32235.233152089542
  4651.6405826431655
  2818.0961878148637
  3464.825049543837
  4260.926895698672
  5537.138095116216
   644.187528167641
  2325.2201341048303
  1543.517414380902
  1732.218047253383
   671.5840339873197
  1573.7748815258074

In [34]:
ypc_reg_sum=sum(df_r_1.*ypc_reg,dims=1)

1×16 Matrix{Float64}:
 3.63316e6  2.55153e6  2.96889e6  3.97382e6  …  1.46459e5  56718.3  1.32729e5

In [35]:
ypc_reg_avg=ypc_reg_sum/291

1×16 Matrix{Float64}:
 12485.1  8768.14  10202.4  13655.7  …  438.298  503.297  194.908  456.114

In [36]:
ypc_reg_pop_avg=sum(df_r_1.*ypc_reg.*pop_reg,dims=1)./sum(pop_reg,dims=1)

1×16 Matrix{Float64}:
 12103.9  8491.43  9883.46  12985.8  …  416.971  440.977  170.942  427.795

In [37]:
ypc_glob_avg=(sum(GDP_reg_sum.*pop_reg)./sum(pop_reg))/291

769.9572890469371

In [38]:
ypc_glob_pop_avg=sum(df_r_1.*ypc_reg.*pop_reg)./sum(pop_reg)

1518.9631807726375

#### Alternative Regions 

In [39]:
ypc_high=1000*gdp_high./pop_high
ypc_med=1000*gdp_med./pop_med
ypc_low=1000*gdp_low./pop_low;
ypc_high_avg=1000*gdp_high_avg/pop_high_avg*(301/291)
ypc_med_avg=1000*gdp_med_avg/pop_med_avg*(301/291)
ypc_low_avg=1000*gdp_low_avg/pop_low_avg*(301/291)
ypc_high_2015=1000*gdp_high_2015./pop_high_2015
ypc_med_2015=1000*gdp_med_2015./pop_med_2015
ypc_low_2015=1000*gdp_low_2015./pop_low_2015

942.5414916894058

## Deaths

In [40]:
deaths = m1[:impactdeathmorbidity, :dead];

In [41]:
deaths_reg=deaths[50:350,:];

In [42]:
deaths_reg_2015=deaths[65,:]

16-element Vector{Union{Missing, Float64}}:
    603.0971346388916
      5.27988679433527
    339.5917443201339
    148.4104636388879
      1.2947512277704032
    140.33301638272204
  13450.395789310684
    484.25900829773593
    610.7234099276487
   1375.0918253082205
   6773.554870976271
    832.0133380108076
   1979.789207020567
   4243.393664693301
 120493.90434910511
    301.2762891164075

In [43]:
deaths_reg_sum=sum(deaths_reg,dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 1.42828e5  87.9228  81480.8  35611.7  …  361833.0  1.02198e7  32182.2

In [44]:
deaths_reg_avg=sum(deaths_reg,dims=1)/301

1×16 Matrix{Float64}:
 474.513  0.292102  270.7  118.311  …  374.878  1202.1  33952.9  106.918

In [45]:
deaths_glob=sum(deaths,dims=2)[50:350,:];

In [46]:
deaths_glob_2015=sum(deaths,dims=2)[65,:]

1-element Vector{Union{Missing, Float64}}:
 151782.4087487695

In [47]:
deaths_glob_sum=sum(deaths_glob)

1.3925347226462541e7

In [48]:
deaths_glob_avg=deaths_glob_sum/301

46263.61204804831

#### Alternative Regions 

In [49]:
dead_high=sum(deaths[50:350,1:5],dims=2)
dead_med=(deaths[50:350,6]+sum(deaths[50:350,8:10],dims=2)+sum(deaths[50:350,12:13],dims=2))
dead_low=(deaths[50:350,7]+deaths[50:350,11]+deaths[50:350,14]+deaths[50:350,15]+deaths[50:350,16])
dead_high_sum=sum(dead_high)
dead_med_sum=sum(dead_med)
dead_low_sum=sum(dead_low)
dead_high_avg=sum(dead_high)/301
dead_med_avg=sum(dead_med)/301
dead_low_avg=sum(dead_low)/301

43656.98011078971

### VSL

In [50]:
vsl=m1[:vslvmorb, :vsl];

In [51]:
vsl_reg=vsl[50:350,:];

In [52]:
vsl_reg_2015=vsl[65,:]

16-element Vector{Union{Missing, Float64}}:
      8.331770282102372e6
      5.8560165027839495e6
      6.829389896537956e6
      9.150319899005698e6
      6.4470466304179095e6
 930328.1165286332
 563619.2375629727
 692965.0099087674
 852185.3791397344
      1.1074276190232434e6
 128837.50563352818
 465044.0268209661
 308703.48287618044
 346443.6094506766
 134316.80679746394
 314754.9763051615

In [53]:
vsl_reg_avg=sum(df_r_1.*vsl_reg,dims=1)/291

1×16 Matrix{Float64}:
 2.49702e6  1.75363e6  2.04047e6  2.73115e6  …  1.00659e5  38981.7  91222.7

In [54]:
vsl_reg_pop_avg=vsl_reg_pop_avg=sum(df_r_1[10:300,:].*vsl_reg[10:300,:].*deaths_reg[10:300,:],dims=1)./sum(deaths_reg[10:300,:],dims=1)

1×16 Matrix{Float64}:
 2.8815e6  -449031.0  2.33299e6  2.95313e6  …  1.81917e5  71461.8  1.36382e5

In [55]:
#Incorrect
vsl_glob=sum(df_r.*vsl.*deaths,dims=2)./sum(deaths,dims=2)
vsl_glob=vsl_glob[50:350,:]

301×1 Matrix{Union{Missing, Float64}}:
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
      0.0
 228575.34846442926
 225647.78688795803
 222944.6452829596
      ⋮
  35742.593828489225
  35367.03371750702
  34994.58705747758
  34625.2443205913
  34258.99575871409
  33895.831374257185
  33535.740501691915
  33178.71241031991
  32824.736099656126
  32473.800167135534
  32125.893054399843
  31781.002726001876

In [56]:
vsl_glob_2015=vsl_glob[65,:]

1-element Vector{Union{Missing, Float64}}:
 149441.0367455261

In [57]:
vsl_glob_avg=sum(vsl_glob)/291

109296.0426956537

#### Alternative Regions 

In [58]:
mort_val=vsl.*deaths
vsl_high=sum(mort_val[50:350,1:5],dims=2)./sum(deaths[50:350,1:5],dims=2)
vsl_med=(mort_val[50:350,6]+sum(mort_val[50:350,8:10],dims=2)+sum(mort_val[50:350,12:13],dims=2))./(deaths[50:350,6]+sum(deaths[50:350,8:10],dims=2)+sum(deaths[50:350,12:13],dims=2))
vsl_low=(mort_val[50:350,7]+mort_val[50:350,11]+mort_val[50:350,14]+mort_val[50:350,15]+mort_val[50:350,16])./(deaths[50:350,7]+deaths[50:350,11]+deaths[50:350,14]+deaths[50:350,15]+deaths[50:350,16]);
vsl_high_avg=sum(vsl_high)/291
vsl_med_avg=sum(vsl_med)/291
vsl_low_avg=sum(vsl_low)/291
vsl_high_pop_avg=sum(mort_val[50:350,1:5])./sum(deaths[50:350,1:5])
vsl_med_pop_avg=(sum(mort_val[50:350,6])+sum(mort_val[50:350,8:10])+sum(mort_val[50:350,12:13]))./(sum(deaths[50:350,6])+sum(deaths[50:350,8:10])+sum(deaths[50:350,12:13]))
vsl_low_pop_avg=(sum(mort_val[50:350,7])+sum(mort_val[50:350,11])+sum(mort_val[50:350,14])+sum(mort_val[50:350,15])+sum(mort_val[50:350,16]))./(sum(deaths[50:350,7])+sum(deaths[50:350,11])+sum(deaths[50:350,14])+sum(deaths[50:350,15])+sum(deaths[50:350,16]))


1.1670998741855812e6

# SCC

In [59]:
m3 = MimiFUND.get_model(params=parameters);

In [60]:
add_comp!(m3, Mimi.adder, :co2marg, before=:climateco2cycle);

In [61]:
connect_param!(m3, :co2marg, :input, :emissions, :mco2)

In [62]:
connect_param!(m3, :climateco2cycle, :mco2, :co2marg, :output)

In [63]:
marginalemissions = zeros(1051)
marginalemissions[60] = 1
set_param!(m3, :co2marg, :add, marginalemissions);

In [64]:
run(m3)

In [65]:
md = (m3[:impactaggregation, :loss]-
    m1[:impactaggregation, :loss])/10^6;

In [66]:
pd=df_r.*md
SCC=sum(pd[60:300,:])

19.997817800256435

# Regional SCC

In [67]:
reg_SCC=sum(pd[60:300,:],dims=1);
SCC_reg=reg_SCC

1×16 Matrix{Union{Missing, Float64}}:
 4.38892  0.205078  6.53488  -0.541623  …  1.45016  1.76328  -0.0242873

#### Alternative Regions 

In [68]:
SCC_high=sum(SCC_reg[1:5])
SCC_med=(SCC_reg[6]+sum(SCC_reg[8:10])+sum(SCC_reg[12:13]))
SCC_low=(SCC_reg[7]+SCC_reg[11]+SCC_reg[14]+SCC_reg[15]+SCC_reg[16])

6.104490942111087

## Health SCC

In [69]:
marg_health=10^9*((m3[:impactdeathmorbidity, :deadcost]+m3[:impactdeathmorbidity, :morbcost])-(m1[:impactdeathmorbidity, :deadcost]+m1[:impactdeathmorbidity, :morbcost]));

In [70]:
pd_health=(df_r.*marg_health)/10^6
health_SCC=sum(pd_health[60:300,:])

1.7448486940676682

In [71]:
Perc_Health_SCC=health_SCC/SCC

0.08725195476304888

## Health Regional SCC

In [72]:
reg_health_SCC=sum(pd_health[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.371899  3.18727e-5  0.177026  …  0.0569041  0.603641  0.00339514

In [73]:
Reg_Perc_Health_SCC=reg_health_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.084736  0.000155418  0.0270894  …  0.0392399  0.34234  -0.139791

In [74]:
Perc_health_SCC_reg=reg_health_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.084736  0.000155418  0.0270894  …  0.0392399  0.34234  -0.139791

#### Alternative Regions 

In [75]:
health_SCC_high=sum(reg_health_SCC[1:5])
health_SCC_med=(reg_health_SCC[6]+sum(reg_health_SCC[8:10])+sum(reg_health_SCC[12:13]))
health_SCC_low=(reg_health_SCC[7]+reg_health_SCC[11]+reg_health_SCC[14]+reg_health_SCC[15]+reg_health_SCC[16])

0.9774287191391161

# Health Endpoint SCC

### Dengue Fever 

In [76]:
dv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :dengue]./(10^9)

trick=ones(1051,16)
trick2=parameters[:d2dd]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick

#dv_2=m1[:vslvmorb, :vmorb]*parameters["d2dd"].*m1[:impactvectorbornediseases, :dengue]./1000000000.0
dv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :dengue]./(10^9)
dv_3=dv_1+dv_2
pv_dv_1=df_r.*dv_1
pv_dv_2=df_r.*dv_2
pv_dv_3=df_r.*dv_3;

In [77]:
dv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :dengue]./(10^9)

trick=ones(1051,16)
trick2=parameters[:d2dd]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick;

dv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :dengue]./(10^9)
dv_3b=dv_1b+dv_2b

1051×16 Matrix{Union{Missing, Float64}}:
  missing   missing   missing  …   missing     missing      missing
 0.0       0.0       0.0          0.00714076  0.000529003  0.00135431
 0.0       0.0       0.0          0.00705276  0.000546377  0.00134619
 0.0       0.0       0.0          0.00696585  0.000564321  0.00133812
 0.0       0.0       0.0          0.00687919  0.000582785  0.00132995
 0.0       0.0       0.0       …  0.00679232  0.00060174   0.00132157
 0.0       0.0       0.0          0.0067046   0.00062113   0.00131286
 0.0       0.0       0.0          0.00661568  0.00064092   0.00130376
 0.0       0.0       0.0          0.00652688  0.000661233  0.0012945
 0.0       0.0       0.0          0.00643965  0.00068223   0.00128539
 0.0       0.0       0.0       …  0.00635705  0.000704277  0.00127704
 0.0       0.0       0.0          0.00628238  0.00072969   0.00127002
 0.0       0.0       0.0          0.0062078   0.000755924  0.00126288
 ⋮                             ⋱                    

In [78]:
marg_dengue=10^9*(dv_3b-dv_3)
pd_dengue=(df_r.*marg_dengue)/10^6
dv_SCC=sum(pd_dengue[60:300,:])
perc_dv_SCC=dv_SCC/SCC

0.00018823548880147884

In [79]:
reg_dv_SCC=sum(pd_dengue[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.0  0.0  0.0  0.000771059  0.0  0.0  …  0.000186428  0.000178709  2.5242e-5

In [80]:
reg_perc_dv_SCC=reg_dv_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.0  0.0  0.0  -0.00142361  0.0  0.0  0.0  …  0.00010135  -0.00103931

### Schist 

In [81]:
sv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :schisto]./(10^9)

#sv_2=m1[:vslvmorb, :vmorb]*parameters["d2ds"].*m1[:impactvectorbornediseases, :schisto]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2ds]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
sv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :schisto]./(10^9)

sv_3=sv_1+sv_2
pv_sv_1=df_r.*sv_1
pv_sv_2=df_r.*sv_2
pv_sv_3=df_r.*sv_3;

In [82]:
sv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :schisto]./(10^9)

trick=ones(1051,16)
trick2=parameters[:d2ds]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
sv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :schisto]./(10^9)
sv_3b=sv_1b+sv_2b

marg_schisto=10^9*(sv_3b-sv_3)
pd_schisto=(df_r.*marg_schisto)/10^6
schisto_SCC=sum(pd_schisto[60:300,:])
perc_schisto_SCC=schisto_SCC/SCC

-0.0002999193226689261

In [83]:
reg_sv_SCC=sum(pd_schisto[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -1.39211e-5  -1.38747e-6  -5.23315e-5  …  -0.00297935  -1.34373e-5

In [84]:
reg_perc_sv_SCC=reg_sv_SCC./reg_SCC

1×16 Matrix{Float64}:
 -3.17188e-6  -6.76561e-6  -8.00804e-6  …  -0.00168966  0.000553265

### Malaria 

In [85]:
mv_1=m1[:vslvmorb, :vsl].*m1[:impactvectorbornediseases, :malaria]./(10^9)

#mv_2=m1[:vslvmorb, :vmorb]*parameters["d2dm"].*m1[:impactvectorbornediseases, :malaria]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dm]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
mv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactvectorbornediseases, :malaria]./(10^9)

mv_3=mv_1+mv_2
pv_mv_1=df_r.*mv_1
pv_mv_2=df_r.*mv_2
pv_mv_3=df_r.*mv_3;

In [86]:
mv_1b=m3[:vslvmorb, :vsl].*m3[:impactvectorbornediseases, :malaria]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dm]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
mv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactvectorbornediseases, :malaria]./(10^9)
mv_3b=mv_1b+mv_2b

marg_malaria=10^9*(mv_3b-mv_3)
pd_malaria=(df_r.*marg_malaria)/10^6
malaria_SCC=sum(pd_malaria[60:300,:])
perc_malaria_SCC=malaria_SCC/SCC

0.009769874023577686

In [87]:
reg_mv_SCC=sum(pd_malaria[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 3.16085e-5  3.15032e-6  0.000433956  …  0.0193729  0.164173  0.000666612

In [88]:
reg_perc_mv_SCC=reg_mv_SCC./reg_SCC

1×16 Matrix{Float64}:
 7.20189e-6  1.53616e-5  6.64061e-5  …  0.0133591  0.0931064  -0.027447

### Cardiovascular - Heat Related

In [89]:
hv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)

#hv_2=m1[:vslvmorb, :vmorb]*parameters["d2dc"].*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
hv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :cardheat]./(10^9)

hv_3=hv_1+hv_2
pv_hv_1=df_r.*hv_1
pv_hv_2=df_r.*hv_2
pv_hv_3=df_r.*hv_3;

In [90]:
hv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :cardheat]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
trick
hv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :cardheat]./(10^9)
hv_3b=hv_1b+hv_2b

marg_chr=10^9*(hv_3b-hv_3)
pd_chr=(df_r.*marg_chr)/10^6
chr_SCC=sum(pd_chr[60:300,:])

-0.0018704598748399519

In [91]:
perc_chr_SCC=chr_SCC/SCC

-9.35331991481574e-5

In [92]:
reg_chr_SCC=sum(pd_chr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -0.000424259  -1.9893e-5  -0.000826782  …  -5.20762e-5  2.86771e-6

In [93]:
reg_perc_chr_SCC=reg_chr_SCC./reg_SCC

1×16 Matrix{Float64}:
 -9.66659e-5  -9.70025e-5  -0.000126518  …  -2.95337e-5  -0.000118074

### Cardiovascular - Cold Related

In [94]:
cv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)

#cv_2=m1[:vslvmorb, :vmorb]*parameters["d2dc"].*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
cv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :cardcold]./(10^9)

cv_3=cv_1+cv_2
pv_cv_1=df_r.*cv_1
pv_cv_2=df_r.*cv_2
pv_cv_3=df_r.*cv_3;

In [95]:
cv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :cardcold]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dc]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
cv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :cardcold]./(10^9)
cv_3b=cv_1b+cv_2b

marg_ccr=10^9*(cv_3b-cv_3)
pd_ccr=(df_r.*marg_ccr)/10^6
ccr_SCC=sum(pd_ccr[60:300,:])

0.0016046213411199297

In [96]:
perc_ccr_SCC=ccr_SCC/SCC

8.023982202194849e-5

In [97]:
reg_ccr_SCC=sum(pd_ccr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.000443848  2.04933e-5  0.000865812  …  6.51904e-5  -3.57049e-6

In [98]:
reg_perc_ccr_SCC=reg_ccr_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.000101129  9.99294e-5  0.000132491  …  9.11041e-5  3.69711e-5  0.000147011

## Cardiovascular - Respiratory

In [99]:
rv_1=m1[:vslvmorb, :vsl].*m1[:impactcardiovascularrespiratory, :resp]./(10^9)

#rv_2=m1[:vslvmorb, :vmorb]*parameters["d2dr"].*m1[:impactcardiovascularrespiratory, :resp]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dr]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
rv_2=m1[:vslvmorb, :vmorb].*trick.*m1[:impactcardiovascularrespiratory, :resp]./(10^9)


rv_3=rv_1+rv_2
pv_rv_1=df_r.*rv_1
pv_rv_2=df_r.*rv_2
pv_rv_3=df_r.*rv_3;

In [100]:
rv_1b=m3[:vslvmorb, :vsl].*m3[:impactcardiovascularrespiratory, :resp]./(10^9)
trick=ones(1051,16)
trick2=parameters[:d2dr]
for j=1:16
trick[:,j]=trick[:,j].*trick2[j]
end
rv_2b=m3[:vslvmorb, :vmorb].*trick.*m3[:impactcardiovascularrespiratory, :resp]./(10^9)
rv_3b=rv_1b+rv_2b

marg_resp=10^9*(rv_3b-rv_3)
pd_resp=(df_r.*marg_resp)/10^6
resp_SCC=sum(pd_resp[60:300,:])

-0.00019295565267656617

In [101]:
perc_resp_SCC=resp_SCC/SCC

-9.648835418137066e-6

In [102]:
reg_resp_SCC=sum(pd_resp[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 -4.63193e-5  -2.09943e-6  -8.06784e-5  …  -1.49124e-5  -9.71e-6  4.35965e-7

In [103]:
reg_perc_resp_SCC=reg_resp_SCC./reg_SCC

1×16 Matrix{Float64}:
 -1.05537e-5  -1.02373e-5  -1.23458e-5  …  -5.50678e-6  -1.79504e-5

## Diarrhea 

In [104]:
d_1=m1[:vslvmorb, :vsl].*m1[:impactdiarrhoea, :diadead]./(10^9)
d_2=m1[:vslvmorb, :vmorb].*m1[:impactdiarrhoea, :diasick]./(10^9)
d_3=d_1+d_2
pv_d_1=df_r.*d_1
pv_d_2=df_r.*d_2
pv_d_3=df_r.*d_3;

In [105]:
d_1b=m3[:vslvmorb, :vsl].*m3[:impactdiarrhoea, :diadead]./(10^9)
d_2b=m3[:vslvmorb, :vmorb].*m3[:impactdiarrhoea, :diasick]./(10^9)
d_3b=d_1b+d_2b

marg_diar=10^9*(d_3b-d_3)
pd_diar=(df_r.*marg_diar)/10^6
diar_SCC=sum(pd_diar[60:300,:])

1.5073218600793452

In [106]:
perc_diar_SCC=diar_SCC/SCC

0.07537431709473903

In [107]:
reg_diar_SCC=sum(pd_diar[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.363518  0.0  0.176012  0.0644843  …  0.0378394  0.442012  0.00203418

In [108]:
reg_perc_diar_SCC=reg_diar_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.0828264  0.0  0.0269342  -0.119057  …  0.0260933  0.250676  -0.0837548

## Hurricane 

In [109]:
hd_1=m1[:vslvmorb, :vsl].*m1[:impacttropicalstorms, :hurrdead]./(10^9)
hd_3=hd_1
pv_hd_1=df_r.*hd_1
pv_hd_3=pv_hd_1;

In [110]:
hd_1b=m3[:vslvmorb, :vsl].*m3[:impacttropicalstorms, :hurrdead]./(10^9)
hd_3b=hd_1b

marg_hurr=10^9*(hd_3b-hd_3)
pd_hurr=(df_r.*marg_hurr)/10^6
hurr_SCC=sum(pd_hurr[60:300,:])

0.041221964457289394

In [111]:
perc_hurr_SCC=hurr_SCC/SCC

0.0020613231338051695

In [112]:
reg_hurr_SCC=sum(pd_hurr[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.0070398  7.2826e-6  4.40642e-5  0.00817664  …  0.0  0.00019417  0.00053481

In [113]:
reg_perc_hurr_SCC=reg_hurr_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.00160399  3.55114e-5  6.74293e-6  …  0.0  0.000110119  -0.0220202

## Extratropical Storms

In [114]:
es_1=m1[:vslvmorb, :vsl].*m1[:impactextratropicalstorms, :extratropicalstormsdead]./(10^9)
es_3=es_1
pv_es_1=df_r.*es_1
pv_es_3=pv_es_1;

In [115]:
es_1b=m3[:vslvmorb, :vsl].*m3[:impactextratropicalstorms, :extratropicalstormsdead]./(10^9)
es_3b=es_1b

marg_extra=10^9*(es_3b-es_3)
pd_extra=(df_r.*marg_extra)/10^6
extra_SCC=sum(pd_extra[60:300,:])

0.003620935995083587

In [116]:
perc_extra_SCC=extra_SCC/SCC

0.00018106655592377462

In [117]:
reg_extra_SCC=sum(pd_extra[60:300,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 0.00135005  2.43265e-5  0.00063062  …  5.51272e-6  5.9452e-5  0.00014801

In [118]:
reg_perc_extra_SCC=reg_extra_SCC./reg_SCC

1×16 Matrix{Float64}:
 0.000307604  0.000118621  9.65007e-5  …  3.80145e-6  3.37167e-5  -0.00609413

#### Alternative Regions

In [119]:
dv_SCC_high=sum(reg_dv_SCC[1:5])
dv_SCC_med=(reg_dv_SCC[6]+sum(reg_dv_SCC[8:10])+sum(reg_dv_SCC[12:13]))
dv_SCC_low=(reg_dv_SCC[7]+reg_dv_SCC[11]+reg_dv_SCC[14]+reg_dv_SCC[15]+reg_dv_SCC[16])

sv_SCC_high=sum(reg_sv_SCC[1:5])
sv_SCC_med=(reg_sv_SCC[6]+sum(reg_sv_SCC[8:10])+sum(reg_sv_SCC[12:13]))
sv_SCC_low=(reg_sv_SCC[7]+reg_sv_SCC[11]+reg_sv_SCC[14]+reg_sv_SCC[15]+reg_sv_SCC[16])

mv_SCC_high=sum(reg_mv_SCC[1:5])
mv_SCC_med=(reg_mv_SCC[6]+sum(reg_mv_SCC[8:10])+sum(reg_mv_SCC[12:13]))
mv_SCC_low=(reg_mv_SCC[7]+reg_mv_SCC[11]+reg_mv_SCC[14]+reg_mv_SCC[15]+reg_mv_SCC[16])

chr_SCC_high=sum(reg_chr_SCC[1:5])
chr_SCC_med=(reg_chr_SCC[6]+sum(reg_chr_SCC[8:10])+sum(reg_chr_SCC[12:13]))
chr_SCC_low=(reg_chr_SCC[7]+reg_chr_SCC[11]+reg_chr_SCC[14]+reg_chr_SCC[15]+reg_chr_SCC[16])

ccr_SCC_high=sum(reg_ccr_SCC[1:5])
ccr_SCC_med=(reg_ccr_SCC[6]+sum(reg_ccr_SCC[8:10])+sum(reg_ccr_SCC[12:13]))
ccr_SCC_low=(reg_ccr_SCC[7]+reg_ccr_SCC[11]+reg_ccr_SCC[14]+reg_ccr_SCC[15]+reg_ccr_SCC[16])

resp_SCC_high=sum(reg_resp_SCC[1:5])
resp_SCC_med=(reg_resp_SCC[6]+sum(reg_resp_SCC[8:10])+sum(reg_resp_SCC[12:13]))
resp_SCC_low=(reg_resp_SCC[7]+reg_resp_SCC[11]+reg_resp_SCC[14]+reg_resp_SCC[15]+reg_resp_SCC[16])

diar_SCC_high=sum(reg_diar_SCC[1:5])
diar_SCC_med=(reg_diar_SCC[6]+sum(reg_diar_SCC[8:10])+sum(reg_diar_SCC[12:13]))
diar_SCC_low=(reg_diar_SCC[7]+reg_diar_SCC[11]+reg_diar_SCC[14]+reg_diar_SCC[15]+reg_diar_SCC[16])

hurr_SCC_high=sum(reg_hurr_SCC[1:5])
hurr_SCC_med=(reg_hurr_SCC[6]+sum(reg_hurr_SCC[8:10])+sum(reg_hurr_SCC[12:13]))
hurr_SCC_low=(reg_hurr_SCC[7]+reg_hurr_SCC[11]+reg_hurr_SCC[14]+reg_hurr_SCC[15]+reg_hurr_SCC[16])

extra_SCC_high=sum(reg_extra_SCC[1:5])
extra_SCC_med=(reg_extra_SCC[6]+sum(reg_extra_SCC[8:10])+sum(reg_extra_SCC[12:13]))
extra_SCC_low=(reg_extra_SCC[7]+reg_extra_SCC[11]+reg_extra_SCC[14]+reg_extra_SCC[15]+reg_extra_SCC[16])

0.000633753649544929

# Mortality Endpoint

## Dengue Fever

### Regional

In [120]:
dead_d=m1[:impactvectorbornediseases, :dengue]
dead_d_region=dead_d[50:350,:];

In [121]:
Kevin_d_dead=permutedims(sum(dead_d[50:350,:],dims=1));

### Global 

In [122]:
dead_d_sum=sum(dead_d,dims=2)
dead_d_global=dead_d_sum[50:350,:];

## Schisto

### Regional

In [123]:
dead_s=m1[:impactvectorbornediseases, :schisto]
dead_s_region=dead_s[50:350,:];

In [124]:
Kevin_s_dead=permutedims(sum(dead_s[50:350,:],dims=1));

### Global 

In [125]:
dead_s_sum=sum(dead_s,dims=2)
dead_s_global=dead_s_sum[50:350,:];

## Malaria

### Regional

In [126]:
dead_m=m1[:impactvectorbornediseases, :malaria]
dead_m_region=dead_m[50:350,:];

In [127]:
Kevin_m_dead=permutedims(sum(dead_m[50:350,:],dims=1));

### Global 

In [128]:
dead_m_sum=sum(dead_m,dims=2)
dead_m_global=dead_m_sum[50:350,:];

## Cardio - Heat

### Regional

In [129]:
dead_ch=m1[:impactcardiovascularrespiratory, :cardheat]
dead_ch_region=dead_ch[50:350,:];

In [130]:
Kevin_ch_dead=permutedims(sum(dead_ch[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  21818.74163617644
   2322.133758747711
  34290.81033906312
  14548.675662153362
   1672.9955118913272
  11883.775196272893
  35783.38508493988
  20543.528855202927
   7705.597342184571
  23526.5365927792
 111706.99846757957
      6.344255610318329
 125734.13274444145
  15420.95611104412
  42032.248168445905
   3121.0505677978117

### Global 

In [131]:
dead_ch_sum=sum(dead_ch,dims=2)
dead_ch_global=dead_ch_sum[50:350,:];

## Cardio - Cold 

### Regional

In [132]:
dead_cc=m1[:impactcardiovascularrespiratory, :cardcold]
dead_cc_region=dead_ch[50:350,:];

In [133]:
Kevin_cc_dead=permutedims(sum(dead_cc[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  -23089.599469886714
   -2466.7646930291
  -38093.040688758505
  -15371.017697381962
   -1774.6810164447045
  -13958.213310474408
  -44492.92472888647
  -23638.15297259017
   -8767.876749543866
  -25894.764472156134
 -157677.55184235756
   -2582.7026151270143
 -152163.86859739484
  -19072.472361700376
  -57668.942071222446
   -3824.2263504144366

### Global 

In [134]:
dead_cc_sum=sum(dead_cc,dims=2)
dead_cc_global=dead_cc_sum[50:350,:];

## Respiratory

### Regional

In [135]:
dead_r=m1[:impactcardiovascularrespiratory, :resp]
dead_r_region=dead_ch[50:350,:];

In [136]:
Kevin_r_dead=permutedims(sum(dead_r[50:350,:],dims=1))

16×1 Matrix{Union{Missing, Float64}}:
  2611.31622326968
   187.50245552776383
  2880.9148505228304
  1520.82690169071
   180.76359683823242
   591.8621744789118
  2137.3937335556016
  1707.4773960273142
  1182.0969725005536
  3398.467713031047
 12406.63457164271
  6050.528803173632
  7390.461347985384
  1935.1649748225968
  7709.227839377183
   413.55562411153414

### Global 

In [137]:
dead_r_sum=sum(dead_r,dims=2)
dead_r_global=dead_r_sum[50:350,:];

## Diarrhea

### Regional

In [138]:
dead_diah=m1[:impactdiarrhoea, :diadead]
dead_diah_reg=sum(dead_diah[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 1.32797e5  0.0  81434.4  25669.2  151.99  …  2.64583e5  7.84304e6  14024.5

In [139]:
Kevin_diar_death=permutedims(dead_diah_reg)

16×1 Matrix{Union{Missing, Float64}}:
 132797.12067746656
      0.0
  81434.44419187715
  25669.180377485434
    151.98993789910242
  13064.998035333658
      1.337416061013332e6
  32674.769288544416
  43121.47805775782
 112190.88686834685
 442808.19837358495
  62215.00750920037
 120307.28163385433
 264582.6053588498
      7.843037210004224e6
  14024.50292899489

### Global 

In [140]:
dead_diah_sum=sum(dead_diah,dims=2)
dead_diah_global=dead_diah_sum[50:350,:];

## Hurricane

### Regional

In [141]:
dead_hurr=m1[:impacttropicalstorms, :hurrdead];
dead_hurr_reg=sum(dead_hurr[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 7372.57  10.791  57.4282  7909.78  …  9204.96  0.0  11343.4  10895.8

In [142]:
Kevin_hurr_dead=permutedims(sum(dead_hurr[50:350,:],dims=1));

### Global 

In [143]:
dead_hurr_sum=sum(dead_hurr,dims=2)
dead_hurr_global=dead_hurr_sum[50:350,:];

## Extra-tropical

### Regional

In [144]:
dead_extra=m1[:impactextratropicalstorms, :extratropicalstormsdead];
dead_extra_reg=sum(dead_extra[50:350,:],dims=1)

1×16 Matrix{Union{Missing, Float64}}:
 1312.57  33.4705  759.717  404.388  …  1006.09  134.81  3478.54  2938.2

In [145]:
Kevin_extra_dead=permutedims(sum(dead_extra[50:350,:],dims=1));

### Global 

In [146]:
dead_extra_sum=sum(dead_extra,dims=2)
dead_extra_global=dead_extra_sum[50:350,:];

# SCC - Breakdown

## Agriculture 

In [147]:
agr_1=m1[:impactagriculture, :agcost]
pv_agr_1=df_r.*agr_1;
agr_3=m3[:impactagriculture, :agcost]
pv_agr_3=df_r.*agr_3;
marg_agr=1000000000.0*(agr_3-agr_1);
pd_agr=(df_r.*marg_agr)/10^6
agr_SCC=-1*sum(pd_agr[60:300,:])

-6.13816959108143

In [148]:
perc_agr_SCC=agr_SCC/SCC

-0.3069419699884814

## Cooling

In [149]:
cool_1=m1[:impactcooling, :cooling]
pv_cool_1=df_r.*cool_1;
cool_3=m3[:impactcooling, :cooling]
pv_cool_3=df_r.*cool_3;
marg_cool=1000000000.0*(cool_3-cool_1);
pd_cool=(df_r.*marg_cool)/10^6
cool_SCC=-1*sum(pd_cool[60:300,:])

24.227774277605008

In [150]:
perc_cool_SCC=cool_SCC/SCC

1.211520902910433

## Biodiversity

In [151]:
bio_1=m1[:impactbiodiversity, :species]
bio_3=m3[:impactbiodiversity, :species]
marg_bio=1000000000.0*(bio_3-bio_1);
pd_bio=(df_r.*marg_bio)/10^6
bio_SCC=sum(pd_bio[60:300,:])

1.5444475236840045

In [152]:
perc_bio_SCC=bio_SCC/SCC

0.07723080283610743

## Extra-tropical storm: Non-health 

In [153]:
extra_dam_1=m1[:impactextratropicalstorms, :extratropicalstormsdam]
extra_dam_3=m3[:impactextratropicalstorms, :extratropicalstormsdam]
marg_extra_dam=1000000000.0*(extra_dam_3-extra_dam_1);
pd_extra_dam=(df_r.*marg_extra_dam)/10^6
extra_dam_SCC=sum(pd_extra_dam[60:300,:])

0.017622757219879055

In [154]:
perc_extra_dam_SCC=extra_dam_SCC/SCC

0.0008812340124257496

## Forestry

In [155]:
forest_1=m1[:impactforests, :forests]
forest_3=m3[:impactforests, :forests]
marg_forest=1000000000.0*(forest_3-forest_1);
pd_forest=(df_r.*marg_forest)/10^6
forest_SCC=-1*sum(pd_forest[60:300,:])

-0.12687991076882543

In [156]:
perc_forest_SCC=forest_SCC/SCC

-0.006344687807246571

## Health

In [157]:
health_alt_1=m1[:impactdeathmorbidity, :deadcost]+m1[:impactdeathmorbidity, :morbcost]
health_alt_3=m3[:impactdeathmorbidity, :deadcost]+m3[:impactdeathmorbidity, :morbcost]
marg_health_alt=1000000000.0*(health_alt_3-health_alt_1);
pd_health_alt=(df_r.*marg_health_alt)/10^6
health_alt_SCC=sum(pd_health_alt[60:300,:])## Health

1.7448486940676682

In [158]:
perc_health_alt_SCC=health_alt_SCC/SCC

0.08725195476304888

## Heating 

In [159]:
heat_1=m1[:impactheating, :heating]
pv_heat_1=df_r.*heat_1;
heat_3=m3[:impactheating, :heating]
pv_heat_3=df_r.*heat_3;
marg_heat=1000000000.0*(heat_3-heat_1);
pd_heat=(df_r.*marg_heat)/10^6
heat_SCC=-1*sum(pd_heat[60:300,:])

-4.8404465745904375

In [160]:
perc_heat_SCC=heat_SCC/SCC

-0.24204873866429405

## Energy Consumption

In [161]:
energy_SCC=heat_SCC+cool_SCC

19.38732770301457

In [162]:
perc_energy_SCC=energy_SCC/SCC

0.969472164246139

## Sea-level rise

In [163]:
slr_1=m1[:impactsealevelrise, :leavecost]+m1[:impactsealevelrise, :entercost]
slr_1=slr_1+m1[:impactsealevelrise, :drycost]+m1[:impactsealevelrise, :protcost]
slr_1=slr_1+m1[:impactsealevelrise, :wetcost]
pv_slr_1=df_r.*slr_1;
slr_3=m3[:impactsealevelrise, :leavecost]+m3[:impactsealevelrise, :entercost]
slr_3=slr_3+m3[:impactsealevelrise, :drycost]+m3[:impactsealevelrise, :protcost]
slr_3=slr_3+m3[:impactsealevelrise, :wetcost]
pv_slr_3=df_r.*slr_3;
marg_slr=1000000000.0*(slr_3-slr_1);
pd_slr=(df_r.*marg_slr)/10^6
slr_SCC=sum(pd_slr[60:300,:])

0.4733317397036487

In [164]:
perc_slr_SCC=slr_SCC/SCC

0.023669169527966154

## Tropical - Non-health

In [165]:
hurr_dam_1=m1[:impacttropicalstorms, :hurrdam]
hurr_dam_3=m3[:impacttropicalstorms, :hurrdam]
marg_hurr_dam=1000000000.0*(hurr_dam_3-hurr_dam_1);
pd_hurr_dam=(df_r.*marg_hurr_dam)/10^6
hurr_dam_SCC=sum(pd_hurr_dam[60:300,:])

0.1941669946234637

In [166]:
perc_hurr_dam_SCC=hurr_dam_SCC/SCC

0.009709409124678287

## Storms

In [167]:
storm_SCC=hurr_dam_SCC+extra_dam_SCC

0.21178975184334276

In [168]:
perc_storm_SCC=perc_hurr_dam_SCC+perc_extra_dam_SCC

0.010590643137104037

## Water

In [169]:
water_1=m1[:impactwaterresources, :water]
pv_water_1=df_r.*water_1;
water_3=m3[:impactwaterresources, :water]
pv_water_3=df_r.*water_3;
marg_water=1000000000.0*(water_3-water_1);
pd_water=(df_r.*marg_water)/10^6
water_SCC=-1*sum(pd_water[60:300,:])

2.9011218897967397

In [170]:
perc_water_SCC=water_SCC/SCC

0.1450719232855266

## Other

In [171]:
eloss_other=parameters[:eloss_other]
eloss_other=sum(eloss_other)

0.0

In [172]:
sloss_other=parameters[:sloss_other]
sloss_other=sum(sloss_other)

0.0

## SCC - Check

### SCC-Aggregate

In [173]:
SCC_Check_1=m1[:impactaggregation, :loss]
SCC_Check_3=m3[:impactaggregation, :loss]
marg_SCC_Check=(SCC_Check_3-SCC_Check_1);
pd_SCC_Check=(df_r.*marg_SCC_Check)/10^6
SCC_Check=sum(pd_SCC_Check[60:300,:])

19.99781780025643

### SCC-Aggregate-2

In [174]:
SCC_Check_2=agr_SCC+cool_SCC+bio_SCC+forest_SCC+health_alt_SCC+heat_SCC+slr_SCC+hurr_dam_SCC+water_SCC

19.980195043039846

### SCC-Aggregate-3

In [175]:
SCC_Check_3=perc_agr_SCC+perc_cool_SCC+perc_bio_SCC+perc_forest_SCC+perc_health_alt_SCC+perc_heat_SCC+perc_slr_SCC+perc_hurr_dam_SCC+perc_water_SCC

0.9991187659877383

# Tables

## Tables for Figure 1

In [176]:
Table_Fig1a=zeros(10,3)
Table_Fig1a[1,:].=99
Table_Fig1a[:,1].=99

Table_Fig1a[2,2]=agr_SCC
Table_Fig1a[3,2]=bio_SCC
Table_Fig1a[4,2]=energy_SCC
Table_Fig1a[5,2]=forest_SCC
Table_Fig1a[6,2]=health_alt_SCC
Table_Fig1a[7,2]=slr_SCC
Table_Fig1a[8,2]=storm_SCC
Table_Fig1a[9,2]=water_SCC
Table_Fig1a[10,2]=SCC

Table_Fig1a[2,3]=perc_agr_SCC
Table_Fig1a[3,3]=perc_bio_SCC
Table_Fig1a[4,3]=perc_energy_SCC
Table_Fig1a[5,3]=perc_forest_SCC
Table_Fig1a[6,3]=perc_health_alt_SCC
Table_Fig1a[7,3]=perc_slr_SCC
Table_Fig1a[8,3]=perc_storm_SCC
Table_Fig1a[9,3]=perc_water_SCC
Table_Fig1a[10,3]=1

Table_Fig1a

10×3 Matrix{Float64}:
 99.0  99.0       99.0
 99.0  -6.13817   -0.306942
 99.0   1.54445    0.0772308
 99.0  19.3873     0.969472
 99.0  -0.12688   -0.00634469
 99.0   1.74485    0.087252
 99.0   0.473332   0.0236692
 99.0   0.21179    0.0105906
 99.0   2.90112    0.145072
 99.0  19.9978     1.0

In [177]:
Table_Figure1a_row=(["Impact";"SCC";"% of SCC"])

3-element Vector{String}:
 "Impact"
 "SCC"
 "% of SCC"

In [178]:
Table1_Figure1a_col=["Agriculture";"Ecosystems";"Energy consumption";"Forestry";"Health";"Sea level rise";"Storms - non-health";"Water resources";"Total"]

9-element Vector{String}:
 "Agriculture"
 "Ecosystems"
 "Energy consumption"
 "Forestry"
 "Health"
 "Sea level rise"
 "Storms - non-health"
 "Water resources"
 "Total"

In [179]:
table_Fig1a=Array{String}(undef,10,3)
table_Fig1a[1,:]=["Impact";"SCC";"% of SCC"]
table_Fig1a[:,1]=["Impact";"Agriculture";"Ecosystems";"Energy consumption";"Forestry";"Health";"Sea level rise";"Storms - non-health";"Water resources";"Total"]


table_Fig1a[2:10,2]=[string(agr_SCC);string(bio_SCC);string(energy_SCC);string(forest_SCC);string(health_alt_SCC);string(slr_SCC);string(storm_SCC);string(water_SCC);string(SCC)]
table_Fig1a[2:10,3]=[string(perc_agr_SCC);string(perc_bio_SCC);string(perc_energy_SCC);string(perc_forest_SCC);string(perc_health_alt_SCC);string(perc_slr_SCC);string(perc_storm_SCC);string(perc_water_SCC);string(1)]


table_Fig1a

writedlm("../output/vsl0_fig1a.csv",table_Fig1a, ",")

In [180]:
Table_Fig1b=zeros(17,3)
Table_Fig1b[1,:].=99
Table_Fig1b[:,1].=99

for j=2:17
    Table_Fig1b[j,2]=pop_reg_2015[j-1]
    Table_Fig1b[j,3]=ypc_reg_2015[j-1]
    
end    

Table_Fig1b

17×3 Matrix{Float64}:
 99.0    99.0        99.0
 99.0   296.654   41658.9
 99.0    33.4312  29280.1
 99.0   394.807   34146.9
 99.0   192.842   45751.6
 99.0    23.554   32235.2
 99.0   126.784    4651.64
 99.0   293.47     2818.1
 99.0   316.064    3464.83
 99.0   154.359    4260.93
 99.0   414.734    5537.14
 99.0  1669.72      644.188
 99.0   629.428    2325.22
 99.0  1467.69     1543.52
 99.0   192.422    1732.22
 99.0   878.018     671.584
 99.0    53.3934   1573.77

In [181]:
Table_Figure1b_row=(["Regions";"2015 Population";"2015 GDP per Capita"])

3-element Vector{String}:
 "Regions"
 "2015 Population"
 "2015 GDP per Capita"

In [182]:
Table_Figure1b_col=["Regsions";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

17-element Vector{String}:
 "Regsions"
 "USA"
 "CAN"
 "WEU"
 "JPK"
 "ANZ"
 "CEE"
 "FSU"
 "MDE"
 "CAM"
 "SAM"
 "SAS"
 "SEA"
 "CHI"
 "NAF"
 "SSA"
 "SIS"

In [183]:
table_Fig1b=Array{String}(undef,17,3)
table_Fig1b[1,:]=["Regions";"2015 Population";"2015 GDP per Capita"]
table_Fig1b[:,1]=["Regions";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

table_Fig1b[2:17,2]=[string(pop_reg_2015[1]);string(pop_reg_2015[2]);string(pop_reg_2015[3]);string(pop_reg_2015[4]);string(pop_reg_2015[5]);string(pop_reg_2015[6]);string(pop_reg_2015[7]);string(pop_reg_2015[8]);string(pop_reg_2015[9]);string(pop_reg_2015[10]);string(pop_reg_2015[11]);string(pop_reg_2015[12]);string(pop_reg_2015[13]);string(pop_reg_2015[14]);string(pop_reg_2015[15]);string(pop_reg_2015[16])]
table_Fig1b[2:17,3]=[string(ypc_reg_2015[1]);string(ypc_reg_2015[2]);string(ypc_reg_2015[3]);string(ypc_reg_2015[4]);string(ypc_reg_2015[5]);string(ypc_reg_2015[6]);string(ypc_reg_2015[7]);string(ypc_reg_2015[8]);string(ypc_reg_2015[9]);string(ypc_reg_2015[10]);string(ypc_reg_2015[11]);string(ypc_reg_2015[12]);string(ypc_reg_2015[13]);string(ypc_reg_2015[14]);string(ypc_reg_2015[15]);string(ypc_reg_2015[16])]

table_Fig1b

writedlm("../output/vsl0_fig1b.csv",table_Fig1b, ",")

#### Alternative Regions

In [184]:
table_Fig1b_Reg=Array{String}(undef,4,3)
table_Fig1b_Reg[1,:]=["Regions";"2015 Population";"2015 GDP per Capita"]
table_Fig1b_Reg[:,1]=["Regions";"HIGH";"MEDIUM";"LOW"]

table_Fig1b_Reg[2:4,2]=[string(pop_high_2015);string(pop_med_2015);string(pop_low_2015)]
table_Fig1b_Reg[2:4,3]=[string(ypc_high_2015);string(ypc_med_2015);string(ypc_low_2015)]

table_Fig1b_Reg


writedlm("../output/vsl0_fig1b_Reg.csv",table_Fig1b_Reg, ",")

## Table - Figure 2

In [185]:
#table_Fig2=Array{String}(undef,11,17)
#table_Fig2[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
#table_Fig2[:,1]=["Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]

#for j=2:17
#    table_Fig2[2,j]=string(reg_perc_dv_SCC[j-1])
#    table_Fig2[3,j]=string(reg_perc_sv_SCC[j-1])
#    table_Fig2[4,j]=string(reg_perc_mv_SCC[j-1])
#    table_Fig2[5,j]=string(reg_perc_chr_SCC[j-1])
#    table_Fig2[6,j]=string(reg_perc_ccr_SCC[j-1])
#    table_Fig2[7,j]=string(reg_perc_resp_SCC[j-1])
#    table_Fig2[8,j]=string(reg_perc_diar_SCC[j-1])
#    table_Fig2[9,j]=string(reg_perc_hurr_SCC[j-1])
#    table_Fig2[10,j]=string(reg_perc_extra_SCC[j-1])
#    table_Fig2[11,j]=string(Reg_Perc_Health_SCC[j-1])
#end
#        
#table_Fig2
#
#writedlm("vsl0_Fig2.csv",table_Fig2, ",")

In [186]:
table_Fig2=Array{String}(undef,11,17)
table_Fig2[1,:]=["SCC by Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig2[:,1]=["SCC by Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]

for j=2:17
    table_Fig2[2,j]=string(reg_dv_SCC[j-1])
    table_Fig2[3,j]=string(reg_sv_SCC[j-1])
    table_Fig2[4,j]=string(reg_mv_SCC[j-1])
    table_Fig2[5,j]=string(reg_chr_SCC[j-1])
    table_Fig2[6,j]=string(reg_ccr_SCC[j-1])
    table_Fig2[7,j]=string(reg_resp_SCC[j-1])
    table_Fig2[8,j]=string(reg_diar_SCC[j-1])
    table_Fig2[9,j]=string(reg_hurr_SCC[j-1])
    table_Fig2[10,j]=string(reg_extra_SCC[j-1])
    table_Fig2[11,j]=string(reg_health_SCC[j-1])
end
        
table_Fig2

writedlm("../output/vsl0_Fig2.csv",table_Fig2, ",")

#### Alternative Regions

In [187]:
table_Fig2_Reg=Array{String}(undef,11,4)
table_Fig2_Reg[1,:]=["SCC by Endpoint/Region";"High";"Medium";"Low"]
table_Fig2_Reg[:,1]=["SCC by Endpoint/Region";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total Health"]


table_Fig2_Reg[2,2:4]=[string(dv_SCC_high);string(dv_SCC_med);string(dv_SCC_low)]
table_Fig2_Reg[3,2:4]=[string(sv_SCC_high);string(sv_SCC_med);string(sv_SCC_low)]
table_Fig2_Reg[4,2:4]=[string(mv_SCC_high);string(mv_SCC_med);string(mv_SCC_low)]
table_Fig2_Reg[5,2:4]=[string(chr_SCC_high);string(chr_SCC_med);string(chr_SCC_low)]
table_Fig2_Reg[6,2:4]=[string(ccr_SCC_high);string(ccr_SCC_med);string(ccr_SCC_low)]
table_Fig2_Reg[7,2:4]=[string(resp_SCC_high);string(resp_SCC_med);string(resp_SCC_low)]
table_Fig2_Reg[8,2:4]=[string(diar_SCC_high);string(diar_SCC_med);string(diar_SCC_low)]
table_Fig2_Reg[9,2:4]=[string(hurr_SCC_high);string(hurr_SCC_med);string(hurr_SCC_low)]
table_Fig2_Reg[10,2:4]=[string(extra_SCC_high);string(extra_SCC_med);string(extra_SCC_low)]
table_Fig2_Reg[11,2:4]=[string(health_SCC_high);string(health_SCC_med);string(health_SCC_low)]
        
table_Fig2_Reg

writedlm("../output/vsl0_Fig2_Reg.csv",table_Fig2_Reg, ",")

## Table - Appendix Figure 1

In [188]:
table_app1=Array{String}(undef,11,301)
table_app1[:,1]=["Mortalities by Endpoint/Year";"Dengue Fever";"Schistomiasis";"Malaria";"Cardiovascular - Heat";"Cardiovascular - Cold";"Respiratory";"Diarrhea";"Hurricane";"Extratropical";"Total"]

for j=2:301
    table_app1[1,j]=string(j-2+2000)
    table_app1[2,j]=string(dead_d_global[j-1])
    table_app1[3,j]=string(dead_s_global[j-1])
    table_app1[4,j]=string(dead_m_global[j-1])
    table_app1[5,j]=string(dead_ch_global[j-1])
    table_app1[6,j]=string(dead_cc_global[j-1])
    table_app1[7,j]=string(dead_r_global[j-1])
    table_app1[8,j]=string(dead_diah_global[j-1])
    table_app1[9,j]=string(dead_hurr_global[j-1])
    table_app1[10,j]=string(dead_extra_global[j-1])
    table_app1[11,j]=string(deaths_glob[j-1])
end

table_app1
table_app1b=permutedims(table_app1)

301×11 Matrix{String}:
 "Mortalities by Endpoint/Year"  …  "Total"
 "2000"                             "146329.3760479393"
 "2001"                             "151046.17592244447"
 "2002"                             "152292.32208001942"
 "2003"                             "154682.1588934941"
 "2004"                          …  "156637.28707168964"
 "2005"                             "158137.86526846"
 "2006"                             "159187.69793021708"
 "2007"                             "159776.56181101955"
 "2008"                             "159984.32029920336"
 "2009"                          …  "159766.82873739584"
 "2010"                             "159119.59059339002"
 "2011"                             "158032.50898717623"
 ⋮                               ⋱  ⋮
 "2288"                             "9045.241334117256"
 "2289"                          …  "8992.021033032002"
 "2290"                             "8939.392055863582"
 "2291"                             "8887.347844

In [189]:
writedlm("../output/vsl0_app1.csv",table_app1b, ",")

## Table_Fig3 

In [190]:
table_Fig3=Array{String}(undef,3,17)
table_Fig3[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig3[:,1]=["Endpoint/Region";"Health";"SCC"]

for j=2:17
    table_Fig3[2,j]=string(reg_health_SCC[j-1])
    table_Fig3[3,j]=string(SCC_reg[j-1])
end
        
table_Fig3
table_Fig3=permutedims(table_Fig3)

writedlm("../output/vsl0_table_fig3.csv",table_Fig3, ",")

#### Alternative Regions

In [191]:
table_Fig3_Reg=Array{String}(undef,3,4)
table_Fig3_Reg[1,:]=["Endpoint/Region";"High";"Medium";"Low"]
table_Fig3_Reg[:,1]=["Endpoint/Region";"Health";"SCC"]


table_Fig3_Reg[2,2:4]=[string(health_SCC_high);string(health_SCC_med);string(health_SCC_low)]
table_Fig3_Reg[3,2:4]=[string(SCC_high);string(SCC_med);string(SCC_low)]
        
table_Fig3_Reg
table_Fig3_Reg=permutedims(table_Fig3_Reg)

writedlm("../output/vsl0_fig3_Reg.csv",table_Fig3_Reg, ",")

## Table_Fig4

In [192]:
table_Fig4a=Array{String}(undef,6,17)
table_Fig4a[1,:]=["Endpoint/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]
table_Fig4a[:,1]=["Endpoint/Region";"Avg VSL";"Weighted VSL";"Deaths";"Avg Per Capita GDP";"Weighted Per Capita GDP"]

for j=2:17
    table_Fig4a[2,j]=string(vsl_reg_avg[j-1])
    table_Fig4a[3,j]=string(vsl_reg_pop_avg[j-1])
    table_Fig4a[4,j]=string(deaths_reg_sum[j-1])
    table_Fig4a[5,j]=string(ypc_reg_avg[j-1])
    table_Fig4a[6,j]=string(ypc_reg_pop_avg[j-1])
end
        
table_Fig4a
table_Fig4a=permutedims(table_Fig4a)

writedlm("../output/vsl0_fig4a.csv",table_Fig4a, ",")

In [193]:
table_Fig4b=Array{String}(undef,17,301)
table_Fig4b[:,1]=["VSL/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4b[1,j]=string(j-2+2000)
    table_Fig4b[2,j]=string(vsl_reg[j-1,1])
    table_Fig4b[3,j]=string(vsl_reg[j-1,2])
    table_Fig4b[4,j]=string(vsl_reg[j-1,3])
    table_Fig4b[5,j]=string(vsl_reg[j-1,4])
    table_Fig4b[6,j]=string(vsl_reg[j-1,5])
    table_Fig4b[7,j]=string(vsl_reg[j-1,6])
    table_Fig4b[8,j]=string(vsl_reg[j-1,7])
    table_Fig4b[9,j]=string(vsl_reg[j-1,8])
    table_Fig4b[10,j]=string(vsl_reg[j-1,9])
    table_Fig4b[11,j]=string(vsl_reg[j-1,10])
    table_Fig4b[12,j]=string(vsl_reg[j-1,11])
    table_Fig4b[13,j]=string(vsl_reg[j-1,12])
    table_Fig4b[14,j]=string(vsl_reg[j-1,13])
    table_Fig4b[15,j]=string(vsl_reg[j-1,14])
    table_Fig4b[16,j]=string(vsl_reg[j-1,15])
    table_Fig4b[17,j]=string(vsl_reg[j-1,16])
    
end

table_Fig4b
table_Fig4b=permutedims(table_Fig4b)
writedlm("../output/vsl0_fig4b.csv",table_Fig4b, ",")

In [194]:
table_Fig4c=Array{String}(undef,17,301)
table_Fig4c[:,1]=["Mortalities/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4c[1,j]=string(j-2+2000)
    table_Fig4c[2,j]=string(deaths_reg[j-1,1])
    table_Fig4c[3,j]=string(deaths_reg[j-1,2])
    table_Fig4c[4,j]=string(deaths_reg[j-1,3])
    table_Fig4c[5,j]=string(deaths_reg[j-1,4])
    table_Fig4c[6,j]=string(deaths_reg[j-1,5])
    table_Fig4c[7,j]=string(deaths_reg[j-1,6])
    table_Fig4c[8,j]=string(deaths_reg[j-1,7])
    table_Fig4c[9,j]=string(deaths_reg[j-1,8])
    table_Fig4c[10,j]=string(deaths_reg[j-1,9])
    table_Fig4c[11,j]=string(deaths_reg[j-1,10])
    table_Fig4c[12,j]=string(deaths_reg[j-1,11])
    table_Fig4c[13,j]=string(deaths_reg[j-1,12])
    table_Fig4c[14,j]=string(deaths_reg[j-1,13])
    table_Fig4c[15,j]=string(deaths_reg[j-1,14])
    table_Fig4c[16,j]=string(deaths_reg[j-1,15])
    table_Fig4c[17,j]=string(deaths_reg[j-1,16])
    
end

table_Fig4c
table_Fig4c=permutedims(table_Fig4c)
writedlm("../output/vsl0_fig4c.csv",table_Fig4c, ",")

In [195]:
table_Fig4d=Array{String}(undef,17,301)
table_Fig4d[:,1]=["YPC/Region";"USA";"CAN"; "WEU";"JPK";"ANZ";"CEE";"FSU";"MDE";"CAM";"SAM";"SAS";"SEA";"CHI";"NAF";"SSA";"SIS"]

for j=2:301
    table_Fig4d[1,j]=string(j-2+2000)
    table_Fig4d[2,j]=string(ypc_reg[j-1,1])
    table_Fig4d[3,j]=string(ypc_reg[j-1,2])
    table_Fig4d[4,j]=string(ypc_reg[j-1,3])
    table_Fig4d[5,j]=string(ypc_reg[j-1,4])
    table_Fig4d[6,j]=string(ypc_reg[j-1,5])
    table_Fig4d[7,j]=string(ypc_reg[j-1,6])
    table_Fig4d[8,j]=string(ypc_reg[j-1,7])
    table_Fig4d[9,j]=string(ypc_reg[j-1,8])
    table_Fig4d[10,j]=string(ypc_reg[j-1,9])
    table_Fig4d[11,j]=string(ypc_reg[j-1,10])
    table_Fig4d[12,j]=string(ypc_reg[j-1,11])
    table_Fig4d[13,j]=string(ypc_reg[j-1,12])
    table_Fig4d[14,j]=string(ypc_reg[j-1,13])
    table_Fig4d[15,j]=string(ypc_reg[j-1,14])
    table_Fig4d[16,j]=string(ypc_reg[j-1,15])
    table_Fig4d[17,j]=string(ypc_reg[j-1,16])
    
end

table_Fig4d
table_Fig4d=permutedims(table_Fig4d)
writedlm("../output/vsl0_fig4d.csv",table_Fig4d, ",")

#### Alternative Regions

In [196]:
table_Fig4a_Reg=Array{String}(undef,5,4)
table_Fig4a_Reg[1,:]=["Endpoint/Region";"High";"Medium";"Low"]
table_Fig4a_Reg[:,1]=["Endpoint/Region";"Avg VSL";"Weighted VSL";"Deaths";"Avg Per Capita GDP"]


table_Fig4a_Reg[2,2:4]=[string(vsl_high_avg);string(vsl_med_avg);string(vsl_low_avg)]
table_Fig4a_Reg[3,2:4]=[string(vsl_high_pop_avg);string(vsl_med_pop_avg);string(vsl_low_pop_avg)]
table_Fig4a_Reg[4,2:4]=[string(dead_high_sum);string(dead_med_sum);string(dead_low_sum)]
table_Fig4a_Reg[5,2:4]=[string(ypc_high_avg);string(ypc_med_avg);string(ypc_low_avg)]

        
table_Fig4a_Reg
table_Fig4a_Reg=permutedims(table_Fig4a_Reg)

writedlm("../output/vsl0_fig4a_Reg.csv",table_Fig4a_Reg, ",")

In [197]:
table_Fig4b_Reg=Array{String}(undef,4,301)
table_Fig4b_Reg[:,1]=["VSL/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4b_Reg[1,j]=string(j-2+2000)
    table_Fig4b_Reg[2,j]=string(vsl_high[j-1])
    table_Fig4b_Reg[3,j]=string(vsl_med[j-1])
    table_Fig4b_Reg[4,j]=string(vsl_low[j-1])    
end

table_Fig4b_Reg
table_Fig4b_Reg=permutedims(table_Fig4b_Reg)
writedlm("../output/vsl0_fig4b_Reg.csv",table_Fig4b_Reg, ",")

In [198]:
table_Fig4c_Reg=Array{String}(undef,4,301)
table_Fig4c_Reg[:,1]=["Mortalities/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4c_Reg[1,j]=string(j-2+2000)
    table_Fig4c_Reg[2,j]=string(dead_high[j-1])
    table_Fig4c_Reg[3,j]=string(dead_med[j-1])
    table_Fig4c_Reg[4,j]=string(dead_low[j-1])
end

table_Fig4c_Reg
table_Fig4c_Reg=permutedims(table_Fig4c_Reg)
writedlm("../output/vsl0_fig4c_Reg.csv",table_Fig4c_Reg, ",")

In [199]:
table_Fig4d_Reg=Array{String}(undef,4,301)
table_Fig4d_Reg[:,1]=["YPC/Region";"High";"Medium";"Low"]

for j=2:301
    table_Fig4d_Reg[1,j]=string(j-2+2000)
    table_Fig4d_Reg[2,j]=string(ypc_high[j-1])
    table_Fig4d_Reg[3,j]=string(ypc_med[j-1])
    table_Fig4d_Reg[4,j]=string(ypc_low[j-1])
end

table_Fig4d_Reg
table_Fig4d_Reg=permutedims(table_Fig4d_Reg)
writedlm("../output/vsl0_fig4d_Reg.csv",table_Fig4d_Reg, ",")